package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 16-sep-2011 13:45:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * AccionDocumento generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ACCIONES_DOCUMENTOS", uniqueConstraints = @UniqueConstraint(columnNames = "C_ACDO"))
public class AccionDocumento implements java.io.Serializable {

	private static final long serialVersionUID = 626439101036258127L;

	private Long id;
	private Date version;
	private String codigo;
	private String descripcion;
	private String codUsuarioBloq;
	private String externos;
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<ActoMasivo> actosMasivos = new HashSet<ActoMasivo>(0);


	public AccionDocumento() {
	}

	@Id 
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ACDO_X_ACDO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ACDO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "C_ACDO", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "D_ACDO", nullable = false, length = 240)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 30)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@Column(name = "L_EXTERNOS", nullable = false, length = 1)
	public String getExternos() {
		return this.externos;
	}

	public void setExternos(String externos) {
		this.externos = externos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accionDocumento")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccionDocumento))
			return false;
		AccionDocumento castOther = (AccionDocumento) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accionDocumento")
	public Set<ActoMasivo> getActosMasivos() {
		return this.actosMasivos;
	}

	public void setActosMasivos(Set<ActoMasivo> actosMasivos) {
		this.actosMasivos = actosMasivos;
	}

}
