package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 05-mar-2012 9:06:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * ActoRespaldo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ACTO_RESPALDO")
public class ActoRespaldo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 423449062033615710L;
	private Long id;
	private Date version;
	private FuncSuplidoReemplazado funcSuplidoReemplazado;
	private String cali;
	private Date fechaDesde;
	private Date fechaHasta;
	private Date fechaResolucion;
	private String descripcionCalidad;
	private String descripcionPlantaCargo;
	private String descripcionCargo;
	private String descripcionGrado;
	private Long numHoras;
	private String numResolucion;
	private String designacionHonorario;
	private String codDesignacionHonorario;
	private String codUsuarioBloq;
	private Set<DocumentoRespaldo> documentoRespaldos = new HashSet<DocumentoRespaldo>(0);

	public ActoRespaldo() {
	}

	public ActoRespaldo(FuncSuplidoReemplazado funcSuplidoReemplazado) {
		this.funcSuplidoReemplazado = funcSuplidoReemplazado;
	}

	public ActoRespaldo(FuncSuplidoReemplazado funcSuplidoReemplazado,
			String cali, Date fechaDesde, Date fechaHasta,
			Date fechaResolucion, String numResolucion,
			String designacionHonorario, String codDesignacionHonorario,
			Set<DocumentoRespaldo> documentoRespaldos) {
		this.funcSuplidoReemplazado = funcSuplidoReemplazado;
		this.cali = cali;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.fechaResolucion = fechaResolucion;
		this.numResolucion = numResolucion;
		this.designacionHonorario = designacionHonorario;
		this.codDesignacionHonorario = codDesignacionHonorario;
		this.documentoRespaldos = documentoRespaldos;
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ACRE_X_ACRE")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ACRE", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUSR_X_FUSR", nullable = false)
	public FuncSuplidoReemplazado getFuncSuplidoReemplazado() {
		return this.funcSuplidoReemplazado;
	}

	public void setFuncSuplidoReemplazado(
			FuncSuplidoReemplazado funcSuplidoReemplazado) {
		this.funcSuplidoReemplazado = funcSuplidoReemplazado;
	}
	
	@Column(name = "S_CALI", precision = 12, scale = 0)
	public String getCali() {
		return this.cali;
	}

	public void setCali(String cali) {
		this.cali = cali;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_DESDE", length = 7)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_HASTA", length = 7)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_RESOLUCION", length = 7)
	public Date getFechaResolucion() {
		return this.fechaResolucion;
	}

	public void setFechaResolucion(Date fechaResolucion) {
		this.fechaResolucion = fechaResolucion;
	}

	@Column(name = "T_NUM_RESOLUCION", length = 255)
	public String getNumResolucion() {
		return this.numResolucion;
	}

	public void setNumResolucion(String numResolucion) {
		this.numResolucion = numResolucion;
	}

	@Column(name = "S_DESIGNACION_HONORARIO", length = 1)
	public String getDesignacionHonorario() {
		return this.designacionHonorario;
	}

	public void setDesignacionHonorario(String designacionHonorario) {
		this.designacionHonorario = designacionHonorario;
	}

	@Column(name = "C_DESIGNACION_HONORARIO", length = 12)
	public String getCodDesignacionHonorario() {
		return this.codDesignacionHonorario;
	}

	public void setCodDesignacionHonorario(String codDesignacionHonorario) {
		this.codDesignacionHonorario = codDesignacionHonorario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actoRespaldo", cascade = CascadeType.ALL)
	public Set<DocumentoRespaldo> getDocumentoRespaldos() {
		return this.documentoRespaldos;
	}

	public void setDocumentoRespaldos(Set<DocumentoRespaldo> documentoRespaldos) {
		this.documentoRespaldos = documentoRespaldos;
	}
	
	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "D_CALIDAD", length = 255)
	public String getDescripcionCalidad() {
		return descripcionCalidad;
	}

	public void setDescripcionCalidad(String descripcionCalidad) {
		this.descripcionCalidad = descripcionCalidad;
	}

	@Column(name = "D_PLANTA_CARGO", length = 255)
	public String getDescripcionPlantaCargo() {
		return descripcionPlantaCargo;
	}

	public void setDescripcionPlantaCargo(String descripcionPlantaCargo) {
		this.descripcionPlantaCargo = descripcionPlantaCargo;
	}

	@Column(name = "D_CARGO", length = 255)
	public String getDescripcionCargo() {
		return descripcionCargo;
	}

	public void setDescripcionCargo(String descripcionCargo) {
		this.descripcionCargo = descripcionCargo;
	}

	@Column(name = "D_GRADO", length = 255)
	public String getDescripcionGrado() {
		return descripcionGrado;
	}

	public void setDescripcionGrado(String descripcionGrado) {
		this.descripcionGrado = descripcionGrado;
	}

	@Column(name = "N_HORAS", length = 3)
	public Long getNumHoras() {
		return numHoras;
	}

	public void setNumHoras(Long numHoras) {
		this.numHoras = numHoras;
	}
}
