package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 07-jul-2017 9:24:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * ActosMasivo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ACTOS_MASIVO")
public class ActoMasivo implements Serializable, Entidad {
	
	private static final long serialVersionUID = -5149907716705255095L;
	private Long id;
	private TipoDocumento tipoDocumento;
	private Servicio dependenciaEmisora;
	private Servicio servicioEmisor;
	private CargaMasiva cargaMasiva;
	private String numDocu;
	private Date fechaDocumento;
	private Date version;
	private String servicioEmisorPreview;
	private AccionDocumento accionDocumento;
	private Fichero preview;
	private String hashPlanilla;
	private Integer nVersion;
	private boolean previewRegistro;

	private Set<CasoMasivo> casosMasivo = new HashSet<CasoMasivo>(0);

	public ActoMasivo() {
	}

	public ActoMasivo(TipoDocumento tipoDocumento,
	                   Servicio dependenciaEmisora,
	                   Servicio servicioEmisor,
	                   String numDocu,
	                   Date fechaDocumento,
	                   CargaMasiva cargaMasiva) {

		this.tipoDocumento = tipoDocumento;
		this.dependenciaEmisora = dependenciaEmisora;
		this.servicioEmisor = servicioEmisor;
		this.numDocu = numDocu;
		this.fechaDocumento = fechaDocumento;
		this.cargaMasiva = cargaMasiva;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ACMA_X_ACMA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ACMA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIDO_X_TIDO", nullable = false)
	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SERV_X_SERV_DEP_EMI")
	public Servicio getDependenciaEmisora() {
		return dependenciaEmisora;
	}
	
	public void setDependenciaEmisora(Servicio dependenciaEmisora) {
		this.dependenciaEmisora = dependenciaEmisora;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SERV_X_SERV_E", nullable = false)
	public Servicio getServicioEmisor() {
		return servicioEmisor;
	}
	
	public void setServicioEmisor(Servicio servicioEmisor) {
		this.servicioEmisor = servicioEmisor;
	}
	
	@Column(name = "T_NUM_DOCU", nullable = false, length = 150)
	public String getNumDocu() {
		return this.numDocu;
	}

	public void setNumDocu(String numDocu) {
		this.numDocu = numDocu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "F_FECHA_DOCUMENTO", nullable = false, length = 7)
	public Date getFechaDocumento() {
		return this.fechaDocumento;
	}

	public void setFechaDocumento(Date fechaDocumento) {
		this.fechaDocumento = fechaDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "CAMA_X_CAMA")
	public CargaMasiva getCargaMasiva() {
		return this.cargaMasiva;
	}

	public void setCargaMasiva(CargaMasiva cargaMasiva) {

		this.cargaMasiva = cargaMasiva;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actoMasivo", cascade = CascadeType.ALL)
	public Set<CasoMasivo> getCasosMasivo() {
		return this.casosMasivo;
	}

	public void setCasosMasivo(Set<CasoMasivo> casosMasivo) {
		this.casosMasivo = casosMasivo;
	}

	/**
	 * @return the servicioEmisorPreview
	 */
	@Transient
	public String getServicioEmisorPreview() {
		return servicioEmisorPreview;
	}

	/**
	 * @param servicioEmisorPreview the servicioEmisorPreview to set
	 */
	public void setServicioEmisorPreview(String servicioEmisorPreview) {
		this.servicioEmisorPreview = servicioEmisorPreview;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACDO_X_ACDO", nullable = false)
	public AccionDocumento getAccionDocumento() {
		return this.accionDocumento;
	}

	public void setAccionDocumento(AccionDocumento accionDocumento) {
		this.accionDocumento = accionDocumento;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "FICH_X_FICH")
	public Fichero getPreview() {
		return this.preview;
	}

	public void setPreview(Fichero ficheros) {
		this.preview = ficheros;
	}
	
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActoMasivo))
			return false;
		ActoMasivo castOther = (ActoMasivo) other;
		
		//return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
		
		// Comprobemos si se trata de un acto ya registrado: 
		// N° de Documento
		// Tipo de Documento
		// Fecha de Documento
		// Servicio Emisor
		// Dependencia Emisora -> Puede ser null
		
		if (this.getNumDocu() != null && castOther.getNumDocu() != null && this.getNumDocu().equals(castOther.getNumDocu())) {
			if (this.getTipoDocumento() != null && castOther.getTipoDocumento() != null && this.getTipoDocumento().equals(castOther.getTipoDocumento())) {
				if (this.getFechaDocumento() != null && castOther.getFechaDocumento() != null && this.getFechaDocumento().equals(castOther.getFechaDocumento())) {
					if (this.getServicioEmisor() != null && castOther.getServicioEmisor() != null && this.getServicioEmisor().equals(castOther.getServicioEmisor())) {
						if (this.getDependenciaEmisora() != null && castOther.getDependenciaEmisora() != null && this.getDependenciaEmisora().equals(castOther.getDependenciaEmisora())) {
							return true;
						} else if (this.getDependenciaEmisora() == null && castOther.getDependenciaEmisora() == null) {
							return true;
						}
					}
				}
			}
		}

		return false;
		
	}

	/**
	 * @return the hashPlanilla
	 */
	@Column(name = "T_PLANTILLA_RESOLUCION", length = 500)
	public String getHashPlanilla() {
		return hashPlanilla;
	}

	/**
	 * @param hashPlanilla the hashPlanilla to set
	 */
	public void setHashPlanilla(String hashPlanilla) {
		this.hashPlanilla = hashPlanilla;
	}
	
	@Column(name = "N_VERSION", length = 9)
	public Integer getNVersion() {
		return nVersion;
	}

	public void setNVersion(Integer nVersion) {
		this.nVersion = nVersion;
	}
	
	@Column(name = "L_PREWREG", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isPreviewRegistro() {
		return this.previewRegistro;
	}

	public void setPreviewRegistro(boolean previewRegistro) {
		this.previewRegistro = previewRegistro;
	}

}