package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 11-oct-2011 11:53:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Access;
import jakarta.persistence.AccessType;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * AnexoCaso generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ANEXOS_CASOS")
public class AnexoCaso implements java.io.Serializable {

	private static final long serialVersionUID = 1701377974897325425L;

	private Long id;
	private Date version;
	private CasoDocumento casoDocumento;
	private Fichero fichero;
	private MedioVerificacion medioVerificacion;
	private String observaciones;
	private String atributo;
	private String codUsuarioBloq;
	
	private Requisito requisito;
	
	/**
	 * Atributo Transient
	 * Indica si el fichero está en el CM
	 */
	private boolean existeFichero;

	public AnexoCaso() {
	}

	public AnexoCaso(Long id) {
		this.id = id;
	}
	
	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ANCA_X_ANCA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ANCA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CADO_X_CADO", nullable = false)
	public CasoDocumento getCasoDocumento() {
		return this.casoDocumento;
	}

	public void setCasoDocumento(CasoDocumento casoDocumento) {
		this.casoDocumento = casoDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
	@JoinColumn(name = "FICH_X_FICH")
	public Fichero getFichero() {
		return this.fichero;
	}

	public void setFichero(Fichero fichero) {
		this.fichero = fichero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEVE_X_MEVE", nullable = false)
	public MedioVerificacion getMedioVerificacion() {
		return this.medioVerificacion;
	}

	public void setMedioVerificacion(MedioVerificacion medioVerificacion) {
		this.medioVerificacion = medioVerificacion;
	}

	@Column(name = "T_OBSERVACIONES", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "T_ATRIBUTO", length = 250)
	public String getAtributo() {
		return this.atributo;
	}

	public void setAtributo(String atributo) {
		this.atributo = atributo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
    @Transient
	public Requisito getRequisito() {
		return requisito;
	}

	public void setRequisito(Requisito requisito) {
		this.requisito = requisito;
	}

	@Transient
	public boolean getExisteFichero() {
		return existeFichero;
	}

	public void setExisteFichero(boolean existeFichero) {
		this.existeFichero = existeFichero;
	}


	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnexoCaso))
			return false;
		AnexoCaso castOther = (AnexoCaso) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
//	public String toString() {
//		StringBuilder datos = new StringBuilder();
//		datos.append("Anexo: ");
//		datos.append(medioVerificacion.getCodigo());
//		if (fichero != null) {
//			datos.append(", fichero: ");
//			datos.append(fichero.getHash());
//		}
//		datos.append(", Caso: (");
//		datos.append(casoDocumento.getRun());
//		datos.append(" - ");
//		datos.append(casoDocumento.getApellidos());
//		datos.append(", ");
//		datos.append(casoDocumento.getNombres());
//		datos.append(" - Documento: ");
//		datos.append(casoDocumento.getDocumento().getNumDocuFirmado() == null ? casoDocumento.getDocumento().getNumDocuBorrador() : casoDocumento.getDocumento().getNumDocuFirmado());
//		datos.append(")");
//		return datos.toString();
//	}


	//add siaper-ru
	public String toStringJson() {
	    StringBuilder sb = new StringBuilder();
	    sb.append("{\n");

	    sb.append("  \"id\": ").append(id).append(",\n");
	    sb.append("  \"version\": ").append(version != null ? "\"" + version + "\"" : null).append(",\n");
	    sb.append("  \"casoDocumento\": ").append(casoDocumento != null ? "\"" + casoDocumento.getId() + "\"" : null).append(",\n");
	    sb.append("  \"fichero\": ").append(fichero != null ? "\"" + fichero.toString() + "\"" : null).append(",\n");
	    sb.append("  \"medioVerificacion\": ").append(medioVerificacion != null ? "\"" + medioVerificacion.toString() + "\"" : null).append(",\n");
	    sb.append("  \"observaciones\": ").append(observaciones != null ? "\"" + observaciones + "\"" : null).append(",\n");
	    sb.append("  \"atributo\": ").append(atributo != null ? "\"" + atributo + "\"" : null).append(",\n");
	    sb.append("  \"codUsuarioBloq\": ").append(codUsuarioBloq != null ? "\"" + codUsuarioBloq + "\"" : null).append(",\n");
	    sb.append("  \"requisito\": ").append(requisito != null ? "\"" + requisito.toStringJson() + "\"" : null).append(",\n");
	    sb.append("  \"existeFichero\": ").append(existeFichero).append("\n");

	    sb.append("}");

	    return sb.toString();
	}

}
