package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 28-oct-2011 13:37:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

//import org.hibernate.annotations.Type;
import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

import com.fasterxml.jackson.annotation.JsonIgnore;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * AntecedenteEducacional generated by hbm2java
 */
@Entity
@Audited
@AuditTable("TRA_ANTECEDENTES_EDUCACIO_HIST")
@Table(name = "TRA_ANTECEDENTES_EDUCACIONALES")
public class AntecedenteEducacional implements java.io.Serializable, Cloneable {

	private static final long serialVersionUID = 7116748248573358886L;

	private Long id;
	private Date version;
	private CasoDocumento casoDocumento;
	private EnsenianzaMedia ensenianzaMedia;
	private EntidadInteroperable entidadInteroperable;
	private Fichero fichero;
	private Pais pais;
	private EntidadOtorgadora entidadOtorgadora;
	private Titulo titulo;
	private GradoAcademico gradoAcademico;
	private TipoEstudio tipoEstudio;
	private NivelEducacional nivelEducacional;
	private NivelConvalidado nivelConvalidado;
	private FormaFinanciamiento formaFinanciamiento;
	private NivelDocente nivelDocente;
	private NivelEstudioFormal nivelEstudioFormal;
	private MateriaConvalida materiaConvalida;
	private Boolean interoperable;
	private Boolean aprobadoIntegro;
	private Short numAnioEgreso;
	private String establecimiento;
	private String estudioInteroper;
	private Short numAnioUltimo;
	private Boolean mediaLaboral;
	private String descEstudio;
	private String descEstudioOriginal;
	private Date fechaOtorgamiento;
	private String descOtorgado;
	private Boolean tieneOtroTitulo;
	private String otroTitulo;
	private String mencion;
	private String mencionOriginal;
	private Byte numSemestres;
	private Byte numSemestresAprob;
	private Short numHoras;
	private Short numHorasPedag;
	private Boolean tecnicoSuperior;
	private Boolean tecnicoMedio;
	private Date fechaConvalidacion;
	private Date fechaDesde;
	private Date fechaHasta;
	private String codUsuarioBloq;
	private Long codSiaper;
	private boolean errorIndicadoEstudio;
	
	private Boolean esNuevo;

	private TipoDocumento tipoDocumento;
	private Servicio servicio;
	private String glosaEducacional;
	
	private String agregadoPor;
	
	/**
	 * Atributo Transient
	 * Indica si el fichero está en el CM
	 */
	private boolean existeFichero;


	public AntecedenteEducacional() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ANED_X_ANED")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ANED", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CADO_X_CADO", nullable = false)
	@JsonIgnore //add siaper-ru
	public CasoDocumento getCasoDocumento() {
		return this.casoDocumento;
	}

	public void setCasoDocumento(CasoDocumento casoDocumento) {
		this.casoDocumento = casoDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "FICH_X_FICH")
	@JsonIgnore //add siaper-ru
	public Fichero getFichero() {
		return this.fichero;
	}

	public void setFichero(Fichero fichero) {
		this.fichero = fichero;
	}
	
	@Column(name = "S_ESTUDIO", precision = 10, scale = 0)
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAIS_X_PAIS")
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENOT_X_ENOT")
	public EntidadOtorgadora getEntidadOtorgadora() {
		return this.entidadOtorgadora;
	}

	public void setEntidadOtorgadora(EntidadOtorgadora entidadOtorgadora) {
		this.entidadOtorgadora = entidadOtorgadora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TITU_X_TITU")
	public Titulo getTitulo() {
		return this.titulo;
	}

	public void setTitulo(Titulo titulo) {
		this.titulo = titulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRAC_X_GRAC")
	public GradoAcademico getGradoAcademico() {
		return this.gradoAcademico;
	}

	public void setGradoAcademico(GradoAcademico gradoAcademico) {
		this.gradoAcademico = gradoAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIES_X_TIES", nullable = false)
	public TipoEstudio getTipoEstudio() {
		return this.tipoEstudio;
	}

	public void setTipoEstudio(TipoEstudio tipoEstudio) {
		this.tipoEstudio = tipoEstudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NIED_X_NIED")
	public NivelEducacional getNivelEducacional() {
		return this.nivelEducacional;
	}

	public void setNivelEducacional(NivelEducacional nivelEducacional) {
		this.nivelEducacional = nivelEducacional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FOFI_X_FOFI")
	public FormaFinanciamiento getFormaFinanciamiento() {
		return this.formaFinanciamiento;
	}

	public void setFormaFinanciamiento(FormaFinanciamiento formaFinanciamiento) {
		this.formaFinanciamiento = formaFinanciamiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NIDO_X_NIDO")
	public NivelDocente getNivelDocente() {
		return this.nivelDocente;
	}

	public void setNivelDocente(NivelDocente nivelDocente) {
		this.nivelDocente = nivelDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NIEF_X_NIEF")
	public NivelEstudioFormal getNivelEstudioFormal() {
		return this.nivelEstudioFormal;
	}

	public void setNivelEstudioFormal(NivelEstudioFormal nivelEstudioFormal) {
		this.nivelEstudioFormal = nivelEstudioFormal;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NICO_X_NICO")
	public NivelConvalidado getNivelConvalidado() {
		return nivelConvalidado;
	}

	public void setNivelConvalidado(NivelConvalidado nivelConvalidado) {
		this.nivelConvalidado = nivelConvalidado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MACO_X_MACO")
	public MateriaConvalida getMateriaConvalida() {
		return this.materiaConvalida;
	}

	public void setMateriaConvalida(MateriaConvalida materiaConvalida) {
		this.materiaConvalida = materiaConvalida;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENME_X_ENME")
	public EnsenianzaMedia getEnsenianzaMedia() {
		return this.ensenianzaMedia;
	}

	public void setEnsenianzaMedia(EnsenianzaMedia ensenianzaMedia) {
		this.ensenianzaMedia = ensenianzaMedia;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENIN_X_ENIN")
	public EntidadInteroperable getEntidadInteroperable() {
		return entidadInteroperable;
	}

	public void setEntidadInteroperable(EntidadInteroperable entidadInteroperable) {
		this.entidadInteroperable = entidadInteroperable;
	}

	@Column(name = "L_INTEROPERABLE", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getInteroperable() {
		return this.interoperable;
	}

	public void setInteroperable(Boolean interoperable) {
		this.interoperable = interoperable;
	}

	@Column(name = "L_APROBADO_INTEGRO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getAprobadoIntegro() {
		return this.aprobadoIntegro;
	}

	public void setAprobadoIntegro(Boolean aprobadoIntegro) {
		this.aprobadoIntegro = aprobadoIntegro;
	}

	@Column(name = "N_ANIO_EGRESO", precision = 4, scale = 0)
	public Short getNumAnioEgreso() {
		return this.numAnioEgreso;
	}

	public void setNumAnioEgreso(Short numAnioEgreso) {
		this.numAnioEgreso = numAnioEgreso;
	}

	@Column(name = "T_ESTABLECIMIENTO", length = 150)
	public String getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(String establecimiento) {
		this.establecimiento = establecimiento;
	}
	
	@Column(name = "C_ESTUDIO_INTEROPER", length = 150)
	public String getEstudioInteroper() {
		return estudioInteroper;
	}

	public void setEstudioInteroper(String estudioInteroper) {
		this.estudioInteroper = estudioInteroper;
	}

	@Column(name = "N_ANIO_ULTIMO", precision = 4, scale = 0)
	public Short getNumAnioUltimo() {
		return this.numAnioUltimo;
	}

	public void setNumAnioUltimo(Short numAnioUltimo) {
		this.numAnioUltimo = numAnioUltimo;
	}

	@Column(name = "L_MEDIA_LABORAL", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getMediaLaboral() {
		return this.mediaLaboral;
	}

	public void setMediaLaboral(Boolean mediaLaboral) {
		this.mediaLaboral = mediaLaboral;
	}

	@Column(name = "D_ESTUDIO", length = 150)
	public String getDescEstudio() {
		return this.descEstudio;
	}

	public void setDescEstudio(String descEstudio) {
		this.descEstudio = descEstudio;
	}

	@Column(name = "D_ESTUDIO_ORIGINAL", length = 150)
	public String getDescEstudioOriginal() {
		return this.descEstudioOriginal;
	}

	public void setDescEstudioOriginal(String descEstudioOriginal) {
		this.descEstudioOriginal = descEstudioOriginal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_OTORGAMIENTO", length = 7)
	public Date getFechaOtorgamiento() {
		return this.fechaOtorgamiento;
	}

	public void setFechaOtorgamiento(Date fechaOtorgamiento) {
		this.fechaOtorgamiento = fechaOtorgamiento;
	}

	@Column(name = "D_OTORGADO", length = 150)
	public String getDescOtorgado() {
		return this.descOtorgado;
	}

	public void setDescOtorgado(String descOtorgado) {
		this.descOtorgado = descOtorgado;
	}

	@Column(name = "L_TIENE_OTRO_TITULO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getTieneOtroTitulo() {
		return this.tieneOtroTitulo;
	}

	public void setTieneOtroTitulo(Boolean tieneOtroTitulo) {
		this.tieneOtroTitulo = tieneOtroTitulo;
	}

	@Column(name = "T_OTRO_TITULO", length = 150)
	public String getOtroTitulo() {
		return this.otroTitulo;
	}

	public void setOtroTitulo(String otroTitulo) {
		this.otroTitulo = otroTitulo;
	}

	@Column(name = "T_MENCION", length = 150)
	public String getMencion() {
		return this.mencion;
	}

	public void setMencion(String mencion) {
		this.mencion = mencion;
	}

	@Column(name = "T_MENCION_ORIGINAL", length = 150)
	public String getMencionOriginal() {
		return this.mencionOriginal;
	}

	public void setMencionOriginal(String mencionOriginal) {
		this.mencionOriginal = mencionOriginal;
	}

	@Column(name = "N_SEMESTRES", precision = 2, scale = 0)
	public Byte getNumSemestres() {
		return this.numSemestres;
	}

	public void setNumSemestres(Byte numSemestres) {
		this.numSemestres = numSemestres;
	}

	@Column(name = "N_SEMESTRES_APROB", precision = 2, scale = 0)
	public Byte getNumSemestresAprob() {
		return this.numSemestresAprob;
	}

	public void setNumSemestresAprob(Byte numSemestresAprob) {
		this.numSemestresAprob = numSemestresAprob;
	}

	@Column(name = "N_HORAS", precision = 4, scale = 0)
	public Short getNumHoras() {
		return this.numHoras;
	}

	public void setNumHoras(Short numHoras) {
		this.numHoras = numHoras;
	}

	@Column(name = "N_HORAS_PEDAG", precision = 4, scale = 0)
	public Short getNumHorasPedag() {
		return this.numHorasPedag;
	}

	public void setNumHorasPedag(Short numHorasPedag) {
		this.numHorasPedag = numHorasPedag;
	}

	@Column(name = "L_TECNICO_SUPERIOR", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getTecnicoSuperior() {
		return this.tecnicoSuperior;
	}

	public void setTecnicoSuperior(Boolean tecnicoSuperior) {
		this.tecnicoSuperior = tecnicoSuperior;
	}

	@Column(name = "L_ERROR_INDICADO_ESTUDIO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isErrorIndicadoEstudio() {
		return errorIndicadoEstudio;
	}

	public void setErrorIndicadoEstudio(boolean errorIndicadoEstudio) {
		this.errorIndicadoEstudio = errorIndicadoEstudio;
	}

	@Column(name = "L_TECNICO_MEDIO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getTecnicoMedio() {
		return this.tecnicoMedio;
	}

	public void setTecnicoMedio(Boolean tecnicoMedio) {
		this.tecnicoMedio = tecnicoMedio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_CONVALIDACION", length = 7)
	public Date getFechaConvalidacion() {
		return this.fechaConvalidacion;
	}

	public void setFechaConvalidacion(Date fechaConvalidacion) {
		this.fechaConvalidacion = fechaConvalidacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_DESDE", length = 7)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_HASTA", length = 7)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	
	@Column(name = "T_GLOSA_EDUCACION", length = 2000)
	public String getGlosaEducacional() {
		return this.glosaEducacional;
	}

	public void setGlosaEducacional(String glosaEducacional) {
		this.glosaEducacional = glosaEducacional;
	}
	
	@Column(name = "D_AGREGADO", length = 256)
	public String getAgregadoPor() {
		return this.agregadoPor;
	}

	public void setAgregadoPor(String agregadoPor) {
		this.agregadoPor = agregadoPor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AntecedenteEducacional))
			return false;
		AntecedenteEducacional castOther = (AntecedenteEducacional) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	public AntecedenteEducacional clone() {
		try {
			return (AntecedenteEducacional) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}

	@Transient
	public TipoDocumento getTipoDocumento() {
		return tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}
	
	@Transient
	public Servicio getServicio() {
		return servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}
	
	@Transient
	public String getTituloCertificadoLicen() {
		if (titulo != null) {
			return titulo.getDescripcion();
		} else {
			return descEstudioOriginal;
		}
	}
	
	@Transient
	public Boolean getEsNuevo() {
		return esNuevo;
	}

	public void setEsNuevo(Boolean esNuevo) {
		this.esNuevo = esNuevo;
	}
	
	@Transient
	public boolean getExisteFichero() {
		return existeFichero;
	}

	public void setExisteFichero(boolean existeFichero) {
		this.existeFichero = existeFichero;
	}

	
//	@Override
//	public String toString() {
//		return "Caso: (" + casoDocumento + "), tipo: " + tipoEstudio.getCodigo() + (nivelEstudioFormal != null ? ", nivel: " + nivelEstudioFormal.getCodigo() : "");
//	}

	//add siaper-ru
	public String toStringJson() {
	    StringBuilder sb = new StringBuilder();
	    sb.append("{\n");

	    sb.append("  \"id\": ").append(id).append(",\n");
	    sb.append("  \"version\": ").append(version != null ? "\"" + version + "\"" : null).append(",\n");
	    sb.append("  \"casoDocumento\": ").append(casoDocumento != null ? "\"" + casoDocumento.getId() + "\"" : null).append(",\n");
	    sb.append("  \"ensenianzaMedia\": ").append(ensenianzaMedia != null ? "\"" + ensenianzaMedia.getId() + "\"" : null).append(",\n");
	    sb.append("  \"entidadInteroperable\": ").append(entidadInteroperable != null ? "\"" + entidadInteroperable.getId() + "\"" : null).append(",\n");
	    sb.append("  \"fichero\": ").append(fichero != null ? "\"" + fichero.toString() + "\"" : null).append(",\n");
	    sb.append("  \"pais\": ").append(pais != null ? "\"" + pais.getDescripcion() + "\"" : null).append(",\n");
	    sb.append("  \"entidadOtorgadora\": ").append(entidadOtorgadora != null ? "\"" + entidadOtorgadora.getId() + "\"" : null).append(",\n");
	    sb.append("  \"titulo\": ").append(titulo != null ? "\"" + titulo.getId() + "\"" : null).append(",\n");
	    sb.append("  \"gradoAcademico\": ").append(gradoAcademico != null ? "\"" + gradoAcademico.getId() + "\"" : null).append(",\n");
	    sb.append("  \"tipoEstudio\": ").append(tipoEstudio != null ? "\"" + tipoEstudio.getId() + "\"" : null).append(",\n");
	    sb.append("  \"nivelEducacional\": ").append(nivelEducacional != null ? "\"" + nivelEducacional.getId() + "\"" : null).append(",\n");
	    sb.append("  \"nivelConvalidado\": ").append(nivelConvalidado != null ? "\"" + nivelConvalidado.getId() + "\"" : null).append(",\n");
	    sb.append("  \"formaFinanciamiento\": ").append(formaFinanciamiento != null ? "\"" + formaFinanciamiento.getId() + "\"" : null).append(",\n");
	    sb.append("  \"nivelDocente\": ").append(nivelDocente != null ? "\"" + nivelDocente.getId() + "\"" : null).append(",\n");
	    sb.append("  \"nivelEstudioFormal\": ").append(nivelEstudioFormal != null ? "\"" + nivelEstudioFormal.getId() + "\"" : null).append(",\n");
	    sb.append("  \"materiaConvalida\": ").append(materiaConvalida != null ? "\"" + materiaConvalida.getId() + "\"" : null).append(",\n");

	    sb.append("  \"interoperable\": ").append(interoperable).append(",\n");
	    sb.append("  \"aprobadoIntegro\": ").append(aprobadoIntegro).append(",\n");
	    sb.append("  \"numAnioEgreso\": ").append(numAnioEgreso).append(",\n");
	    sb.append("  \"establecimiento\": ").append(establecimiento != null ? "\"" + establecimiento + "\"" : null).append(",\n");
	    sb.append("  \"estudioInteroper\": ").append(estudioInteroper != null ? "\"" + estudioInteroper + "\"" : null).append(",\n");
	    sb.append("  \"numAnioUltimo\": ").append(numAnioUltimo).append(",\n");
	    sb.append("  \"mediaLaboral\": ").append(mediaLaboral).append(",\n");

	    sb.append("  \"descEstudio\": ").append(descEstudio != null ? "\"" + descEstudio + "\"" : null).append(",\n");
	    sb.append("  \"descEstudioOriginal\": ").append(descEstudioOriginal != null ? "\"" + descEstudioOriginal + "\"" : null).append(",\n");
	    sb.append("  \"fechaOtorgamiento\": ").append(fechaOtorgamiento != null ? "\"" + fechaOtorgamiento + "\"" : null).append(",\n");
	    sb.append("  \"descOtorgado\": ").append(descOtorgado != null ? "\"" + descOtorgado + "\"" : null).append(",\n");
	    sb.append("  \"tieneOtroTitulo\": ").append(tieneOtroTitulo).append(",\n");
	    sb.append("  \"otroTitulo\": ").append(otroTitulo != null ? "\"" + otroTitulo + "\"" : null).append(",\n");

	    sb.append("  \"mencion\": ").append(mencion != null ? "\"" + mencion + "\"" : null).append(",\n");
	    sb.append("  \"mencionOriginal\": ").append(mencionOriginal != null ? "\"" + mencionOriginal + "\"" : null).append(",\n");
	    sb.append("  \"numSemestres\": ").append(numSemestres).append(",\n");
	    sb.append("  \"numSemestresAprob\": ").append(numSemestresAprob).append(",\n");
	    sb.append("  \"numHoras\": ").append(numHoras).append(",\n");
	    sb.append("  \"numHorasPedag\": ").append(numHorasPedag).append(",\n");
	    sb.append("  \"tecnicoSuperior\": ").append(tecnicoSuperior).append(",\n");
	    sb.append("  \"tecnicoMedio\": ").append(tecnicoMedio).append(",\n");

	    sb.append("  \"fechaConvalidacion\": ").append(fechaConvalidacion != null ? "\"" + fechaConvalidacion + "\"" : null).append(",\n");
	    sb.append("  \"fechaDesde\": ").append(fechaDesde != null ? "\"" + fechaDesde + "\"" : null).append(",\n");
	    sb.append("  \"fechaHasta\": ").append(fechaHasta != null ? "\"" + fechaHasta + "\"" : null).append(",\n");

	    sb.append("  \"codUsuarioBloq\": ").append(codUsuarioBloq != null ? "\"" + codUsuarioBloq + "\"" : null).append(",\n");
	    sb.append("  \"codSiaper\": ").append(codSiaper).append(",\n");
	    sb.append("  \"errorIndicadoEstudio\": ").append(errorIndicadoEstudio).append(",\n");

	    sb.append("  \"esNuevo\": ").append(esNuevo).append(",\n");

	    sb.append("  \"tipoDocumento\": ").append(tipoDocumento != null ? "\"" + tipoDocumento.getId() + "\"" : null).append(",\n");
	    sb.append("  \"servicio\": ").append(servicio != null ? "\"" + servicio.getId() + "\"" : null).append(",\n");
	    sb.append("  \"glosaEducacional\": ").append(glosaEducacional != null ? "\"" + glosaEducacional + "\"" : null).append(",\n");

	    sb.append("  \"agregadoPor\": ").append(agregadoPor != null ? "\"" + agregadoPor + "\"" : null).append(",\n");

	    sb.append("  \"existeFichero\": ").append(existeFichero).append("\n");

	    sb.append("}");

	    return sb.toString();
	}
	
}
