package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ARTICULOS")
public class Articulo implements java.io.Serializable, Cloneable {

	private static final long serialVersionUID = -6276801428909271131L;

	private Long id;
	private Date version;
	private Ley ley;
	private String numArticulo;
	private String texto;
	private String codUsuarioBloq;
	private Set<RequisitoArticulo> requisitosArticulo = new HashSet<RequisitoArticulo>(0);
	private Set<ArticuloMateria> materiasArticulo = new HashSet<ArticuloMateria>(0);
	private Set<ArticuloServicio> articulosServicios = new HashSet<ArticuloServicio>(0);

	public Articulo() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ARTI_X_ARTI")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ARTI", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEYE_X_LEYE", nullable = false)
	public Ley getLey() {
		return this.ley;
	}

	public void setLey(Ley ley) {
		this.ley = ley;
	}

	@Column(name = "N_ARTICULO", length = 50)
	public String getNumArticulo() {
		return this.numArticulo;
	}

	public void setNumArticulo(String numArticulo) {
		this.numArticulo = numArticulo;
	}

	@Column(name = "T_TEXTO", length = 4000)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "articulo", cascade=CascadeType.ALL)
	public Set<RequisitoArticulo> getRequisitosArticulo() {
		return this.requisitosArticulo;
	}

	public void setRequisitosArticulo(Set<RequisitoArticulo> requisitoArticulos) {
		this.requisitosArticulo = requisitoArticulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "articulo", cascade=CascadeType.ALL)
	public Set<ArticuloMateria> getMateriasArticulo() {
		return this.materiasArticulo;
	}

	public void setMateriasArticulo(Set<ArticuloMateria> articuloMaterias) {
		this.materiasArticulo = articuloMaterias;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "articulo", cascade=CascadeType.ALL)
	public Set<ArticuloServicio> getArticulosServicios() {
		return articulosServicios;
	}

	public void setArticulosServicios(Set<ArticuloServicio> articulosServicios) {
		this.articulosServicios = articulosServicios;
	}

	public Articulo clone() {
		try {
			return (Articulo) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Articulo))
			return false;
		Articulo castOther = (Articulo) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Número: " + numArticulo + ", ley: " + ley.getNumLey();
	}
}
