package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

//Generated 09-feb-2012 17:49:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * ArtservMateria generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ARTSERV_MATERIAS")
public class ArtservMateria implements java.io.Serializable {

	private Long id;
	private Date version;
	private ArticuloServicio articuloServicio;
	private Materia materia;
	private String codUsuarioBloq;

	public ArtservMateria() {
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ARSM_X_ARSM")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ARSM", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ARSE_X_ARSE", nullable = false)
	public ArticuloServicio getArticuloServicio() {
		return this.articuloServicio;
	}

	public void setArticuloServicio(ArticuloServicio articuloServicio) {
		this.articuloServicio = articuloServicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATE_X_MATE", nullable = false)
	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtservMateria))
			return false;
		ArtservMateria castOther = (ArtservMateria) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

}
