package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 07-jul-2017 9:24:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * BenCargMasivo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_BEN_CARG_MASIVO")
public class BenCargMasivo implements Serializable {

	private static final long serialVersionUID = -4950301462649657737L;
	private Long id;
	private CasoMasivo casoMasivo;
	private BenMasivo benMasivo;
	private Date version;

	public BenCargMasivo() {
	}

	public BenCargMasivo(CasoMasivo casoMasivo, BenMasivo benMasivo) {
		this.casoMasivo = casoMasivo;
		this.benMasivo = benMasivo;
	}

	public BenCargMasivo(CasoMasivo casoMasivo, BenMasivo benMasivo, Date version) {
		this.casoMasivo = casoMasivo;
		this.benMasivo = benMasivo;
		this.version = version;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_BECA_X_BECA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_BECA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CASM_X_CASM", nullable = false)
	public CasoMasivo getCasoMasivo() {
		return this.casoMasivo;
	}

	public void setCasoMasivo(CasoMasivo casoMasivo) {
		this.casoMasivo = casoMasivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BEMA_X_BEMA", nullable = false)
	public BenMasivo getBenMasivo() {
		return this.benMasivo;
	}

	public void setBenMasivo(BenMasivo benMasivo) {
		this.benMasivo = benMasivo;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BenCargMasivo))
			return false;
		BenCargMasivo castOther = (BenCargMasivo) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

}