package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 07-jul-2017 9:24:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * BenMasivo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_BEN_MASIVO")
public class BenMasivo implements Serializable {

	private static final long serialVersionUID = -3560377373599288351L;
	private Long id;
	private String descripcion;
	private Date version;
	private Set<BenCargMasivo> benCargMasivo = new HashSet<BenCargMasivo>(0);

	public BenMasivo() {
	}

	public BenMasivo(String descripcion, Set<BenCargMasivo> benCargMasivo) {
		this.descripcion = descripcion;
		this.benCargMasivo = benCargMasivo;
	}

	public BenMasivo(String descripcion, Date version, Set<BenCargMasivo> benCargMasivo) {
		this.descripcion = descripcion;
		this.version = version;
		this.benCargMasivo = benCargMasivo;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_BEMA_X_BEMA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_BEMA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "T_DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benMasivo", cascade = CascadeType.ALL)
	public Set<BenCargMasivo> getBenCargMasivo() {
		return this.benCargMasivo;
	}

	public void setBenCargMasivo(Set<BenCargMasivo> benCargMasivo) {
		this.benCargMasivo = benCargMasivo;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BenMasivo))
			return false;
		BenMasivo castOther = (BenMasivo) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}


}