package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 06-mar-2012 11:28:58 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;
//import org.jboss.seam.annotations.In;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.SinoTipo;

//import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.repository.historical.CaminosTraService;


/**
 * CaminoTraGen generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_CAMINOS_TRA_GEN")
public class CaminoTraGen implements java.io.Serializable {
	
//	@In
//	private CaminosTraService caminosTraService;
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -2289092073926999917L;
	private Long id;
	private Date version;
	private Formulario formulario;
	private String codUsuarioBloq;	
	private Set<ReqartCaminoTraGen> reqartCaminoTraGenes = new HashSet<ReqartCaminoTraGen>(0);
	
	// Transient attributes
	private int orden;
	private List<String> alternativasReqArt;

	public CaminoTraGen() {
	}

	public CaminoTraGen(Formulario formulario) {
		this.formulario = formulario;
	}

	public CaminoTraGen(Formulario formulario, String codUsuarioBloq,
			Set<ReqartCaminoTraGen> reqartCaminoTraGenes) {
		this.formulario = formulario;
		this.codUsuarioBloq = codUsuarioBloq;
		this.reqartCaminoTraGenes = reqartCaminoTraGenes;
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_CTRG_X_CTRG")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_CTRG", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FORM_X_FORM", nullable = false)
	public Formulario getFormulario() {
		return this.formulario;
	}

	public void setFormulario(Formulario formulario) {
		this.formulario = formulario;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caminoTraGen")
	public Set<ReqartCaminoTraGen> getReqartCaminoTraGenes() {
		return this.reqartCaminoTraGenes;
	}

	public void setReqartCaminoTraGenes(
			Set<ReqartCaminoTraGen> reqartCaminoTraGenes) {
		this.reqartCaminoTraGenes = reqartCaminoTraGenes;
	}
	
	@Transient
	public List<String> getAlternativasReqArt() {
		return alternativasReqArt;
	}

	public void setAlternativasReqArt(List<String> alternativasReqArt) {
		this.alternativasReqArt = alternativasReqArt;
	}
	
	@Transient
	public int getOrden() {
		return orden;
	}
	
	public void setOrden(int orden) {
		this.orden = orden;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CaminoTraGen))
			return false;
		CaminoTraGen castOther = (CaminoTraGen) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
}
