package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 07-jul-2017 9:24:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * CargaMasiva generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_CARGA_MASIVA")
public class CargaMasiva implements Serializable, Entidad {
	
	private static final long serialVersionUID = -7202795278349796376L;
	private Long id;
	private PeticionMasiva peticionMasiva;
	private Date fechaCarga;
	private Date fechaRegistro;
	private String tipo;
	private boolean valido;
	private Date version;
	private String error;
	private Set<EstadoCargaMasiva> estadosCargaMasiva = new HashSet<EstadoCargaMasiva>(0);
	
	private String perfil;

	private String estado;
	
	private boolean seleccionado;
	
	private Set<ActoMasivo> actosMasivo = new HashSet<ActoMasivo>(0);
	
	public CargaMasiva() {
	}


	public CargaMasiva(PeticionMasiva peticionMasiva,
	                   Date fechaCarga,
	                   Date fechaRegistro,
	                   String tipo,
	                   boolean valido,
	                   Set<EstadoCargaMasiva> estCargMasivo,
	                   String perfil,
	                   String estado,
	                   boolean seleccionado) {

		this.peticionMasiva = peticionMasiva;
		this.fechaCarga = fechaCarga;
		this.fechaRegistro = fechaRegistro;
		this.tipo = tipo;
		this.valido = valido;
		this.estadosCargaMasiva = estCargMasivo;
		this.perfil = perfil;
		this.estado = estado;
		this.seleccionado = seleccionado;
	}

	public CargaMasiva(PeticionMasiva peticionMasiva,
	                   Date fechaCarga,
	                   Date fechaRegistro,
	                   String tipo,
	                   boolean valido,
	                   Date version,
	                   Set<EstadoCargaMasiva> estCargMasivo,
	                   String perfil,
	                   String estado,
	                   boolean seleccionado) {

		this.peticionMasiva = peticionMasiva;
		this.fechaCarga = fechaCarga;
		this.fechaRegistro = fechaRegistro;
		this.tipo = tipo;
		this.valido = valido;
		this.version = version;
		this.estadosCargaMasiva = estCargMasivo;
		this.perfil = perfil;
		this.estado = estado;
		this.seleccionado = seleccionado;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_CAMA_X_CAMA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_CAMA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PEMA_X_PEMA", nullable = false)
	public PeticionMasiva getPeticionMasiva() {
		return this.peticionMasiva;
	}

	public void setPeticionMasiva(PeticionMasiva peticionMasiva) {
		this.peticionMasiva = peticionMasiva;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FECHA_CARGA", nullable = false, length = 7)
	public Date getFechaCarga() {
		return this.fechaCarga;
	}

	public void setFechaCarga(Date fechaCarga) {
		this.fechaCarga = fechaCarga;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "T_TIPO", nullable = false, length = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	
	@Column(name = "L_VALIDO", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isValido() {
		return this.valido;
	}

	public void setValido(boolean valido) {
		this.valido = valido;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
    @Column(name = "X_ERROR", nullable = false, length = 4000)
    public String getError() {
        return this.error;
    }

    public void setError(String error) {
        this.error = error;
    }   

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargaMasiva", cascade = CascadeType.ALL)
	public Set<EstadoCargaMasiva> getEstadosCargaMasiva() {
		return this.estadosCargaMasiva;
	}

	public void setEstadosCargaMasiva(Set<EstadoCargaMasiva> estadosCargaMasiva) {
		this.estadosCargaMasiva = estadosCargaMasiva;
	}

	@Transient
	public String getPerfil() {
		return perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	@Transient
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Transient
	public boolean isSeleccionado() {
		return seleccionado;
	}

	public void setSeleccionado(boolean seleccionado) {
		this.seleccionado = seleccionado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargaMasiva", cascade = CascadeType.ALL)
	public Set<ActoMasivo> getActosMasivo() {
		return actosMasivo;
	}

	public void setActosMasivo(Set<ActoMasivo> actosMasivo) {
		this.actosMasivo = actosMasivo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CargaMasiva))
			return false;
		CargaMasiva castOther = (CargaMasiva) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

}