package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 28-oct-2011 13:37:46 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

//import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.documento.hist.GeneracionDocumentos;
import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;
//import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.util.hist.AsignacionItem;
//import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.util.hist.CargoItem;
//import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.util.hist.EncomendacionItem;
//import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.util.hist.EstudioItem;

/**
 * CasoDocumento generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_CASOS_DOCUMENTO")
//public class CasoDocumento implements java.io.Serializable, Comparable<CasoDocumento>, Cloneable {
public class CasoDocumento implements java.io.Serializable {

	private static final long serialVersionUID = -273028493863844046L;

	private Long id;
	private Date version;
	private DatoRaiz datoRaiz;
	private Pais pais;
	private Dotacion dotacion;
	private Documento documento;
	private Subcargo subcargo;
	private Formulario formulario;
	private String run;
	private String otraIdentificacion;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String sexo;
	private Date fechaNacimiento;
	private Boolean concurso;
	private Date fechaConcurso;
	private Date fechaVacante;
	private String estadoForm;
	private String codUsuarioBloq;
	private Long designacionSelect;
	private boolean completo;
	private Boolean certificable;
	private Boolean certificacionCorrecta;
	
	private String caliSelec;
	private Calidad calidadTraSeelct;
	private Long codigoFuncionarioSelect;
	private String runSelec;
	private String otraIdentificacionSelec;
	private String nombreFuncionarioSelec;
	private String numResolucionSelec;
	private Date fechaResolucionSelec;
	private Date fechaDesdeSelec;
	private Date fechaHastaSelec;
	private String descCalidadSelec;
	private Boolean msnssSelec;
	private Double horasSelec;
	
	private Long codPlantaCargoSiaperSelect;
	private Long codCargoSiaperSelect;
	private Long codGradoSiaperSelect;
	
	private Date fechaDesdeProrroga;
	private Date fechaHastaProrroga;
	
	private String resultadoEstudioManual;
	private String textoEstudioManual;
	
	private String codMotivoRepresEstudio;
	
	private String totalTramite;
	private Date fechaDesde;
	
	private Boolean datosPrincObtenidos;
	private Boolean datosPenaObtenidos;
	private Boolean datosInhabilidadObtenidos;
	private Boolean datosSitMilitarObtenidos;
	
	private boolean tomadoRazonAntesEstudio;
	
	private EstadisticasCaso estadisticasCaso;
	
	private Long funcionarioIdSIAPER;
	
	private Set<CeseMinisterio> actosVigentes = new HashSet<CeseMinisterio>(0);
	private Set<AntecedenteAdjunto> antecedentesAdjuntos = new HashSet<AntecedenteAdjunto>(0);
	private Set<AntecedenteEducacional> antecedentesEducacionales = new HashSet<AntecedenteEducacional>(0);
//	private Set<NotificacionCaso> notificaciones = new HashSet<NotificacionCaso>(0);
	private Set<DatoCaso> datosCaso = new HashSet<DatoCaso>(0);
	private Set<AnexoCaso> anexosCaso = new HashSet<AnexoCaso>(0);
	private Set<WarningCaso> warningsCaso = new HashSet<WarningCaso>(0);
	private Set<PanelSuplenciaReemplazo> panelSuplenciaReemplazos = new HashSet<PanelSuplenciaReemplazo>(0);
//	private Set<ErrorServicioWeb> erroresServicioWeb = new HashSet<ErrorServicioWeb>();
	private Set<ErrorFormulario> erroresFormulario = new HashSet<ErrorFormulario>();
	
	
	private Map<String, String> datosCasoMapa = new HashMap<String, String>();
	private String letra = "a";
//	private List<CargoItem> cargosConservaList = new ArrayList<CargoItem>();
//	private List<CargoItem> designacionesList = new ArrayList<CargoItem>();
	private String gradoDescPreview;
	private String nivelDescPreview;
	private String categoriaDescPreview;
	private Set<Warning> warningsCasoPreview = new HashSet<Warning>();
	private String identificacionPreview;
	private Long codRemuneracionSelect; // Prorroga Masiva
	
//	private List<GeneracionDocumentos.SiaPreview> subtituloItemAsignacionPreview;
	private String convenioPreview;
	
	private Fichero convenio;
	
	private Boolean totalTramiteModRec;
	
	private String comentarioModRec;
	
	private Date fechaDesdeModRec;
	
//	private Set<CargaFormulario> tiemposCargaFormulario = new HashSet<CargaFormulario>(0);

//	private List<AsignacionItem> asignacion = new ArrayList<AsignacionItem>();
	
//	private EstudioItem estudioPreview = new EstudioItem();
	
//	private EncomendacionItem encomendacionPreview = new EncomendacionItem();
	
//	private AsignacionItem asignacionPreview = new AsignacionItem();
	
	private Integer orden;
	
	/**
	 * Atributo Transient
	 * Indica si el fichero está en el CM
	 */
	private boolean existeFicheroConvenio;
	
	/**
	 * Atributo Transient
	 * Indica si los ficheros estám en el CM
	 */
	private boolean existenFicherosAdjuntos;
	
	/**
	 * Atributo Transient
	 * Indica si los ficheros están en el CM
	 */
	private boolean existenFicherosAntAdjuntos;

	public CasoDocumento() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_CADO_X_CADO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_CADO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "DARA_X_DARA")
	public DatoRaiz getDatoRaiz() {
		return this.datoRaiz;
	}

	public void setDatoRaiz(DatoRaiz datoRaiz) {
		this.datoRaiz = datoRaiz;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAIS_X_PAIS")
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RPLS_X_RPLS")
	public Dotacion getDotacion() {
		return this.dotacion;
	}

	public void setDotacion(Dotacion dotacion) {
		this.dotacion = dotacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCU_X_DOCU", nullable = false)
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBC_X_SUBC")
	public Subcargo getSubcargo() {
		return subcargo;
	}

	public void setSubcargo(Subcargo subcargo) {
		this.subcargo = subcargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FORM_X_FORM")
	public Formulario getFormulario() {
		return this.formulario;
	}

	public void setFormulario(Formulario formulario) {
		this.formulario = formulario;
	}

	@Column(name = "T_RUN", length = 10)
	public String getRun() {
		return this.run;
	}

	public void setRun(String run) {
		this.run = run;
	}

	@Column(name = "T_OTRA_IDENTIFICACION", length = 15)
	public String getOtraIdentificacion() {
		return this.otraIdentificacion;
	}

	public void setOtraIdentificacion(String otraIdentificacion) {
		this.otraIdentificacion = otraIdentificacion;
	}

	@Column(name = "T_NOMBRES", length = 150)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "T_APELLIDO_PATERNO", length = 150)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "T_APELLIDO_MATERNO", length = 150)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "V_SEXO", length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_NACIMIENTO", length = 7)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "L_CONCURSO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getConcurso() {
		return this.concurso;
	}

	public void setConcurso(Boolean concurso) {
		this.concurso = concurso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_CONCURSO", length = 7)
	public Date getFechaConcurso() {
		return this.fechaConcurso;
	}

	public void setFechaConcurso(Date fechaConcurso) {
		this.fechaConcurso = fechaConcurso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VACANTE", length = 7)
	public Date getFechaVacante() {
		return this.fechaVacante;
	}

	public void setFechaVacante(Date fechaVacante) {
		this.fechaVacante = fechaVacante;
	}

	@Column(name = "V_ESTADO_FORM", length = 2)
	public String getEstadoForm() {
		return this.estadoForm;
	}

	public void setEstadoForm(String estadoForm) {
		this.estadoForm = estadoForm;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@Column(name = "C_DESIGNACION_SELEC", precision = 12, scale = 0, nullable = true)
	public Long getDesignacionSelect() {
		return designacionSelect;
	}
	
	public void setDesignacionSelect(Long designacionSelect) {
		this.designacionSelect = designacionSelect;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoDocumento", cascade = CascadeType.ALL)
	public Set<CeseMinisterio> getActosVigentes() {
		if (this.actosVigentes ==  null) {
			return new HashSet<CeseMinisterio>();
		}
		return actosVigentes;
	}

	public void setActosVigentes(Set<CeseMinisterio> actosVigentes) {
		this.actosVigentes = actosVigentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoDocumento", cascade = CascadeType.ALL)
	public Set<AntecedenteAdjunto> getAntecedentesAdjuntos() {
		if (this.antecedentesAdjuntos ==  null) {
			return new HashSet<AntecedenteAdjunto>();
		}
		return antecedentesAdjuntos;
	}

	public void setAntecedentesAdjuntos(Set<AntecedenteAdjunto> antecedentesAdjuntos) {
		this.antecedentesAdjuntos = antecedentesAdjuntos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoDocumento", cascade = CascadeType.ALL)
	public Set<AntecedenteEducacional> getAntecedentesEducacionales() {
		if (this.antecedentesEducacionales ==  null) {
			return new HashSet<AntecedenteEducacional>();
		}
		return this.antecedentesEducacionales;
	}

	public void setAntecedentesEducacionales(Set<AntecedenteEducacional> antecedenteEducacionales) {
		this.antecedentesEducacionales = antecedenteEducacionales;
	}

/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoDocumento", cascade = CascadeType.ALL)
	public Set<NotificacionCaso> getNotificaciones() {
		return this.notificaciones;
	}

	public void setNotificaciones(Set<NotificacionCaso> notificacionCasos) {
		this.notificaciones = notificacionCasos;
	}
*/
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoDocumento", cascade = CascadeType.ALL)
	public Set<DatoCaso> getDatosCaso() {
		return this.datosCaso;
	}

	public void setDatosCaso(Set<DatoCaso> datoCasos) {
		this.datosCaso = datoCasos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoDocumento", cascade = CascadeType.ALL)
	public Set<AnexoCaso> getAnexosCaso() {
		return this.anexosCaso;
	}

	public void setAnexosCaso(Set<AnexoCaso> anexoCasos) {
		this.anexosCaso = anexoCasos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoDocumento", cascade = CascadeType.ALL)
	public Set<WarningCaso> getWarningsCaso() {
		return this.warningsCaso;
	}

	public void setWarningsCaso(Set<WarningCaso> warningCasos) {
		this.warningsCaso = warningCasos;
	}

	@Column(name = "S_CALI_SELEC", length = 4)
	public String getCaliSelec() {
		return caliSelec;
	}

	public void setCaliSelec(String caliSelec) {
		this.caliSelec = caliSelec;
	}

	@Column(name = "L_MSNSS_SELEC", length = 1)	
	public Boolean getMsnssSelec() {
		return msnssSelec;
	}

	public void setMsnssSelec(Boolean msnssSelec) {
		this.msnssSelec = msnssSelec;
	}

	@Column(name = "N_HORAS_SELEC")	
	public Double getHorasSelec() {
		return horasSelec;
	}

	public void setHorasSelec(Double horasSelec) {
		this.horasSelec = horasSelec;
	}

	@Column(name = "T_RUN_SELEC", length = 42)
	public String getRunSelec() {
		return runSelec;
	}

	public void setRunSelec(String runSelec) {
		this.runSelec = runSelec;
	}

	@Column(name = "T_OTRA_IDENTIFICACION_SELEC", length = 50)
	public String getOtraIdentificacionSelec() {
		return otraIdentificacionSelec;
	}

	public void setOtraIdentificacionSelec(String otraIdentificacionSelec) {
		this.otraIdentificacionSelec = otraIdentificacionSelec;
	}
	
	@Column(name = "T_NOMBRE_FUNCIONARIO_SELEC", length = 122)
	public String getNombreFuncionarioSelec() {
		return nombreFuncionarioSelec;
	}

	public void setNombreFuncionarioSelec(String nombreFuncionarioSelec) {
		this.nombreFuncionarioSelec = nombreFuncionarioSelec;
	}

	@Column(name = "T_NUM_RESOLUCION_SELEC", length = 255)
	public String getNumResolucionSelec() {
		return numResolucionSelec;
	}

	public void setNumResolucionSelec(String numResolucionSelec) {
		this.numResolucionSelec = numResolucionSelec;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_RESOLUCION_SELEC", length = 7)
	public Date getFechaResolucionSelec() {
		return fechaResolucionSelec;
	}

	public void setFechaResolucionSelec(Date fechaResolucionSelec) {
		this.fechaResolucionSelec = fechaResolucionSelec;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_DESDE_SELEC", length = 7)
	public Date getFechaDesdeSelec() {
		return fechaDesdeSelec;
	}

	public void setFechaDesdeSelec(Date fechaDesdeSelec) {
		this.fechaDesdeSelec = fechaDesdeSelec;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_HASTA_SELEC", length = 7)
	public Date getFechaHastaSelec() {
		return fechaHastaSelec;
	}

	public void setFechaHastaSelec(Date fechaHastaSelec) {
		this.fechaHastaSelec = fechaHastaSelec;
	}
	
	@Column(name = "V_TR_MANUAL", length = 1)
	public String getResultadoEstudioManual() {
		return resultadoEstudioManual;
	}

	public void setResultadoEstudioManual(String resultadoEstudioManual) {
		this.resultadoEstudioManual = resultadoEstudioManual;
	}

	@Column(name = "T_TR_MANUAL_WARN", length = 255)
	public String getTextoEstudioManual() {
		return textoEstudioManual;
	}

	public void setTextoEstudioManual(String textoEstudioManual) {
		this.textoEstudioManual = textoEstudioManual;
	}

	@Column(name = "C_MOTIVO_REP_ESTUDIO", length = 1)
	public String getCodMotivoRepresEstudio() {
		return codMotivoRepresEstudio;
	}

	public void setCodMotivoRepresEstudio(String codMotivoRepresEstudio) {
		this.codMotivoRepresEstudio = codMotivoRepresEstudio;
	}

	@Column(name = "L_DAT_PRINC_OBTENIDOS")
	public Boolean getDatosPrincObtenidos() {
		return datosPrincObtenidos;
	}

	public void setDatosPrincObtenidos(Boolean datosPrincObtenidos) {
		this.datosPrincObtenidos = datosPrincObtenidos;
	}

	@Column(name = "L_DAT_PENA_OBTENIDOS")
	public Boolean getDatosPenaObtenidos() {
		return datosPenaObtenidos;
	}

	public void setDatosPenaObtenidos(Boolean datosPenaObtenidos) {
		this.datosPenaObtenidos = datosPenaObtenidos;
	}
	
	@Column(name = "L_DAT_INH_OBTENIDOS")
	public Boolean getDatosInhabilidadObtenidos() {
		return datosInhabilidadObtenidos;
	}

	public void setDatosInhabilidadObtenidos(Boolean datosInhabilidadObtenidos) {
		this.datosInhabilidadObtenidos = datosInhabilidadObtenidos;
	}

	@Column(name = "L_DAT_SITMILITAR_OBTENIDOS")
	public Boolean getDatosSitMilitarObtenidos() {
		return datosSitMilitarObtenidos;
	}

	public void setDatosSitMilitarObtenidos(Boolean datosSitMilitarObtenidos) {
		this.datosSitMilitarObtenidos = datosSitMilitarObtenidos;
	}

	@Column(name = "L_TOMA_RAZON_ANTES_ESTUDIO", nullable = false)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isTomadoRazonAntesEstudio() {
		return tomadoRazonAntesEstudio;
	}

	public void setTomadoRazonAntesEstudio(boolean tomadoRazonAntesEstudio) {
		this.tomadoRazonAntesEstudio = tomadoRazonAntesEstudio;
	}

	@OneToOne(mappedBy = "caso")
	public EstadisticasCaso getEstadisticasCaso() {
		return estadisticasCaso;
	}

	public void setEstadisticasCaso(EstadisticasCaso estadisticasCaso) {
		this.estadisticasCaso = estadisticasCaso;
	}

	@Transient
	public String getApellidos() {
		String ret;
		if(this.apellidoPaterno != null && !"".equals(this.apellidoPaterno)){
			ret = this.apellidoPaterno;
		}else {
			ret = "";
		}
		if(this.apellidoMaterno != null && !"".equals(this.apellidoMaterno)){
			ret += " " + this.apellidoMaterno;
		}else {
			ret += "";
		}
		return ret;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CasoDocumento))
			return false;
		CasoDocumento castOther = (CasoDocumento) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	@Transient
	public Map<String, String> getDatosCasoMapa() {
		return datosCasoMapa;
	}

	public void setDatosCasoMapa(Map<String, String> datosCasoMapa) {
		this.datosCasoMapa = datosCasoMapa;
	}

	@Column(name = "L_COMPLETO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean getCompleto() {
		return completo;
	}

	public void setCompleto(boolean completo) {
		this.completo = completo;
	}
	
	@Column(name = "L_CERTIFICABLE", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getCertificable() {
		return certificable;
	}

	public void setCertificable(Boolean certificable) {
		this.certificable = certificable;
	}

	@Column(name = "L_CERTI_CORRECTA", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getCertificacionCorrecta() {
		return certificacionCorrecta;
	}

	public void setCertificacionCorrecta(Boolean certificacionCorrecta) {
		this.certificacionCorrecta = certificacionCorrecta;
	}

	@Column(name = "S_PLCA_SELEC", precision = 12, scale = 0)
	public Long getCodPlantaCargoSiaperSelect() {
		return codPlantaCargoSiaperSelect;
	}

	public void setCodPlantaCargoSiaperSelect(Long codPlantaCargoSiaperSelect) {
		this.codPlantaCargoSiaperSelect = codPlantaCargoSiaperSelect;
	}

	@Column(name = "S_CARG_SELEC", precision = 12, scale = 0)
	public Long getCodCargoSiaperSelect() {
		return codCargoSiaperSelect;
	}

	public void setCodCargoSiaperSelect(Long codCargoSiaperSelect) {
		this.codCargoSiaperSelect = codCargoSiaperSelect;
	}

	@Column(name = "S_GRAD_SELEC", precision = 12, scale = 0)
	public Long getCodGradoSiaperSelect() {
		return codGradoSiaperSelect;
	}

	public void setCodGradoSiaperSelect(Long codGradoSiaperSelect) {
		this.codGradoSiaperSelect = codGradoSiaperSelect;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_DESDE_PRORROGA", length = 7)
	public Date getFechaDesdeProrroga() {
		return fechaDesdeProrroga;
	}

	public void setFechaDesdeProrroga(Date fechaDesdeProrroga) {
		this.fechaDesdeProrroga = fechaDesdeProrroga;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_HASTA_PRORROGA", length = 7)
	public Date getFechaHastaProrroga() {
		return fechaHastaProrroga;
	}

	public void setFechaHastaProrroga(Date fechaHastaProrroga) {
		this.fechaHastaProrroga = fechaHastaProrroga;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoDocumento", cascade = CascadeType.ALL)
	public Set<PanelSuplenciaReemplazo> getPanelSuplenciaReemplazos() {
		return panelSuplenciaReemplazos;
	}

	public void setPanelSuplenciaReemplazos(
			Set<PanelSuplenciaReemplazo> panelSuplenciaReemplazos) {
		this.panelSuplenciaReemplazos = panelSuplenciaReemplazos;
	}

	public int compareTo(CasoDocumento caso) {
		int ord = 0;
		
		try {
			ord  = (int) (this.orden - caso.orden);
		}catch(Exception e){
			ord = 0;
		}
		
		return ord;
	}

	@Transient
	public String getDescCalidadSelec() {
		return descCalidadSelec;
	}

	public void setDescCalidadSelec(String descCalidadSelec) {
		this.descCalidadSelec = descCalidadSelec;
	}
	
	@Transient
	public Calidad getCalidadTraSeelct() {
		return calidadTraSeelct;
	}

	public void setCalidadTraSeelct(Calidad calidadTraSeelct) {
		this.calidadTraSeelct = calidadTraSeelct;
	}

	@Column(name = "S_FUNCIONARIO_SELEC", length = 12, scale = 0)
	public Long getCodigoFuncionarioSelect() {
		return codigoFuncionarioSelect;
	}

	public void setCodigoFuncionarioSelect(Long codigoFuncionarioSelect) {
		this.codigoFuncionarioSelect = codigoFuncionarioSelect;
	}
	
	@Column(name = "S_FUNCIONARIOID", length = 12, scale = 0)
	public Long getFuncionarioIdSIAPER() {
		return funcionarioIdSIAPER;
	}

	public void setFuncionarioIdSIAPER(Long funcionarioIdSIAPER) {
		this.funcionarioIdSIAPER = funcionarioIdSIAPER;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoDocumento", cascade = CascadeType.ALL)
	public Set<ErrorServicioWeb> getErroresServicioWeb() {
		return erroresServicioWeb;
	}

	public void setErroresServicioWeb(Set<ErrorServicioWeb> erroresServicioWeb) {
		this.erroresServicioWeb = erroresServicioWeb;
	}
*/
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoDocumento", cascade = CascadeType.ALL)
	public Set<ErrorFormulario> getErroresFormulario() {
		return erroresFormulario;
	}

	public void setErroresFormulario(Set<ErrorFormulario> erroresFormulario) {
		this.erroresFormulario = erroresFormulario;
	}

	@Transient
	public String getLetra() {
		return letra;
	}

	public void setLetra(String letra) {
		this.letra = letra;
	}

//	@Transient
//	public List<CargoItem> getCargosConservaList() {
//		return cargosConservaList;
//	}

//	public void setCargosConservaList(List<CargoItem> cargosConservaList) {
//		this.cargosConservaList = cargosConservaList;
//	}
	
//	@Transient
//	public List<CargoItem> getDesignacionesList() {
//		return designacionesList;
//	}

//	public void setDesignacionesList(List<CargoItem> designacionesList) {
//		this.designacionesList = designacionesList;
//	}

	
	public CasoDocumento clone() {
		try {
			return (CasoDocumento) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}

	@Transient
	public String getTotalTramite() {
		return totalTramite;
	}

	public void setTotalTramite(String totalTramite) {
		this.totalTramite = totalTramite;
	}

	@Transient
	public Date getFechaDesde() {
		return fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Transient
	public String getGradoDescPreview() {
		return gradoDescPreview;
	}

	public void setGradoDescPreview(String gradoDescPreview) {
		this.gradoDescPreview = gradoDescPreview;
	}

	@Transient
	public String getNivelDescPreview() {
		return nivelDescPreview;
	}

	public void setNivelDescPreview(String nivelDescPreview) {
		this.nivelDescPreview = nivelDescPreview;
	}

	@Transient
	public String getCategoriaDescPreview() {
		return categoriaDescPreview;
	}

	public void setCategoriaDescPreview(String categoriaDescPreview) {
		this.categoriaDescPreview = categoriaDescPreview;
	}

	@Transient
	public Set<Warning> getWarningsCasoPreview() {
		return warningsCasoPreview;
	}

	public void setWarningsCasoPreview(Set<Warning> warningsCasoPreview) {
		this.warningsCasoPreview = warningsCasoPreview;
	}

	@Transient
	public String getIdentificacionPreview() {
		return identificacionPreview;
	}
	
	public void setIdentificacionPreview(String identificacionPreview) {
		this.identificacionPreview = identificacionPreview;
	}
	
	@Column(name = "S_REMU_SELEC", length = 12, scale = 0)
	public Long getCodRemuneracionSelect() {
		return codRemuneracionSelect;
	}

	public void setCodRemuneracionSelect(Long codRemuneracionSelect) {
		this.codRemuneracionSelect = codRemuneracionSelect;
	}
	
//	@Transient
//	public List<GeneracionDocumentos.SiaPreview> getSubtituloItemAsignacionPreview() {
//		return subtituloItemAsignacionPreview;
//	}

//	public void setSubtituloItemAsignacionPreview(
//			List<GeneracionDocumentos.SiaPreview> subtituloItemAsignacionPreview) {
//		this.subtituloItemAsignacionPreview = subtituloItemAsignacionPreview;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FICH_X_FICH_CONVENIO", nullable = true)
	public Fichero getConvenio() {
		return convenio;
	}

	public void setConvenio(Fichero convenio) {
		this.convenio = convenio;
	}

	@Transient
	public String getConvenioPreview() {
		return convenioPreview;
	}

	public void setConvenioPreview(String convenioPreview) {
		this.convenioPreview = convenioPreview;
	}

	/**
	 * @return the totalTramiteModRec
	 */
	@Column(name = "L_MOD_TOTAL_TRAMITE", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getTotalTramiteModRec() {
		return totalTramiteModRec;
	}

	/**
	 * @param totalTramiteModRec the totalTramiteModRec to set
	 */
	public void setTotalTramiteModRec(Boolean totalTramiteModRec) {
		this.totalTramiteModRec = totalTramiteModRec;
	}

	/**
	 * @return the comentarioModRec
	 */
	@Column(name = "T_MOD_COMENTARIO", length = 4000)
	public String getComentarioModRec() {
		return comentarioModRec;
	}

	/**
	 * @param comentarioModRec the comentarioModRec to set
	 */
	public void setComentarioModRec(String comentarioModRec) {
		this.comentarioModRec = comentarioModRec;
	}

	/**
	 * @return the fechaDesdeModRec
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_MOD_DESDE", length = 7)
	public Date getFechaDesdeModRec() {
		return fechaDesdeModRec;
	}

	/**
	 * @param fechaDesdeModRec the fechaDesdeModRec to set
	 */
	public void setFechaDesdeModRec(Date fechaDesdeModRec) {
		this.fechaDesdeModRec = fechaDesdeModRec;
	}

	/**
	 * @return the tiemposCargaFormulario
	 */
	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formulario")
	public Set<CargaFormulario> getTiemposCargaFormulario() {
		return tiemposCargaFormulario;
	}

	/**
	 * @param tiemposCargaFormulario the tiemposCargaFormulario to set
	 */
	/*
	public void setTiemposCargaFormulario(Set<CargaFormulario> tiemposCargaFormulario) {
		this.tiemposCargaFormulario = tiemposCargaFormulario;
	}
	*/

//	@Transient
//	public List<AsignacionItem> getAsignacion() {
//		return asignacion;
//	}

//	public void setAsignacion(List<AsignacionItem> asignacion) {
//		this.asignacion = asignacion;
//	}

	@Transient
	public boolean getExisteFicheroConvenio() {
		return existeFicheroConvenio;
	}

	public void setExisteFicheroConvenio(boolean existeFicheroConvenio) {
		this.existeFicheroConvenio = existeFicheroConvenio;
	}

	@Transient
	public boolean getExistenFicherosAdjuntos() {
		return existenFicherosAdjuntos;
	}

	public void setExistenFicherosAdjuntos(boolean existenFicherosAdjuntos) {
		this.existenFicherosAdjuntos = existenFicherosAdjuntos;
	}

	@Transient
	public boolean getExistenFicherosAntAdjuntos() {
		return existenFicherosAntAdjuntos;
	}

	public void setExistenFicherosAntAdjuntos(boolean existenFicherosAntAdjuntos) {
		this.existenFicherosAntAdjuntos = existenFicherosAntAdjuntos;
	}
	
//	@Transient
//	public EstudioItem getEstudioPreview() {
//		return estudioPreview;
//	}

//	public void setEstudioPreview(EstudioItem estudioPreview) {
//		this.estudioPreview = estudioPreview;
//	}
	
//	@Transient
//	public EncomendacionItem getEncomendacionPreview() {
//		return encomendacionPreview;
//	}

//	public void setEncomendacionPreview(EncomendacionItem encomendacionPreview) {
//		this.encomendacionPreview = encomendacionPreview;
//	}
	
//	@Transient
//	public AsignacionItem getAsignacionPreview() {
//		return asignacionPreview;
//	}

//	public void setAsignacionPreview(AsignacionItem asignacionPreview) {
//		this.asignacionPreview = asignacionPreview;
//	}
	
	@Column(name = "N_ORDEN")
	public Integer getOrden() {
		return orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	//
//	public String toString() {
//		StringBuilder datos = new StringBuilder();
//		datos.append("Run: ");
//		datos.append(run);
//		datos.append(" - ");
//		datos.append(getApellidos());
//		datos.append(", ");
//		datos.append(getNombres());
//		datos.append(" - Documento: ");
//		datos.append(getDocumento().getNumDocuFirmado() == null ? getDocumento().getNumDocuBorrador() : getDocumento().getNumDocuFirmado());
//		datos.append(")");
//		return datos.toString();
//	}

	//add siaper-ru
	public String toStringJson() {
	    StringBuilder sb = new StringBuilder();
	    sb.append("{\n");

	    sb.append("  \"id\": ").append(id).append(",\n");
	    sb.append("  \"version\": ").append(version != null ? "\"" + version + "\"" : null).append(",\n");
	    sb.append("  \"datoRaiz\": ").append(datoRaiz != null ? "\"" + datoRaiz.getId() + "\"" : null).append(",\n");
	    sb.append("  \"pais\": ").append(pais != null ? "\"" + pais.getDescripcion() + "\"" : null).append(",\n");
	    sb.append("  \"dotacion\": ").append(dotacion != null ? "\"" + dotacion.getId() + "\"" : null).append(",\n");
	    sb.append("  \"documento\": ").append(documento != null ? "\"" + documento.getId() + "\"" : null).append(",\n");
	    sb.append("  \"subcargo\": ").append(subcargo != null ? "\"" + subcargo.getId() + "\"" : null).append(",\n");
	    sb.append("  \"formulario\": ").append(formulario != null ? "\"" + formulario.getId() + "\"" : null).append(",\n");

	    sb.append("  \"run\": ").append(run != null ? "\"" + run + "\"" : null).append(",\n");
	    sb.append("  \"otraIdentificacion\": ").append(otraIdentificacion != null ? "\"" + otraIdentificacion + "\"" : null).append(",\n");
	    sb.append("  \"nombres\": ").append(nombres != null ? "\"" + nombres + "\"" : null).append(",\n");
	    sb.append("  \"apellidoPaterno\": ").append(apellidoPaterno != null ? "\"" + apellidoPaterno + "\"" : null).append(",\n");
	    sb.append("  \"apellidoMaterno\": ").append(apellidoMaterno != null ? "\"" + apellidoMaterno + "\"" : null).append(",\n");
	    sb.append("  \"sexo\": ").append(sexo != null ? "\"" + sexo + "\"" : null).append(",\n");
	    sb.append("  \"fechaNacimiento\": ").append(fechaNacimiento != null ? "\"" + fechaNacimiento + "\"" : null).append(",\n");

	    sb.append("  \"concurso\": ").append(concurso).append(",\n");
	    sb.append("  \"fechaConcurso\": ").append(fechaConcurso != null ? "\"" + fechaConcurso + "\"" : null).append(",\n");
	    sb.append("  \"fechaVacante\": ").append(fechaVacante != null ? "\"" + fechaVacante + "\"" : null).append(",\n");
	    sb.append("  \"estadoForm\": ").append(estadoForm != null ? "\"" + estadoForm + "\"" : null).append(",\n");
	    sb.append("  \"codUsuarioBloq\": ").append(codUsuarioBloq != null ? "\"" + codUsuarioBloq + "\"" : null).append(",\n");
	    sb.append("  \"designacionSelect\": ").append(designacionSelect).append(",\n");

	    sb.append("  \"completo\": ").append(completo).append(",\n");
	    sb.append("  \"certificable\": ").append(certificable).append(",\n");
	    sb.append("  \"certificacionCorrecta\": ").append(certificacionCorrecta).append(",\n");

	    sb.append("  \"caliSelec\": ").append(caliSelec != null ? "\"" + caliSelec + "\"" : null).append(",\n");
	    sb.append("  \"calidadTraSeelct\": ").append(calidadTraSeelct != null ? "\"" + calidadTraSeelct.getId() + "\"" : null).append(",\n");
	    sb.append("  \"codigoFuncionarioSelect\": ").append(codigoFuncionarioSelect).append(",\n");
	    sb.append("  \"runSelec\": ").append(runSelec != null ? "\"" + runSelec + "\"" : null).append(",\n");
	    sb.append("  \"otraIdentificacionSelec\": ").append(otraIdentificacionSelec != null ? "\"" + otraIdentificacionSelec + "\"" : null).append(",\n");
	    sb.append("  \"nombreFuncionarioSelec\": ").append(nombreFuncionarioSelec != null ? "\"" + nombreFuncionarioSelec + "\"" : null).append(",\n");
	    sb.append("  \"numResolucionSelec\": ").append(numResolucionSelec != null ? "\"" + numResolucionSelec + "\"" : null).append(",\n");
	    sb.append("  \"fechaResolucionSelec\": ").append(fechaResolucionSelec != null ? "\"" + fechaResolucionSelec + "\"" : null).append(",\n");
	    sb.append("  \"fechaDesdeSelec\": ").append(fechaDesdeSelec != null ? "\"" + fechaDesdeSelec + "\"" : null).append(",\n");
	    sb.append("  \"fechaHastaSelec\": ").append(fechaHastaSelec != null ? "\"" + fechaHastaSelec + "\"" : null).append(",\n");
	    sb.append("  \"descCalidadSelec\": ").append(descCalidadSelec != null ? "\"" + descCalidadSelec + "\"" : null).append(",\n");
	    sb.append("  \"msnssSelec\": ").append(msnssSelec).append(",\n");
	    sb.append("  \"horasSelec\": ").append(horasSelec).append(",\n");

	    sb.append("  \"codPlantaCargoSiaperSelect\": ").append(codPlantaCargoSiaperSelect).append(",\n");
	    sb.append("  \"codCargoSiaperSelect\": ").append(codCargoSiaperSelect).append(",\n");
	    sb.append("  \"codGradoSiaperSelect\": ").append(codGradoSiaperSelect).append(",\n");

	    sb.append("  \"fechaDesdeProrroga\": ").append(fechaDesdeProrroga != null ? "\"" + fechaDesdeProrroga + "\"" : null).append(",\n");
	    sb.append("  \"fechaHastaProrroga\": ").append(fechaHastaProrroga != null ? "\"" + fechaHastaProrroga + "\"" : null).append(",\n");

	    sb.append("  \"resultadoEstudioManual\": ").append(resultadoEstudioManual != null ? "\"" + resultadoEstudioManual + "\"" : null).append(",\n");
	    sb.append("  \"textoEstudioManual\": ").append(textoEstudioManual != null ? "\"" + textoEstudioManual + "\"" : null).append(",\n");
	    sb.append("  \"codMotivoRepresEstudio\": ").append(codMotivoRepresEstudio != null ? "\"" + codMotivoRepresEstudio + "\"" : null).append(",\n");

	    sb.append("  \"totalTramite\": ").append(totalTramite != null ? "\"" + totalTramite + "\"" : null).append(",\n");
	    sb.append("  \"fechaDesde\": ").append(fechaDesde != null ? "\"" + fechaDesde + "\"" : null).append(",\n");

	    sb.append("  \"datosPrincObtenidos\": ").append(datosPrincObtenidos).append(",\n");
	    sb.append("  \"datosPenaObtenidos\": ").append(datosPenaObtenidos).append(",\n");
	    sb.append("  \"datosInhabilidadObtenidos\": ").append(datosInhabilidadObtenidos).append(",\n");
	    sb.append("  \"datosSitMilitarObtenidos\": ").append(datosSitMilitarObtenidos).append(",\n");

	    sb.append("  \"tomadoRazonAntesEstudio\": ").append(tomadoRazonAntesEstudio).append(",\n");

	    sb.append("  \"estadisticasCaso\": ").append(estadisticasCaso != null ? "\"" + estadisticasCaso.getId() + "\"" : null).append(",\n");
	    sb.append("  \"funcionarioIdSIAPER\": ").append(funcionarioIdSIAPER).append(",\n");

	    sb.append("  \"actosVigentes\": ").append(actosVigentes != null ? actosVigentes.size() : 0).append(",\n");
	    sb.append("  \"antecedentesAdjuntos\": ").append(antecedentesAdjuntos != null ? antecedentesAdjuntos.size() : 0).append(",\n");
	    sb.append("  \"antecedentesEducacionales\": ").append(antecedentesEducacionales != null ? antecedentesEducacionales.toString() : 0).append(",\n");
	    // sb.append("  \"notificaciones\": ").append(notificaciones != null ? notificaciones.size() : 0).append(",\n");
	    sb.append("  \"datosCaso\": ").append(datosCaso != null ? datosCaso.size() : 0).append(",\n");
	    sb.append("  \"anexosCaso\": ").append(anexosCaso != null ? anexosCaso.size() : 0).append(",\n");
	    sb.append("  \"warningsCaso\": ").append(warningsCaso != null ? warningsCaso.size() : 0).append(",\n");
	    sb.append("  \"panelSuplenciaReemplazos\": ").append(panelSuplenciaReemplazos != null ? panelSuplenciaReemplazos.size() : 0).append(",\n");
	    // sb.append("  \"erroresServicioWeb\": ").append(erroresServicioWeb != null ? erroresServicioWeb.size() : 0).append(",\n");
	    sb.append("  \"erroresFormulario\": ").append(erroresFormulario != null ? erroresFormulario.size() : 0).append(",\n");

	    sb.append("  \"datosCasoMapa\": ").append(datosCasoMapa != null ? datosCasoMapa.size() : 0).append(",\n");
	    sb.append("  \"letra\": ").append(letra != null ? "\"" + letra + "\"" : null).append(",\n");
//	    sb.append("  \"cargosConservaList\": ").append(cargosConservaList != null ? cargosConservaList.size() : 0).append(",\n");
//	    sb.append("  \"designacionesList\": ").append(designacionesList != null ? designacionesList.size() : 0).append(",\n");

	    sb.append("  \"gradoDescPreview\": ").append(gradoDescPreview != null ? "\"" + gradoDescPreview + "\"" : null).append(",\n");
	    sb.append("  \"nivelDescPreview\": ").append(nivelDescPreview != null ? "\"" + nivelDescPreview + "\"" : null).append(",\n");
	    sb.append("  \"categoriaDescPreview\": ").append(categoriaDescPreview != null ? "\"" + categoriaDescPreview + "\"" : null).append(",\n");

	    sb.append("  \"warningsCasoPreview\": ").append(warningsCasoPreview != null ? warningsCasoPreview.size() : 0).append(",\n");
	    sb.append("  \"identificacionPreview\": ").append(identificacionPreview != null ? "\"" + identificacionPreview + "\"" : null).append(",\n");
	    sb.append("  \"codRemuneracionSelect\": ").append(codRemuneracionSelect).append(",\n");

//	    sb.append("  \"subtituloItemAsignacionPreview\": ").append(subtituloItemAsignacionPreview != null ? subtituloItemAsignacionPreview.size() : 0).append(",\n");
	    sb.append("  \"convenioPreview\": ").append(convenioPreview != null ? "\"" + convenioPreview + "\"" : null).append(",\n");
	    sb.append("  \"convenio\": ").append(convenio != null ? "\"" + convenio.getId() + "\"" : null).append(",\n");

	    sb.append("  \"totalTramiteModRec\": ").append(totalTramiteModRec).append(",\n");
	    sb.append("  \"comentarioModRec\": ").append(comentarioModRec != null ? "\"" + comentarioModRec + "\"" : null).append(",\n");
	    sb.append("  \"fechaDesdeModRec\": ").append(fechaDesdeModRec != null ? "\"" + fechaDesdeModRec + "\"" : null).append(",\n");
	    // sb.append("  \"tiemposCargaFormulario\": ").append(tiemposCargaFormulario != null ? tiemposCargaFormulario.size() : 0).append(",\n");

//	    sb.append("  \"asignacion\": ").append(asignacion != null ? asignacion.size() : 0).append(",\n");
//	    sb.append("  \"estudioPreview\": ").append(estudioPreview != null ? "\"" + estudioPreview.getNombre() + "\"" : null).append(",\n");
//	    sb.append("  \"encomendacionPreview\": ").append(encomendacionPreview != null ? "\"" + encomendacionPreview.getNombre() + "\"" : null).append(",\n");
//	    sb.append("  \"asignacionPreview\": ").append(asignacionPreview != null ? "\"" + asignacionPreview.getNombre() + "\"" : null).append(",\n");

	    sb.append("  \"orden\": ").append(orden).append(",\n");

	    sb.append("  \"existeFicheroConvenio\": ").append(existeFicheroConvenio).append(",\n");
	    sb.append("  \"existenFicherosAdjuntos\": ").append(existenFicherosAdjuntos).append(",\n");
	    sb.append("  \"existenFicherosAntAdjuntos\": ").append(existenFicherosAntAdjuntos).append("\n");
	    
	    sb.append("}");

	    return sb.toString();
	}


}
