package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 07-jul-2017 9:24:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * ActosMasivo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_CASOS_MASIVO")
public class CasoMasivo implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -3632747007657945567L;
	
	private Long id;
	private Region region;
	private Comuna comuna;
	private Servicio dependenciaDestino;
	private Servicio servicioDestino;
	private ActoMasivo actoMasivo;
	private Date fechaDesde;
	private Date fechaHasta;
	private String motivo;
	private boolean beneficio;
	private String detalleBeneficio;
	private String run;
	private String digitVerif;
	private Date version;
	private Set<BenCargMasivo> benCargMasivo = new HashSet<BenCargMasivo>(0);
	private String beneficioPreview;
	private String fechaDesdePreview;
	private String fechaHastaPreview;
	private Double monto;

	public CasoMasivo() {
	}

	public CasoMasivo(Region region,
	                   Comuna comuna,
	                   Servicio dependenciaDestino,
	                   Servicio servicioDestino,
	                   CargaMasiva cargaMasiva,
	                   Date fechaDesde,
	                   Date fechaHasta,
	                   String motivo,
	                   boolean beneficio,
	                   String detalleBeneficio,
	                   String run,
	                   String digitVerif,
	                   Set<BenCargMasivo> benCargMasivo) {

		this.region = region;
		this.comuna = comuna;
		this.dependenciaDestino = dependenciaDestino;
		this.servicioDestino = servicioDestino;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.motivo = motivo;
		this.beneficio = beneficio;
		this.detalleBeneficio = detalleBeneficio;
		this.run = run;
		this.digitVerif = digitVerif;
		this.benCargMasivo = benCargMasivo;
	}

	public CasoMasivo(Region region,
	                   Comuna comuna,
	                   Servicio dependenciaDestino,
	                   Servicio servicioDestino,
	                   CargaMasiva cargaMasiva,
	                   Date fechaDesde,
	                   Date fechaHasta,
	                   String motivo,
	                   boolean beneficio,
	                   String detalleBeneficio,
	                   String run,
	                   String digitVerif,
	                   Date version,
	                   Set<BenCargMasivo> benCargMasivo) {

		this.region = region;
		this.comuna = comuna;
		this.dependenciaDestino = dependenciaDestino;
		this.servicioDestino = servicioDestino;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.motivo = motivo;
		this.beneficio = beneficio;
		this.detalleBeneficio = detalleBeneficio;
		this.run = run;
		this.digitVerif = digitVerif;
		this.version = version;
		this.benCargMasivo = benCargMasivo;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_CASM_X_CASM")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_CASM", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGI_X_REGI")
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMU_X_COMU")
	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SERV_X_SERV_DEP_DES")
	public Servicio getDependenciaDestino() {
		return dependenciaDestino;
	}
	
	public void setDependenciaDestino(Servicio dependenciaDestino) {
		this.dependenciaDestino = dependenciaDestino;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SERV_X_SERV_D")
	public Servicio getServicioDestino() {
		return servicioDestino;
	}
	
	public void setServicioDestino(Servicio servicioDestino) {
		this.servicioDestino = servicioDestino;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "F_FECHA_DESDE", nullable = false, length = 7)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "F_FECHA_HASTA", nullable = false, length = 7)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@Column(name = "T_MOTIVO", nullable = false, length = 150)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Column(name = "L_BENEFICIO", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean getBeneficio() {
		return this.beneficio;
	}

	public void setBeneficio(boolean beneficio) {
		this.beneficio = beneficio;
	}

	@Column(name = "T_DETALLE_BENEFICIO", length = 255)
	public String getDetalleBeneficio() {
		return this.detalleBeneficio;
	}

	public void setDetalleBeneficio(String detalleBeneficio) {
		this.detalleBeneficio = detalleBeneficio;
	}

	@Column(name = "T_RUN", nullable = false, length = 10)
	public String getRun() {
		return this.run;
	}

	public void setRun(String run) {
		this.run = run;
	}

	@Column(name = "T_DIGIT_VERIF", nullable = false, length = 10)
	public String getDigitVerif() {
		return this.digitVerif;
	}

	public void setDigitVerif(String digitVerif) {
		this.digitVerif = digitVerif;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACMA_X_ACMA", nullable = false)
	public ActoMasivo getActoMasivo() {
		return actoMasivo;
	}

	public void setActoMasivo(ActoMasivo actoMasivo) {
		this.actoMasivo = actoMasivo;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoMasivo", cascade = CascadeType.ALL)
	public Set<BenCargMasivo> getBenCargMasivo() {
		return this.benCargMasivo;
	}

	public void setBenCargMasivo(Set<BenCargMasivo> benCargMasivo) {
		this.benCargMasivo = benCargMasivo;
	}

	/**
	 * @return the beneficioPreview
	 */
	@Transient
	public String getBeneficioPreview() {
		return beneficioPreview;
	}

	/**
	 * @param beneficioPreview the beneficioPreview to set
	 */
	public void setBeneficioPreview(String beneficioPreview) {
		this.beneficioPreview = beneficioPreview;
	}
	
	@Transient
	public String getFechaDesdePreview() {
		return fechaDesdePreview;
	}

	public void setFechaDesdePreview(String fechaDesdePreview) {
		this.fechaDesdePreview = fechaDesdePreview;
	}

	@Transient
	public String getFechaHastaPreview() {
		return fechaHastaPreview;
	}

	public void setFechaHastaPreview(String fechaHastaPreview) {
		this.fechaHastaPreview = fechaHastaPreview;
	}
	
	@Column(name = "S_MONTO", nullable = true, length = 12, scale = 2)
	public Double getMonto() {
		return monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}
	
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CasoMasivo))
			return false;
		CasoMasivo castOther = (CasoMasivo) other;
		
		// Comprobemos si se trata de un caso ya registrado: 
		// RUN
		
		return this.getRun() != null && this.getDigitVerif() != null 
				&& castOther.getRun() != null && castOther.getDigitVerif() != null 
				&& (this.getRun() + "-" + this.getDigitVerif()).equalsIgnoreCase(castOther.getRun() + "-" + castOther.getDigitVerif());
	}

}