package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 18-oct-2011 11:46:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

import static jakarta.persistence.GenerationType.SEQUENCE;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * CatalogoExpresion generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_CATALOGO_EXPRESIONES", uniqueConstraints = @UniqueConstraint(columnNames = "T_TEXTO"))
public class CatalogoExpresion implements java.io.Serializable, Cloneable {

	private static final long serialVersionUID = -6160824317721917565L;

	private Long id;
	private Date version;
	private String tipo;
	private String descripcion;
	private String texto;
	private String codDrl;
	private String codUsuarioBloq;
	private String tipoRetorno;

	public CatalogoExpresion() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_CAEX_X_CAEX")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_CAEX", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "T_TIPO", nullable = false, length = 2)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "T_DESCRIPCION", length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "T_TEXTO", unique = true, nullable = false, length = 50)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "C_DRL", nullable = false, length = 150)
	public String getCodDrl() {
		return this.codDrl;
	}

	public void setCodDrl(String codDrl) {
		this.codDrl = codDrl;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "T_TIPO_RETORNO", nullable = false, length = 1)
	public String getTipoRetorno() {
		return this.tipoRetorno;
	}

	public void setTipoRetorno(String tipoRetorno) {
		this.tipoRetorno = tipoRetorno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatalogoExpresion))
			return false;
		CatalogoExpresion castOther = (CatalogoExpresion) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Tipo: " + tipo + ", descripcion: " + descripcion;
	}
	
	public CatalogoExpresion clone() {
		try {
			return (CatalogoExpresion) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}
}
