package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;


import java.util.Date;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * AntecedenteEducacional generated by hbm2java
 */
@Entity
@Audited
@AuditTable("TRA_CESE_MINISTERIO_HIST")
@Table(name = "TRA_CESE_MINISTERIO")
public class CeseMinisterio implements java.io.Serializable, Cloneable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 5545889405354551525L;
	
	private Long id;
	private CasoDocumento casoDocumento;
	private Long casoId;
	private Long tipoDocumento;
	private String glosaTDocumento;
	private String numeroDocumento;
	private Date fechaDocumento;
	private Date fechaDesde;
	private Date fechaHasta;
	private Long materiaDocumento;
	private String glosaMateriaDoc;
	private Long calidad;
	private String glosaCalidad;
	private Long estadoCGR;
	private Long estadoEstudio;
	private String estadoTramiteFinal;
	private Long documentoId;
	private Long dotacionVigente;
	private Long designacionHonorario;
	private Date fechaVersion;
	
	
	public CeseMinisterio() {
		
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_CEMI_X_CEMI")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_CEMI", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CADO_X_CADO", nullable = false)
	public CasoDocumento getCasoDocumento() {
		return this.casoDocumento;
	}

	public void setCasoDocumento(CasoDocumento casoDocumento) {
		this.casoDocumento = casoDocumento;
	}
	
	@Column(name = "C_CASO_ID", length = 7)
	public Long getCasoId() {
		return this.casoId;
	}
	public void setCasoId(Long casoId) {
		this.casoId = casoId;
	}
	@Column(name = "C_TIPO_DOCUMENTO", length = 7)
	public Long getTipoDocumento() {
		return this.tipoDocumento;
	}
	public void setTipoDocumento(Long tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}
	
	@Column(name = "D_GLOSA_TDOCUMENTO", length = 2000)
	public String getGlosaTDocumento() {
		return glosaTDocumento;
	}
	public void setGlosaTDocumento(String glosaTDocumento) {
		this.glosaTDocumento = glosaTDocumento;
	}
	
	@Column(name = "D_NUMERO_DOCUMENTO", length = 255)
	public String getNumeroDocumento() {
		return numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FECHA_DOCUMENTO", length = 7)
	public Date getFechaDocumento() {
		return fechaDocumento;
	}

	public void setFechaDocumento(Date fechaDocumento) {
		this.fechaDocumento = fechaDocumento;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FECHA_DESDE", length = 7)
	public Date getFechaDesde() {
		return fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FECHA_HASTA", length = 7)
	public Date getFechaHasta() {
		return fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}
	@Column(name = "C_MATERIA_DOCUMENTO", length = 150)
	public Long getMateriaDocumento() {
		return materiaDocumento;
	}
	public void setMateriaDocumento(Long materiaDocumento) {
		this.materiaDocumento = materiaDocumento;
	}
	@Column(name = "D_GLOSA_MDOCUMENTO", length = 2000)
	public String getGlosaMateriaDoc() {
		return glosaMateriaDoc;
	}

	public void setGlosaMateriaDoc(String glosaMateriaDoc) {
		this.glosaMateriaDoc = glosaMateriaDoc;
	}
	@Column(name = "C_CALIDAD_MODALIDAD", length = 7)
	public Long getCalidad() {
		return calidad;
	}

	public void setCalidad(Long calidad) {
		this.calidad = calidad;
	}
	@Column(name = "D_GLOSA_CALMOD", length = 2000)
	public String getGlosaCalidad() {
		return glosaCalidad;
	}

	public void setGlosaCalidad(String glosaCalidad) {
		this.glosaCalidad = glosaCalidad;
	}
	
	@Column(name = "C_ESTADO_CGR", length = 7)
	public Long getEstadoCGR() {
		return estadoCGR;
	}

	public void setEstadoCGR(Long estadoCGR) {
		this.estadoCGR = estadoCGR;
	}
	
	@Column(name = "C_ESTADO_ESTUDIO", length = 7)
	public Long getEstadoEstudio() {
		return estadoEstudio;
	}

	public void setEstadoEstudio(Long estadoEstudio) {
		this.estadoEstudio = estadoEstudio;
	}
	
	@Column(name = "D_E_TRAMITEFINAL", length = 2000)
	public String getEstadoTramiteFinal() {
		return estadoTramiteFinal;
	}

	public void setEstadoTramiteFinal(String estadoTramiteFinal) {
		this.estadoTramiteFinal = estadoTramiteFinal;
	}
	
	@Column(name = "C_DOCUMENTOID", length = 7)
	public Long getDocumento() {
		return documentoId;
	}

	public void setDocumento(Long documentoId) {
		this.documentoId = documentoId;
	}
	
	@Column(name = "C_DOTACIONVIGID", length = 7)
	public Long getDotacionVigente() {
		return dotacionVigente;
	}

	public void setDotacionVigente(Long dotacionVigente) {
		this.dotacionVigente = dotacionVigente;
	}
	
	@Column(name = "L_DESIGNACIONHONORARIO", length = 7)
	public Long getDesignacionHonorario() {
		return designacionHonorario;
	}

	public void setDesignacionHonorario(Long designacionHonorario) {
		this.designacionHonorario = designacionHonorario;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getFechaVersion() {
		return this.fechaVersion;
	}

	public void setFechaVersion(Date fechaVersion) {
		this.fechaVersion = fechaVersion;
	}
		
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CeseMinisterio))
			return false;
		CeseMinisterio castOther = (CeseMinisterio) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public boolean equalsInvoker(CeseMinisterio cese) {
		if (casoId.longValue() == cese.getCasoId().longValue()) {
			return true;
		}
		return false;
	}

}
