package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 18-oct-2011 11:46:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * Configuracion generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_CONFIGURACIONES")
public class Configuracion implements java.io.Serializable {

	private static final long serialVersionUID = -442350301194615500L;

	private String codigo;
	private Date version;
	private String valor;
	private String descripcion;
	private String codUsuarioBloq;

	public Configuracion() {
	}

	@Id
	@Column(name = "C_CODIGO", unique = true, nullable = false, length = 30)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codCodigo) {
		this.codigo = codCodigo;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "T_VALOR", nullable = false, length = 4000)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "T_DESCRIPCION", nullable = false, length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Configuracion))
			return false;
		Configuracion castOther = (Configuracion) other;
		return this.getCodigo() != null && castOther.getCodigo() != null && this.getCodigo().equals(castOther.getCodigo());
	}

}
