package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 27-sep-2011 11:33:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * DatoCaso generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_DATOS_CASOS")
public class DatoCaso implements java.io.Serializable {

	private static final long serialVersionUID = 735634359955757016L;

	private Long id;
	private Date version;
	private CasoDocumento casoDocumento;
	private String atributo;
	private String valor;
	private String codUsuarioBloq;
	private String descripcion;
	
	// El grupo y el registro en el caso de que pertenezca a un multirregistro
	private String grupo;
	private Integer numRegistro;

	public DatoCaso() {
	}

	@Id 
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_DACA_X_DACA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_DACA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CADO_X_CADO", nullable = false)
	@JsonIgnore //add siaper-ru
	public CasoDocumento getCasoDocumento() {
		return this.casoDocumento;
	}

	public void setCasoDocumento(CasoDocumento casoDocumento) {
		this.casoDocumento = casoDocumento;
	}

	@Column(name = "T_ATRIBUTO", nullable = false, length = 250)
	public String getAtributo() {
		return this.atributo;
	}

	public void setAtributo(String atributo) {
		this.atributo = atributo;
	}

	@Column(name = "T_VALOR", length = 3000)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "T_DESCRIPCION", length = 3000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "T_GRUPO", length = 250)
	public String getGrupo() {
		return grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "N_REGISTRO", precision = 10)
	public Integer getNumRegistro() {
		return numRegistro;
	}

	public void setNumRegistro(Integer numRegistro) {
		this.numRegistro = numRegistro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatoCaso))
			return false;
		DatoCaso castOther = (DatoCaso) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		StringBuilder datos = new StringBuilder();
		datos.append("Atributo: ");
		datos.append(atributo);
		datos.append(", valor: ");
		datos.append(valor);
		datos.append(", Caso: (");
		datos.append(casoDocumento.getRun());
		datos.append(" - ");
		datos.append(casoDocumento.getApellidos());
		datos.append(", ");
		datos.append(casoDocumento.getNombres());
		datos.append(" - Documento: ");
		datos.append(casoDocumento.getDocumento().getNumDocuFirmado() == null ? casoDocumento.getDocumento().getNumDocuBorrador() : casoDocumento.getDocumento().getNumDocuFirmado());
		datos.append(")");
		return datos.toString();
	}


}
