package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 28-oct-2011 13:37:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import com.fasterxml.jackson.annotation.JsonIgnore;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * DatoRaiz generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_DATOS_RAIZ")
public class DatoRaiz implements java.io.Serializable {

	private static final long serialVersionUID = 9178555620166215144L;

	private Long id;
	private Date version;
	private Fichero fichero;
	private RegimenPrevisional regimenPrevisional;
	private EstadoCivil estadoCivil;
	private Region region;
	private Comuna comuna;
	private RegimenSalud regimenSalud;
	private Date fechaFallecimiento;
	private String correoElectronico;
	private String correoElectronico1;
	private String correoElectronico2;
	private String correoElectronico3;
	private String correoElectronico4;
	private String correoElectrPers;
	private Boolean leyReclutamiento;
	private Boolean servicioMilitar;
	private Boolean condenaCrimen;
	private String especificacionAnotacion;
	private Boolean condenadoPena;
	private String inhabilidad;
	private String nombreVia;
	private String numNumero;
	private String departamento;
	private String codUsuarioBloq;
	private Set<CasoDocumento> casoDocumentos = new HashSet<CasoDocumento>(0);
	private Boolean sitMilitarDia;

	public DatoRaiz() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_DARA_X_DARA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_DARA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "FICH_X_FICH")
	public Fichero getFichero() {
		return this.fichero;
	}

	public void setFichero(Fichero fichero) {
		this.fichero = fichero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPR_X_REPR")
	public RegimenPrevisional getRegimenPrevisional() {
		return this.regimenPrevisional;
	}

	public void setRegimenPrevisional(RegimenPrevisional regimenPrevisional) {
		this.regimenPrevisional = regimenPrevisional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESCI_X_ESCI")
	public EstadoCivil getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(EstadoCivil estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGI_X_REGI")
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMU_X_COMU")
	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESA_X_RESA")
	public RegimenSalud getRegimenSalud() {
		return this.regimenSalud;
	}

	public void setRegimenSalud(RegimenSalud regimenSalud) {
		this.regimenSalud = regimenSalud;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FALLECIMIENTO", length = 7)
	public Date getFechaFallecimiento() {
		return this.fechaFallecimiento;
	}

	public void setFechaFallecimiento(Date fechaFallecimiento) {
		this.fechaFallecimiento = fechaFallecimiento;
	}

	@Column(name = "T_CORREO_ELECTRONICO", length = 150)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}
	
	@Column(name = "T_CORREO_ELECTRONICO_1", length = 150)
	public String getCorreoElectronico1() {
		return correoElectronico1;
	}

	public void setCorreoElectronico1(String correoElectronico1) {
		this.correoElectronico1 = correoElectronico1;
	}

	@Column(name = "T_CORREO_ELECTRONICO_2", length = 150)
	public String getCorreoElectronico2() {
		return correoElectronico2;
	}

	public void setCorreoElectronico2(String correoElectronico2) {
		this.correoElectronico2 = correoElectronico2;
	}

	@Column(name = "T_CORREO_ELECTRONICO_3", length = 150)
	public String getCorreoElectronico3() {
		return correoElectronico3;
	}

	public void setCorreoElectronico3(String correoElectronico3) {
		this.correoElectronico3 = correoElectronico3;
	}

	@Column(name = "T_CORREO_ELECTRONICO_4", length = 150)
	public String getCorreoElectronico4() {
		return correoElectronico4;
	}

	public void setCorreoElectronico4(String correoElectronico4) {
		this.correoElectronico4 = correoElectronico4;
	}

	@Column(name = "T_CORREO_ELECTR_PERS", length = 150)
	public String getCorreoElectrPers() {
		return this.correoElectrPers;
	}

	public void setCorreoElectrPers(String correoElectrPers) {
		this.correoElectrPers = correoElectrPers;
	}

	@Column(name = "L_LEY_RECLUTAMIENTO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getLeyReclutamiento() {
		return this.leyReclutamiento;
	}

	public void setLeyReclutamiento(Boolean leyReclutamiento) {
		this.leyReclutamiento = leyReclutamiento;
	}

	@Column(name = "L_SERVICIO_MILITAR", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getServicioMilitar() {
		return this.servicioMilitar;
	}

	public void setServicioMilitar(Boolean servicioMilitar) {
		this.servicioMilitar = servicioMilitar;
	}

	@Column(name = "L_CONDENA_CRIMEN", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getCondenaCrimen() {
		return this.condenaCrimen;
	}

	public void setCondenaCrimen(Boolean condenaCrimen) {
		this.condenaCrimen = condenaCrimen;
	}
	
	@Column(name = "T_ESPECIFICACION_ANOTACION", length = 500)
	public String getEspecificacionAnotacion() {
		return especificacionAnotacion;
	}

	public void setEspecificacionAnotacion(String especificacionAnotacion) {
		this.especificacionAnotacion = especificacionAnotacion;
	}

	@Column(name = "L_CONDENADO_PENA", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getCondenadoPena() {
		return this.condenadoPena;
	}

	public void setCondenadoPena(Boolean condenadoPena) {
		this.condenadoPena = condenadoPena;
	}
	
	@Column(name = "L_INHABILIDAD_MEN", length = 1)
	public String getInhabilidad() {
		return this.inhabilidad;
	}

	public void setInhabilidad(String inhabilidad) {
		this.inhabilidad = inhabilidad;
	}

	@Column(name = "T_NOMBRE_VIA", length = 150)
	public String getNombreVia() {
		return this.nombreVia;
	}

	public void setNombreVia(String nombreVia) {
		this.nombreVia = nombreVia;
	}

	@Column(name = "N_NUMERO", length = 5)
	public String getNumNumero() {
		return this.numNumero;
	}

	public void setNumNumero(String numNumero) {
		this.numNumero = numNumero;
	}

	@Column(name = "T_DEPARTAMENTO", length = 10)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datoRaiz")
	@JsonIgnore //add siaper-ru
	public Set<CasoDocumento> getCasoDocumentos() {
		return this.casoDocumentos;
	}

	public void setCasoDocumentos(Set<CasoDocumento> casoDocumentos) {
		this.casoDocumentos = casoDocumentos;
	}
	
	@Column(name = "L_SITMILITARDIA", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getSitMilitarDia() {
		return sitMilitarDia;
	}

	public void setSitMilitarDia(Boolean sitMilitarDia) {
		this.sitMilitarDia = sitMilitarDia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatoRaiz))
			return false;
		DatoRaiz castOther = (DatoRaiz) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() { 
		CasoDocumento caso = (CasoDocumento) getCasoDocumentos().toArray()[0];
		StringBuilder datos = new StringBuilder();
		datos.append("Caso: (");
		datos.append(caso);
		datos.append(")");
		return datos.toString();
	}

}
