package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 13-oct-2011 16:37:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * Reporte generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_DEST_CORREO_BLOQ")
public class DestinatarioCorreo implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 8546869377644766772L;
	
	private Long id;	
	private String correo;
	private Date version;
	private String codUsuarioBloq;
	
	public DestinatarioCorreo() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_DCOB_X_DCOB")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_DCOB", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@Column(name = "T_CORREO", nullable = false, length = 150)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 30)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
}