package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * DetalleCargo generated by hbm2java
 */
@Entity
@Table(name = "TRA_DETALLE_CARGO")
public class DetalleCargo implements java.io.Serializable {

	private static final long serialVersionUID = 1355305686471325152L;
	
	private Long id;
	private Date version;
	private Long sCalidad;
	private String cjudescripcion;
	private Long desfuncionarioid;
	private String run;
	private String nombreFuncionario;
	private String numResolucion;
	private Date fechaResolucion;
	private Date fechaDesde;
	private Date fechaHasta;
	private Long sServicio;
	private Long sPlantaCargo;
	private Long sCargo;
	private Long sNaturaleza;
	private Long sGrado;
	private Long sNivel;
	private Long sCategoria;
	private Long sEspecialidad;
	private Long sTipoHoras;
	private Short nHoras;
	private Long sRemuneracion; // Asociado al grado
	private Long desDesignacionId;
	private Long desDesignacionAnteriorId;
	private String otraIdentificacion;
	
	private Cargo cargoTra;
	private Servicio servicioTra;
	private Grado gradoTra;
	
	//ELEMENTOS QUE ANTES HABIA, Y AHORA NO
//	MERITO
//	art55bis
	
	private boolean primerElementoVacio;
	private int numOrden;

	public DetalleCargo() {
	}
	
	public DetalleCargo(int orden, boolean primerElementoVacio) {
		this.numOrden = orden;
		this.primerElementoVacio = primerElementoVacio;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_DECA_X_DECA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_DECA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Transient
	public int getNumOrden() {
		return this.numOrden;
	}

	public void setNumOrden(int numOrden) {
		this.numOrden = numOrden;
	}

	@Column(name = "T_RUN", length = 10)
	public String getRun() {
		return this.run;
	}

	public void setRun(String run) {
		this.run = run;
	}

	@Column(name = "T_NOMBRE_FUNCIONARIO", length = 150)
	public String getNombreFuncionario() {
		return this.nombreFuncionario;
	}

	public void setNombreFuncionario(String nombreFuncionario) {
		this.nombreFuncionario = nombreFuncionario;
	}

	@Column(name = "T_NUM_RESOLUCION", length = 15)
	public String getNumResolucion() {
		return this.numResolucion;
	}

	public void setNumResolucion(String numResolucion) {
		this.numResolucion = numResolucion;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_RESOLUCION", length = 7, nullable = false)
	public Date getFechaResolucion() {
		return this.fechaResolucion;
	}

	public void setFechaResolucion(Date fechaResolucion) {
		this.fechaResolucion = fechaResolucion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_DESDE", length = 7)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_HASTA", length = 7)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}
	
	@Column(name = "S_CALI",precision = 12, scale = 0, nullable = false)
	public Long getsCalidad() {
		return sCalidad;
	}
	
	public void setsCalidad(Long sCalidad) {
		this.sCalidad = sCalidad;
	}
	
	@Column(name = "CJUDESCRIPCION", length = 150)
	public String getCjudescripcion() {
		return cjudescripcion;
	}
	
	public void setCjudescripcion(String cjudescripcion) {
		this.cjudescripcion = cjudescripcion;
	}
	
	@Column(name = "DESFUNCIONARIOID", precision = 12)
	public Long getDesfuncionarioid() {
		return desfuncionarioid;
	}
	
	public void setDesfuncionarioid(Long desfuncionarioid) {
		this.desfuncionarioid = desfuncionarioid;
	}
	
	@Column(name = "S_SERV", precision = 12, scale = 0)
	public Long getsServicio() {
		return sServicio;
	}
	
	public void setsServicio(Long sServicio) {
		this.sServicio = sServicio;
	}
	
	@Column(name = "S_PLCA", precision = 12, scale = 0, nullable = false)
	public Long getsPlantaCargo() {
		return sPlantaCargo;
	}
	
	public void setsPlantaCargo(Long sPlantaCargo) {
		this.sPlantaCargo = sPlantaCargo;
	}
	
	@Column(name = "S_CARG", precision = 4, scale = 0, nullable = false)
	public Long getsCargo() {
		return sCargo;
	}
	
	public void setsCargo(Long sCargo) {
		this.sCargo = sCargo;
	}
	
	@Column(name = "S_NATU", precision = 12, scale = 0)
	public Long getsNaturaleza() {
		return sNaturaleza;
	}
	
	public void setsNaturaleza(Long sNaturaleza) {
		this.sNaturaleza = sNaturaleza;
	}
	
	@Column(name = "S_GRAD", precision = 12, scale = 0, nullable = false)
	public Long getsGrado() {
		return sGrado;
	}
	
	public void setsGrado(Long sGrado) {
		this.sGrado = sGrado;
	}
	
	@Column(name = "S_NIVE", precision = 12, scale = 0, nullable = false)
	public Long getsNivel() {
		return sNivel;
	}
	
	public void setsNivel(Long sNivel) {
		this.sNivel = sNivel;
	}
	
	@Column(name = "S_CATE", nullable = false, precision = 4, scale = 0)
	public Long getsCategoria() {
		return sCategoria;
	}
	
	public void setsCategoria(Long sCategoria) {
		this.sCategoria = sCategoria;
	}
	
	@Column(name = "S_ESPE", precision = 4, scale = 0, nullable = false)
	public Long getsEspecialidad() {
		return sEspecialidad;
	}
	
	public void setsEspecialidad(Long sEspecialidad) {
		this.sEspecialidad = sEspecialidad;
	}
	
	@Column(name = "S_TIHO",  precision = 4, scale = 0, nullable = false)
	public Long getsTipoHoras() {
		return sTipoHoras;
	}
	
	public void setsTipoHoras(Long sTipoHoras) {
		this.sTipoHoras = sTipoHoras;
	}
	
	@Column(name = "N_HORAS", precision = 5, scale = 0)
	public Short getnHoras() {
		return nHoras;
	}
	
	public void setnHoras(Short nHoras) {
		this.nHoras = nHoras;
	}
	
	@Column(name = "S_REMU", precision = 4, scale = 0, nullable = false)
	public Long getsRemuneracion() {
		return sRemuneracion;
	}
	
	public void setsRemuneracion(Long sRemuneracion) {
		this.sRemuneracion = sRemuneracion;
	}
	
	public void setPrimerElementoVacio(boolean primerElementoVacio) {
		this.primerElementoVacio = primerElementoVacio;
	}
	
	@Column(name = "DESDESIGNACIONID", precision = 12, scale = 0, nullable = false)
	public Long getDesDesignacionId() {
		return desDesignacionId;
	}

	public void setDesDesignacionId(Long desDesignacionId) {
		this.desDesignacionId = desDesignacionId;
	}
	
	@Column(name = "DESDESIGNACIONANTERIORID", precision = 12, scale = 0, nullable = false)
	public Long getDesDesignacionAnteriorId() {
		return desDesignacionAnteriorId;
	}

	public void setDesDesignacionAnteriorId(Long desDesignacionAnteriorId) {
		this.desDesignacionAnteriorId = desDesignacionAnteriorId;
	}
	
	@Column(name = "T_OTRA_IDENTIFICACION", length = 50)
	public String getOtraIdentificacion() {
		return otraIdentificacion;
	}

	public void setOtraIdentificacion(String otraIdentificacion) {
		this.otraIdentificacion = otraIdentificacion;
	}

	@Transient
	public boolean isPrimerElementoVacio() {
		return primerElementoVacio;
	}
	
	@Transient
	public Cargo getCargoTra() {
		return cargoTra;
	}

	public void setCargoTra(Cargo cargoTra) {
		this.cargoTra = cargoTra;
	}

	@Transient
	public Servicio getServicioTra() {
		return servicioTra;
	}

	public void setServicioTra(Servicio servicioTra) {
		this.servicioTra = servicioTra;
	}

	@Transient
	public Grado getGradoTra() {
		return gradoTra;
	}

	public void setGradoTra(Grado gradoTra) {
		this.gradoTra = gradoTra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetalleCargo))
			return false;
		DetalleCargo castOther = (DetalleCargo) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
}
