package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 02-nov-2011 16:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.OrderBy;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

//import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.documento.hist.GeneracionDocumentos;
import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * Documento generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_DOCUMENTOS")
public class Documento implements java.io.Serializable, Entidad, Cloneable {

	private static final long serialVersionUID = -1937483094013020772L;

	private Long id;
	private Date version;
	private Long codSiaper;
	private TipoDocumento tipoDocumento;
	private Servicio servicioRecepcion;
	private AccionDocumento accionDocumento;
	private Servicio servicio;
	private Servicio servicioEmisor;
	private Materia materia;
	private String vigencia;
	private String numDocuBorrador;
	private String numDocuFirmado;
	private Short numAnioFirmado;
	private Date fechaCreacion;
	private Date fechaFirma;
	private Date fechaTramitacion;
	private Date fechaEnvioEstudio;
	private Date fechaEnvioAnalista;
	private String bitacora;
	private String codUsuarioBloq;
	private Long codSiaperCodPresupuestario;
	private String descripcionSiaperCodPresupuestario;
	private String codUsuarioAsign;
	private String codUsuarioAsignEnv;
	private String codUsuarioAsign2;
	private Boolean completo;
	private Fichero ficheroFirmaContralor;
	private Fichero ficheroOficioRepresentacion;
	private Fichero ficheroRetirarDocumento;
	private OficioRepresenta oficioRepresentaUnico;
	private String tipoContraloria;
	private Boolean visarSubsecretYMinistro;
	private String motivoRechazoSubsecOMinis;
	private boolean revisionRepresentacion;
	private String resultadoTomaRaAutomatica;
	private Division division;
	private Division divisionRepresentado;
	private Set<Firmas> firmasUnico = new HashSet<Firmas>(0);
	private Set<CasoDocumento> casosDocumento = new HashSet<CasoDocumento>(0);
	private Set<FirmaDoc> firmas = new HashSet<FirmaDoc>(0);
	private Set<EstadoDocumento> estadosDocumento = new HashSet<EstadoDocumento>(0);
	private Set<Volcado> volcados = new HashSet<Volcado>(0);
	
	private Set<DocumentoSinEfecto> documentosSinEfectoPadre = new HashSet<DocumentoSinEfecto>(0);
	private Set<DocumentoSinEfecto> documentosSinEfectoHijo = new HashSet<DocumentoSinEfecto>(0);
	
	private Set<SubtituloDocumento> subtitulosDocumento = new HashSet<SubtituloDocumento>(0);
	private Set<Comentario> comentarios = new HashSet<Comentario>(0);
	
	private Boolean sinAfecto;
	

	private String estado;
	private String codigoEstado;
	private boolean otroServicio;
	private boolean otraDivision;
	private String perfil;
	private boolean seleccionado;
	
	private boolean mostrarEdicion;
	private boolean mostrarErrores;
	private boolean mostrarGeneracion;
	private boolean mostrarEliminacion;
	private boolean mostrarBitacora;
	private boolean mostrarEnvioMinistroFe;
	private boolean mostrarRevisionMinistroFe;
	private boolean mostrarDeclaracionAntecedentes;
	private boolean mostrarDevolverCreador;
	private boolean mostrarEnvioFirmante;
	private boolean mostrarFirma;
	private boolean mostrarDevolverMinistroFe;
	private boolean mostrarTomaDeRazon;
	private boolean mostrarEnvioTomaRazon;
	private boolean mostrarAnalistaWarnings;
	private boolean mostrarJefeWarnings;
	private boolean mostrarXMLFirma;
	private boolean mostrarEnviarVisacionDoc;
	private boolean mostrarVisacionDoc;
	private boolean firmaContralor;
	private boolean tieneOficioPDF;
	private boolean mostrarReasignarFirmante;
	private boolean mostrarReasignarVisador;
	private boolean mostrarOpcionesRechazoFirma;
	private boolean perteneceRegion;
	private boolean enviadoParaAnular;
	
	private String considerando;
	private Servicio contraloriaEmisora;
	
	private String considerandos;
	
	/**
	 * Variables para documentos
	 */
	
	private String servicioEmisorString;
	private String fechaEmisionString;
	private String numeroOficio;
	private String membreteOficio;
	private String detalleOficio;
	
	private List<CasoDocumento> casosDocumento2;
	private List<Ley> atomosVistos;
	private List<Ley> atomosVistosSinEfecto;
	private String usuarioPreview;
	private String tipoContratoCt="";
	private String causalCeseArt160="";
	private String naturalezaCargo="";
	private String listaBeneficios;
	private String acogeBeneficios;
	private String fechaDesde;
	private String fechaDesdeSinEfectoPreview;
	private String subtituloItemPreview="";
	private String lineaFinalPreview;
	private String conservaCargoPreview;
	private String numDocuFirmadoSinEfectoPreview;

	private Boolean envotroserv;
	private Boolean firmVisOtroServ;
	
	private boolean certificable;
	
//	private List<GeneracionDocumentos.SiaPreview> subtituloItemAsignacionPreview;

	private String lClonado;
	
	private String estadoExterno;
	
	private String perfilExterno;
	
	private Fichero ficheroImagenServicio;
	
	private Set<DocumentoModificaRectifica> documentosModificaRectificaPadre = new HashSet<DocumentoModificaRectifica>(0);
	private Set<DocumentoModificaRectifica> documentosModificaRectificaHijo = new HashSet<DocumentoModificaRectifica>(0);
	
	private boolean modificado;
	private boolean modificarRectificar;
	
	private Documento documentoModificado;
	private Materia materiaModifica;
	private Servicio contraloriaAsignada;
	private boolean enviadoDiario;
	private Set<EstadoDiarioDoc> estadoDiarioDoc = new HashSet<EstadoDiarioDoc>(0);
	private String comentarioDiario	;
	private String codigoDiario	;
	
	private Servicio servicioCreador;
	private Servicio servicioEmisorOriginal;
	
	private String codUsuarioCreador;
	
	private String plantillaResolucion;
	
	private boolean hasOficioPdf;
	private boolean esSupervisorCGR;
	private Estado estadoDocumento; 
	public Documento() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_DOCU_X_DOCU")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_DOCU", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIDO_X_TIDO", nullable = false)
	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV_A")
	public Servicio getServicioRecepcion() {
		return this.servicioRecepcion;
	}

	public void setServicioRecepcion(Servicio servicioByServXServA) {
		this.servicioRecepcion = servicioByServXServA;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACDO_X_ACDO", nullable = false)
	public AccionDocumento getAccionDocumento() {
		return this.accionDocumento;
	}

	public void setAccionDocumento(AccionDocumento accionDocumento) {
		this.accionDocumento = accionDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV_D")
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicioByServXServD) {
		this.servicio = servicioByServXServD;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV_E")
	public Servicio getServicioEmisor() {
		return this.servicioEmisor;
	}

	public void setServicioEmisor(Servicio servicioByServXServE) {
		this.servicioEmisor = servicioByServXServE;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATE_X_MATE", nullable = false)
	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	@Column(name = "T_NUM_DOCU_BORRADOR", length = 150)
	public String getNumDocuBorrador() {
		return this.numDocuBorrador;
	}

	public void setNumDocuBorrador(String numDocuBorrador) {
		this.numDocuBorrador = numDocuBorrador;
	}

	@Column(name = "T_NUM_DOCU_FIRMADO", length = 150)
	public String getNumDocuFirmado() {
		return this.numDocuFirmado;
	}

	public void setNumDocuFirmado(String numDocuFirmado) {
		this.numDocuFirmado = numDocuFirmado;
	}

	@Column(name = "N_ANIO_FIRMADO", precision = 4, scale = 0)
	public Short getNumAnioFirmado() {
		return this.numAnioFirmado;
	}

	public void setNumAnioFirmado(Short numAnioFirmado) {
		this.numAnioFirmado = numAnioFirmado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_CREACION", length = 7)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FIRMA", length = 7)
	public Date getFechaFirma() {
		return this.fechaFirma;
	}

	public void setFechaFirma(Date fechaFirma) {
		this.fechaFirma = fechaFirma;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_TRAMITACION", length = 7)
	public Date getFechaTramitacion() {
		return this.fechaTramitacion;
	}

	public void setFechaTramitacion(Date fechaTramitacion) {
		this.fechaTramitacion = fechaTramitacion;
	}

	@Column(name = "T_BITACORA", length = 240)
	public String getBitacora() {
		return this.bitacora;
	}

	public void setBitacora(String bitacora) {
		this.bitacora = bitacora;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@Column(name = "V_VIGENCIA", length = 1)
	public String getVigencia() {
		return vigencia;
	}

	public void setVigencia(String vigencia) {
		this.vigencia = vigencia;
	}

	@Column(name = "C_USUARIO_ASIGN", length = 50)
	public String getCodUsuarioAsign() {
		return this.codUsuarioAsign;
	}

	public void setCodUsuarioAsign(String codUsuarioAsign) {
		this.codUsuarioAsign = codUsuarioAsign;
	}

	@Column(name = "C_USU_ASIGN_ENV", length = 50)
	public String getCodUsuarioAsignEnv() {
		return codUsuarioAsignEnv;
	}

	public void setCodUsuarioAsignEnv(String codUsuarioAsignEnv) {
		this.codUsuarioAsignEnv = codUsuarioAsignEnv;
	}

	@Column(name = "C_USUARIO_ASIGN_2", length = 50)
	public String getCodUsuarioAsign2() {
		return codUsuarioAsign2;
	}

	public void setCodUsuarioAsign2(String codUsuarioAsign2) {
		this.codUsuarioAsign2 = codUsuarioAsign2;
	}

	@Column(name = "L_COMPLETO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getCompleto() {
		return this.completo;
	}

	public void setCompleto(Boolean completo) {
		this.completo = completo;
	}
	
	@Column(name = "L_VISAR_SUB_MIN", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getVisarSubsecretYMinistro() {
		return visarSubsecretYMinistro;
	}

	public void setVisarSubsecretYMinistro(Boolean visarSubsecretYMinistro) {
		this.visarSubsecretYMinistro = visarSubsecretYMinistro;
	}

	@Column(name = "T_MOTIVO_RECHA_SUB", length = 1000)
	public String getMotivoRechazoSubsecOMinis() {
		return motivoRechazoSubsecOMinis;
	}

	public void setMotivoRechazoSubsecOMinis(String motivoRechazoSubsecOMinis) {
		this.motivoRechazoSubsecOMinis = motivoRechazoSubsecOMinis;
	}

	@Column(name = "S_DOCU")
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	@Lob
	@Column(name = "T_CONSIDERANDOS")
	public String getConsiderandos() {
		return this.considerandos;
	}
	
	public void setConsiderandos(String considerandos) {
		this.considerandos = considerandos;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento", cascade = CascadeType.ALL)
	@OrderBy("orden ASC")
	public Set<CasoDocumento> getCasosDocumento() {
		return this.casosDocumento;
	}

	public void setCasosDocumento(Set<CasoDocumento> casoDocumentos) {
		this.casosDocumento = casoDocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento", cascade = CascadeType.ALL)
	public Set<FirmaDoc> getFirmas() {
		return this.firmas;
	}

	public void setFirmas(Set<FirmaDoc> firmaDoces) {
		this.firmas = firmaDoces;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento", cascade = CascadeType.ALL)
	public Set<EstadoDocumento> getEstadosDocumento() {
		return this.estadosDocumento;
	}

	public void setEstadosDocumento(Set<EstadoDocumento> estadoDocumentos) {
		this.estadosDocumento = estadoDocumentos;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento", cascade = CascadeType.ALL)
	public Set<Volcado> getVolcados() {
		return volcados;
	}

	public void setVolcados(Set<Volcado> volcados) {
		this.volcados = volcados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FICH_X_FICH_F")
	public Fichero getFicheroFirmaContralor() {
		return ficheroFirmaContralor;
	}

	public void setFicheroFirmaContralor(Fichero ficheroFirmaContralor) {
		this.ficheroFirmaContralor = ficheroFirmaContralor;
	}
	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FICH_X_FICH_OFI", nullable = true)
	public Fichero getFicheroOficioRepresentacion() {
		return ficheroOficioRepresentacion;
	}

	public void setFicheroOficioRepresentacion(Fichero ficheroOficioRepresentacion) {
		this.ficheroOficioRepresentacion = ficheroOficioRepresentacion;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FICH_X_FICH_REDO", nullable = true)
	public Fichero getFicheroRetirarDocumento() {
		return ficheroRetirarDocumento;
	}

	public void setFicheroRetirarDocumento(Fichero ficheroRetirarDocumento) {
		this.ficheroRetirarDocumento = ficheroRetirarDocumento;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento", cascade = CascadeType.ALL)
	public Set<DocumentoSinEfecto> getDocumentosSinEfectoPadre() {
		return documentosSinEfectoPadre;
	}

	public void setDocumentosSinEfectoPadre(
			Set<DocumentoSinEfecto> documentosSinEfectoPadre) {
		this.documentosSinEfectoPadre = documentosSinEfectoPadre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoSinEfecto", cascade = CascadeType.ALL)
	public Set<DocumentoSinEfecto> getDocumentosSinEfectoHijo() {
		return documentosSinEfectoHijo;
	}

	public void setDocumentosSinEfectoHijo(
			Set<DocumentoSinEfecto> documentosSinEfectoHijo) {
		this.documentosSinEfectoHijo = documentosSinEfectoHijo;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento", cascade = CascadeType.ALL)
	public Set<SubtituloDocumento> getSubtitulosDocumento() {
		return subtitulosDocumento;
	}

	public void setSubtitulosDocumento(Set<SubtituloDocumento> subtitulosDocumento) {
		this.subtitulosDocumento = subtitulosDocumento;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento", cascade = CascadeType.ALL)
	public Set<Comentario> getComentarios() {
		return comentarios;
	}

	public void setComentarios(Set<Comentario> comentarios_) {
		this.comentarios = comentarios_;
	}

	@Column(name = "L_SIN_EFECTO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getSinAfecto() {
		return sinAfecto;
	}

	public void setSinAfecto(Boolean sinAfecto) {
		this.sinAfecto = sinAfecto;
	}
	
	@Column(name = "L_ENV_OTRO_SERV", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getEnvotroserv() {
		return envotroserv;
	}

	public void setEnvotroserv(Boolean envotroserv) {
		this.envotroserv = envotroserv;
	}
	
	@Column(name = "L_FIRVIS_OTRO_SERV", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getFirmVisOtroServ() {
		return firmVisOtroServ;
	}

	public void setFirmVisOtroServ(Boolean firmVisOtroServ) {
		this.firmVisOtroServ = firmVisOtroServ;
	}

	@OneToOne(mappedBy = "documento")
	public OficioRepresenta getOficioRepresentaUnico() {
		return oficioRepresentaUnico;
	}

	public void setOficioRepresentaUnico(OficioRepresenta oficioRepresentaUnico) {
		this.oficioRepresentaUnico = oficioRepresentaUnico;
	}
	
	@Column(name = "S_CODPRESUPUESTARIO", precision = 12, scale = 0)
	public Long getCodSiaperCodPresupuestario() {
		return codSiaperCodPresupuestario;
	}

	public void setCodSiaperCodPresupuestario(Long codSiaperCodPresupuestario) {
		this.codSiaperCodPresupuestario = codSiaperCodPresupuestario;
	}
	
	@Column(name = "D_CODPRESUPUESTARIO", length = 255)
	public String getDescripcionSiaperCodPresupuestario() {
		return descripcionSiaperCodPresupuestario;
	}

	public void setDescripcionSiaperCodPresupuestario(
			String descripcionSiaperCodPresupuestario) {
		this.descripcionSiaperCodPresupuestario = descripcionSiaperCodPresupuestario;
	}
	
	@Column(name = "L_REV_REPRESENTACION", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isRevisionRepresentacion() {
		return revisionRepresentacion;
	}

	public void setRevisionRepresentacion(boolean revisionRepresentacion) {
		this.revisionRepresentacion = revisionRepresentacion;
	}
	
	@Column(name = "C_RES_TOMARA_AUTOMATICA", length = 1)
	public String getResultadoTomaRaAutomatica() {
		return resultadoTomaRaAutomatica;
	}

	public void setResultadoTomaRaAutomatica(String resultadoTomaRaAutomatica) {
		this.resultadoTomaRaAutomatica = resultadoTomaRaAutomatica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIVI_X_DIVI", nullable = true)
	public Division getDivision() {
		return division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}
    @Transient
    public Division getDivisionRepresentado() {
        return divisionRepresentado;
    }
    public void setDivisionRepresentado(Division divisionRepresentado) {
        this.divisionRepresentado = divisionRepresentado;
    }

	@OneToMany(mappedBy = "documento", cascade = CascadeType.ALL)
	public Set<Firmas> getFirmasUnico() {
		if (this.firmasUnico == null) {
			return new HashSet<Firmas>();
		}
		return firmasUnico;
	}

	public void setFirmasUnico(Set<Firmas> firmasUnico) {
		this.firmasUnico = firmasUnico;
	}
	
	@Column(name = "L_CLONADO", length = 1, nullable = false)
	public String getLClonado() {
		return this.lClonado;
	}

	public void setLClonado(String LClonado) {
		this.lClonado = LClonado;
	}
	
	/**
	 * @return the plantillaResolucion
	 */
	@Column(name = "T_PLANTILLA_RESOLUCION", length = 500)
	public String getPlantillaResolucion() {
		return plantillaResolucion;
	}

	/**
	 * @param plantillaResolucion the plantillaResolucion to set
	 */
	public void setPlantillaResolucion(String plantillaResolucion) {
		this.plantillaResolucion = plantillaResolucion;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Documento))
			return false;
		Documento castOther = (Documento) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		StringBuilder documento = new StringBuilder(); 
		documento.append(numDocuFirmado == null? numDocuBorrador : numDocuFirmado);
		documento.append(" - Materia: ");
		documento.append(materia.getCodCodigo());
		documento.append(", servicio: ");
		documento.append(servicioEmisor.getCodSiaper());
		documento.append(", estado: ");
		documento.append(getEstado());
		return documento.toString();
	}

	@Transient
	public String getEstado() {
		return estado;
	}
	
	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Transient
	public String getCodigoEstado() {
		return codigoEstado;
	}

	public void setCodigoEstado(String codigoEstado) {
		this.codigoEstado = codigoEstado;
	}

	@Transient
	public String getPerfil() {
		return perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	@Transient
	public boolean isSeleccionado() {
		return seleccionado;
	}

	public void setSeleccionado(boolean seleccionado) {
		this.seleccionado = seleccionado;
	}

	@Transient
	public boolean isMostrarEdicion() {
		return mostrarEdicion;
	}

	public void setMostrarEdicion(boolean mostrarEdicion) {
		this.mostrarEdicion = mostrarEdicion;
	}

	@Transient
	public boolean isMostrarGeneracion() {
		return mostrarGeneracion;
	}

	public void setMostrarGeneracion(boolean mostrarGeneracion) {
		this.mostrarGeneracion = mostrarGeneracion;
	}

	@Transient
	public boolean isMostrarEliminacion() {
		return mostrarEliminacion;
	}

	public void setMostrarEliminacion(boolean mostrarEliminacion) {
		this.mostrarEliminacion = mostrarEliminacion;
	}

	@Transient
	public boolean isMostrarEnvioMinistroFe() {
		return mostrarEnvioMinistroFe;
	}

	public void setMostrarEnvioMinistroFe(boolean mostrarEnvioMinistroFe) {
		this.mostrarEnvioMinistroFe = mostrarEnvioMinistroFe;
	}

	@Transient
	public boolean isMostrarRevisionMinistroFe() {
		return mostrarRevisionMinistroFe;
	}

	public void setMostrarRevisionMinistroFe(boolean mostrarRevisionMinistroFe) {
		this.mostrarRevisionMinistroFe = mostrarRevisionMinistroFe;
	}

	@Transient
	public boolean isMostrarDevolverCreador() {
		return mostrarDevolverCreador;
	}

	public void setMostrarDevolverCreador(boolean mostrarDevolverCreador) {
		this.mostrarDevolverCreador = mostrarDevolverCreador;
	}

	@Transient
	public boolean isMostrarEnvioFirmante() {
		return mostrarEnvioFirmante;
	}

	public void setMostrarEnvioFirmante(boolean mostrarEnvioFirmante) {
		this.mostrarEnvioFirmante = mostrarEnvioFirmante;
	}

	@Transient
	public boolean isMostrarFirma() {
		return mostrarFirma;
	}

	public void setMostrarFirma(boolean mostrarFirma) {
		this.mostrarFirma = mostrarFirma;
	}

	@Transient
	public boolean isMostrarDevolverMinistroFe() {
		return mostrarDevolverMinistroFe;
	}

	public void setMostrarDevolverMinistroFe(boolean mostrarDevolverMinistroFe) {
		this.mostrarDevolverMinistroFe = mostrarDevolverMinistroFe;
	}	

	@Transient
	public boolean isMostrarTomaDeRazon() {
		return mostrarTomaDeRazon;
	}

	public void setMostrarTomaDeRazon(boolean mostrarTomaDeRazon) {
		this.mostrarTomaDeRazon = mostrarTomaDeRazon;
	}

	@Transient
	public boolean isMostrarEnvioTomaRazon() {
		return mostrarEnvioTomaRazon;
	}

	public void setMostrarEnvioTomaRazon(boolean mostrarEnvioTomaRazon) {
		this.mostrarEnvioTomaRazon = mostrarEnvioTomaRazon;
	}

	@Transient
	public boolean isMostrarBitacora() {
		return mostrarBitacora;
	}

	public void setMostrarBitacora(boolean mostrarBitacora) {
		this.mostrarBitacora = mostrarBitacora;
	}

	@Transient
	public boolean isMostrarErrores() {
		return mostrarErrores;
	}

	public void setMostrarErrores(boolean mostrarErrores) {
		this.mostrarErrores = mostrarErrores;
	}

	@Transient
	public boolean isMostrarAnalistaWarnings() {
		return mostrarAnalistaWarnings;
	}

	public void setMostrarAnalistaWarnings(boolean mostrarAnalisisWarningsAnalista) {
		this.mostrarAnalistaWarnings = mostrarAnalisisWarningsAnalista;
	}
	
	@Transient
	public boolean isMostrarJefeWarnings() {
		return mostrarJefeWarnings;
	}
	
	public void setMostrarJefeWarnings(boolean mostrarJefeWarnings) {
		this.mostrarJefeWarnings = mostrarJefeWarnings;
	}

	@Transient
	public boolean isMostrarDeclaracionAntecedentes() {
		return mostrarDeclaracionAntecedentes;
	}

	public void setMostrarDeclaracionAntecedentes(
			boolean mostrarDeclaracionAntecedentes) {
		this.mostrarDeclaracionAntecedentes = mostrarDeclaracionAntecedentes;
	}

	@Transient
	public Servicio getContraloriaEmisora() {
		return contraloriaEmisora;
	}

	public void setContraloriaEmisora(Servicio contraloriaEmisora) {
		this.contraloriaEmisora = contraloriaEmisora;
	}

	@Transient
	public String getTipoContraloria() {
		return tipoContraloria;
	}

	public void setTipoContraloria(String tipoContraloria) {
		this.tipoContraloria = tipoContraloria;
	}
	
	@Transient
	public String getConsiderando() {
		return considerando;
	}

	public void setConsiderando(String considerando) {
		this.considerando = considerando;
	}
	
	
	@Transient
	public String getServicioEmisorString() {
		return servicioEmisorString;
	}

	public void setServicioEmisorString(String servicioEmisorString) {
		this.servicioEmisorString = servicioEmisorString;
	}

	@Transient
	public String getFechaEmisionString() {
		return fechaEmisionString;
	}

	public void setFechaEmisionString(String fechaEmisionString) {
		this.fechaEmisionString = fechaEmisionString;
	}
	
	@Transient
	public String getNumeroOficio() {
		return numeroOficio;
	}

	public void setNumeroOficio(String numeroOficio) {
		this.numeroOficio = numeroOficio;
	}
	
	@Transient
	public String getMembreteOficio() {
		return membreteOficio;
	}

	public void setMembreteOficio(String membreteOficio) {
		this.membreteOficio = membreteOficio;
	}

	@Transient
	public String getDetalleOficio() {
		return detalleOficio;
	}

	public void setDetalleOficio(String detalleOficio) {
		this.detalleOficio = detalleOficio;
	}	
	
	@Transient
	public List<CasoDocumento> getCasosDocumento2() {
		return casosDocumento2;
	}

	public void setCasosDocumento2(List<CasoDocumento> casosDocumento2) {
		this.casosDocumento2 = casosDocumento2;
	}

	@Override
	public Documento clone() {
		try {
			return (Documento) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	@Transient
	public List<Ley> getAtomosVistos() {
		return atomosVistos;
	}

	public void setAtomosVistos(List<Ley> atomosVistos) {
		this.atomosVistos = atomosVistos;
	}
	
	@Transient
	public List<Ley> getAtomosVistosSinEfecto() {
		return atomosVistosSinEfecto;
	}

	public void setAtomosVistosSinEfecto(List<Ley> atomosVistosSinEfecto) {
		this.atomosVistosSinEfecto = atomosVistosSinEfecto;
	}

	@Transient
	public String getUsuarioPreview() {
		return usuarioPreview;
	}

	public void setUsuarioPreview(String usuarioPreview) {
		this.usuarioPreview = usuarioPreview;
	}
// TODO: preview de la materia 15	
	@Transient
	public String getNaturalezaCargo() {
		return naturalezaCargo;
	}

	@Transient
	public void setNaturalezaCargo(Dotacion dot) {
		Naturaleza n = null;
		if (dot != null && (n=dot.getNaturaleza())!= null)
			this.naturalezaCargo = n.getDescripcion();
	}

	@Transient
	public String getNaturalezaCargo2() {
		return naturalezaCargo;
	}
///////////////////////////////////	
	@Transient
	public String getNumDocuFirmado2() {
		return numDocuFirmado;
	}
	
	@Transient
	public String getTipoContratoCt(){
		return tipoContratoCt;
	}

	public void setTipoContratoCt(String tcct){
		this.tipoContratoCt = tcct;
	}

	@Transient
	public boolean isMostrarXMLFirma() {
		return mostrarXMLFirma;
	}

	public void setMostrarXMLFirma(boolean mostrarXMLFirma) {
		this.mostrarXMLFirma = mostrarXMLFirma;
	}

	@Transient
	public boolean isMostrarEnviarVisacionDoc() {
		return mostrarEnviarVisacionDoc;
	}

	public void setMostrarEnviarVisacionDoc(boolean mostrarEnviarVisacionDoc) {
		this.mostrarEnviarVisacionDoc = mostrarEnviarVisacionDoc;
	}

	@Transient
	public boolean isMostrarVisacionDoc() {
		return mostrarVisacionDoc;
	}

	public void setMostrarVisacionDoc(boolean mostrarVisacionDoc) {
		this.mostrarVisacionDoc = mostrarVisacionDoc;
	}
	
	@Transient
	public String getCausalCeseArt160() {
		return causalCeseArt160;
	}

	public void setCausalCeseArt160(String causalCeseArt160) {
		this.causalCeseArt160 = causalCeseArt160;
	}
	
	@Transient
	public void setListaBeneficios(String listaBeneficios) {
		this.listaBeneficios = listaBeneficios;
	}
	
	@Transient
	public String getListaBeneficios() {
		return listaBeneficios;
	}
	
	@Transient
	public String getFechaDesde() {
		return fechaDesde;
	}

	public void setFechaDesde(String fechaDesde) {
		this.fechaDesde = fechaDesde;
	}
	
	@Transient
	public String getFechaDesdeSinEfectoPreview() {
		return fechaDesdeSinEfectoPreview;
	}

	public void setFechaDesdeSinEfectoPreview(String fechaDesdeSinEfectoPreview) {
		this.fechaDesdeSinEfectoPreview = fechaDesdeSinEfectoPreview;
	}

	@Transient
	public boolean isFirmaContralor() {
		return firmaContralor;
	}

	public void setFirmaContralor(boolean firmaContralor) {
		this.firmaContralor = firmaContralor;
	}
	
	@Transient
	public boolean isTieneOficioPDF() {
		return tieneOficioPDF;
	}

	public void setTieneOficioPDF(boolean tieneOficioPDF) {
		this.tieneOficioPDF = tieneOficioPDF;
	}

	@Transient
	public String getSubtituloItemPreview() {
		return subtituloItemPreview;
	}

	public void setSubtituloItemPreview(String subtituloItemPreview) {
		this.subtituloItemPreview = subtituloItemPreview;
	}
	
	@Transient
	public String getAcogeBeneficios() {
		return acogeBeneficios;
	}

	public void setAcogeBeneficios(String acogeBeneficios) {
		this.acogeBeneficios = acogeBeneficios;
	}

	@Transient
	public String getLineaFinalPreview() {
		return lineaFinalPreview;
	}

	public void setLineaFinalPreview(String lineaFinalPreview) {
		this.lineaFinalPreview = lineaFinalPreview;
	}

	@Transient
	public String getConservaCargoPreview() {
		return conservaCargoPreview;
	}

	public void setConservaCargoPreview(String conservaCargoPreview) {
		this.conservaCargoPreview = conservaCargoPreview;
	}

	@Transient
	public String getNumDocuFirmadoSinEfectoPreview() {
		return numDocuFirmadoSinEfectoPreview;
	}

	public void setNumDocuFirmadoSinEfectoPreview(
			String numDocuFirmadoSinEfectoPreview) {
		this.numDocuFirmadoSinEfectoPreview = numDocuFirmadoSinEfectoPreview;
	}

	@Transient
	public boolean isOtroServicio() {
		return otroServicio;
	}

	public void setOtroServicio(boolean otroServicio) {
		this.otroServicio = otroServicio;
	}

	@Transient
	public boolean isOtraDivision() {
		return otraDivision;
	}

	public void setOtraDivision(boolean otraDivision) {
		this.otraDivision = otraDivision;
	}

	@Transient
	public boolean isCertificable() {
		return certificable;
	}

	public void setCertificable(boolean certificable) {
		this.certificable = certificable;
	}

	@Transient
	public boolean isMostrarReasignarFirmante() {
		return mostrarReasignarFirmante;
	}

	public void setMostrarReasignarFirmante(boolean mostrarReasignarFirmante) {
		this.mostrarReasignarFirmante = mostrarReasignarFirmante;
	}

	@Transient
	public boolean isMostrarReasignarVisador() {
		return mostrarReasignarVisador;
	}

	public void setMostrarReasignarVisador(boolean mostrarReasignarVisador) {
		this.mostrarReasignarVisador = mostrarReasignarVisador;
	}

	@Transient
	public boolean isMostrarOpcionesRechazoFirma() {
		return mostrarOpcionesRechazoFirma;
	}

	public void setMostrarOpcionesRechazoFirma(boolean mostrarOpcionesRechazoFirma) {
		this.mostrarOpcionesRechazoFirma = mostrarOpcionesRechazoFirma;
	}
	
	@Transient
	public boolean isPerteneceRegion() {
		return perteneceRegion;
	}

	public void setPerteneceRegion(boolean perteneceRegion) {
		this.perteneceRegion = perteneceRegion;
	}

//	@Transient
//	public List<GeneracionDocumentos.SiaPreview> getSubtituloItemAsignacionPreview() {
//		return subtituloItemAsignacionPreview;
//	}

//	public void setSubtituloItemAsignacionPreview(
//			List<GeneracionDocumentos.SiaPreview> subtituloItemAsignacionPreview) {
//		this.subtituloItemAsignacionPreview = subtituloItemAsignacionPreview;
//	}
	
	@Transient
	public boolean isEnviadoParaAnular() {
		return enviadoParaAnular;
	}

	public void setEnviadoParaAnular(boolean enviadoParaAnular) {
		this.enviadoParaAnular = enviadoParaAnular;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_ENVIO_ESTUDIO", length = 7)
	public Date getFechaEnvioEstudio() {
		return fechaEnvioEstudio;
	}

	public void setFechaEnvioEstudio(Date fechaEnvioEstudio) {
		this.fechaEnvioEstudio = fechaEnvioEstudio;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_ENVIO_ANALISTA", length = 7)
	public Date getFechaEnvioAnalista() {
		return fechaEnvioAnalista;
	}
	
	public void setFechaEnvioAnalista(Date fechaEnvioAnalista) {
		this.fechaEnvioAnalista = fechaEnvioAnalista;
	}

	/**
	 * @return the estadoExterno
	 */
	@Transient
	public String getEstadoExterno() {
		return estadoExterno;
	}

	/**
	 * @param estadoExterno the estadoExterno to set
	 */
	public void setEstadoExterno(String estadoExterno) {
		this.estadoExterno = estadoExterno;
	}

	/**
	 * @return the perfilExterno
	 */
	@Transient
	public String getPerfilExterno() {
		return perfilExterno;
	}

	/**
	 * @param perfilExterno the perfilExterno to set
	 */
	public void setPerfilExterno(String perfilExterno) {
		this.perfilExterno = perfilExterno;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "FICH_X_FICH_I")
	public Fichero getFicheroImagenServicio() {
		return ficheroImagenServicio;
	}

	public void setFicheroImagenServicio(Fichero ficheroImagenServicio) {
		this.ficheroImagenServicio = ficheroImagenServicio;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento", cascade = CascadeType.ALL)
	public Set<DocumentoModificaRectifica> getDocumentosModificaRectificaPadre() {
		return documentosModificaRectificaPadre;
	}

	public void setDocumentosModificaRectificaPadre(
			Set<DocumentoModificaRectifica> documentosModificaRectificaPadre) {
		this.documentosModificaRectificaPadre = documentosModificaRectificaPadre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoModificado", cascade = CascadeType.ALL)
	public Set<DocumentoModificaRectifica> getDocumentosModificaRectificaHijo() {
		return documentosModificaRectificaHijo;
	}

	public void setDocumentosModificaRectificaHijo(
			Set<DocumentoModificaRectifica> documentosModificaRectificaHijo) {
		this.documentosModificaRectificaHijo = documentosModificaRectificaHijo;
	}

	/**
	 * @return the modificado
	 */
	@Column(name = "L_MODIFICADO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isModificado() {
		return modificado;
	}

	/**
	 * @param modificado the modificado to set
	 */
	public void setModificado(boolean modificado) {
		this.modificado = modificado;
	}

	/**
	 * @return the modificarRectificar
	 */
	@Column(name = "L_MODIFICA", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isModificarRectificar() {
		return modificarRectificar;
	}

	/**
	 * @param modificarRectificar the modificarRectificar to set
	 */
	public void setModificarRectificar(boolean modificarRectificar) {
		this.modificarRectificar = modificarRectificar;
	}

	/**
	 * @return the documentoModificado
	 */
	@Transient
	public Documento getDocumentoModificado() {
		return documentoModificado;
	}

	/**
	 * @param documentoModificado the documentoModificado to set
	 */
	public void setDocumentoModificado(Documento documentoModificado) {
		this.documentoModificado = documentoModificado;
	}

	/**
	 * @return the materiaModifica
	 */
	@Transient
	public Materia getMateriaModifica() {
		return materiaModifica;
	}

	/**
	 * @param materiaModifica the materiaModifica to set
	 */
	public void setMateriaModifica(Materia materiaModifica) {
		this.materiaModifica = materiaModifica;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV_C")
	public Servicio getContraloriaAsignada() {
		return this.contraloriaAsignada;
	}

	public void setContraloriaAsignada(Servicio contraloriaAsignada) {
		this.contraloriaAsignada = contraloriaAsignada;
	}
	
	/**
	 * @return the Diario oficial
	 */
	@Column(name = "L_DIARIO_OFICIAL", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isEnviadoDiario() {
		return enviadoDiario;
	}
	
	/**
	 * @param the  Diario oficial
	 */
	public void setEnviadoDiario(boolean enviadoDiario) {
		this.enviadoDiario = enviadoDiario;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento", cascade = CascadeType.ALL)
	public Set<EstadoDiarioDoc> getEstadoDiarioDoc() {
		return estadoDiarioDoc;
	}

	public void setEstadoDiarioDoc(Set<EstadoDiarioDoc> estadoDiarioDoc) {
		this.estadoDiarioDoc = estadoDiarioDoc;
	}
	
	@Column(name = "T_MOTIVO_NO_PUBLICA", length = 4000)
	public String getComentarioDiario() {
		return comentarioDiario;
	}

	public void setComentarioDiario(String comentarioDiario) {
		this.comentarioDiario = comentarioDiario;
	}
	
	@Column(name = "T_EST_DIARIO", length = 20)
	public String getCodigoDiario() {
		return codigoDiario;
	}

	public void setCodigoDiario(String codigoDiario) {
		this.codigoDiario = codigoDiario;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV_U")
	public Servicio getServicioCreador() {
		return this.servicioCreador;
	}

	public void setServicioCreador(Servicio servicioCreador) {
		this.servicioCreador = servicioCreador;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV_O")
	public Servicio getServicioEmisorOriginal() {
		return this.servicioEmisorOriginal;
	}

	public void setServicioEmisorOriginal(Servicio servicioEmisorOriginal) {
		this.servicioEmisorOriginal = servicioEmisorOriginal;
	}
	
	@Column(name = "C_USUARIO_CREA", length = 50)
	public String getCodUsuarioCreador() {
		return this.codUsuarioCreador;
	}

	public void setCodUsuarioCreador(String codUsuarioCreador) {
		this.codUsuarioCreador = codUsuarioCreador;
	}
	
	@Transient
	public boolean isHasOficioPdf() {
		return hasOficioPdf;
	}

	public void setHasOficioPdf(boolean hasOficioPdf) {
		this.hasOficioPdf = hasOficioPdf;
	}

	@Transient
	public boolean isEsSupervisorCGR() {
		return esSupervisorCGR;
	}

	public void setEsSupervisorCGR(boolean esSupervisorCGR) {
		this.esSupervisorCGR = esSupervisorCGR;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESTA_X_ESTA", nullable = false)
	public Estado getEstadoDocumento() {
		return this.estadoDocumento;
	}
	public void setEstadoDocumento(Estado estadoDocumento) {
		this.estadoDocumento = estadoDocumento;
	}
}
