package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 05-mar-2012 9:06:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * DocumentoRespaldo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_DOCUMENTOS_RESPALDO")
public class DocumentoRespaldo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2864839594669856476L;
	private Long id;
	private Date version;
	private String codUsuarioBloq;
	private FuncSuplidoReemplazado funcSuplidoReemplazado;
	private ActoRespaldo actoRespaldo;
	private String descTipoDocRespaldo;
	private Long tipoDocRespaldo;
	private Long numDocRespaldoSiaper;
	private String descSubmateriaDocRespaldo;
	private String submateriaDocRespaldo;
	private String numDocRespaldo;
	private Date fechaDesde;
	private Date fechaHasta;
	private Set<PeriodoDocRespaldo> periodoDocRespaldos = new HashSet<PeriodoDocRespaldo>(0);

	public DocumentoRespaldo() {
	}

	public DocumentoRespaldo(FuncSuplidoReemplazado funcSuplidoReemplazado,
			ActoRespaldo actoRespaldo, String descTipoDocRespaldo,
			Long tipoDocRespaldo, String descSubmateriaDocRespaldo,
			String submateriaDocRespaldo, String numDocRespaldo,
			Date fechaDesde, Date fechaHasta,
			Set<PeriodoDocRespaldo> periodoDocRespaldos) {
		this.funcSuplidoReemplazado = funcSuplidoReemplazado;
		this.actoRespaldo = actoRespaldo;
		this.descTipoDocRespaldo = descTipoDocRespaldo;
		this.tipoDocRespaldo = tipoDocRespaldo;
		this.descSubmateriaDocRespaldo = descSubmateriaDocRespaldo;
		this.submateriaDocRespaldo = submateriaDocRespaldo;
		this.numDocRespaldo = numDocRespaldo;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.periodoDocRespaldos = periodoDocRespaldos;
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_DORE_X_DORE")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_DORE", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUSR_X_FUSR")
	public FuncSuplidoReemplazado getFuncSuplidoReemplazado() {
		return this.funcSuplidoReemplazado;
	}

	public void setFuncSuplidoReemplazado(
			FuncSuplidoReemplazado funcSuplidoReemplazado) {
		this.funcSuplidoReemplazado = funcSuplidoReemplazado;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "ACRE_X_ACRE")
	public ActoRespaldo getActoRespaldo() {
		return this.actoRespaldo;
	}

	public void setActoRespaldo(ActoRespaldo actoRespaldo) {
		this.actoRespaldo = actoRespaldo;
	}

	@Column(name = "D_TIPO_DOC_RESPALDO", length = 255)
	public String getDescTipoDocRespaldo() {
		return this.descTipoDocRespaldo;
	}

	public void setDescTipoDocRespaldo(String descTipoDocRespaldo) {
		this.descTipoDocRespaldo = descTipoDocRespaldo;
	}

	@Column(name = "S_TIPO_DOC_RESPALDO", length = 12)
	public Long getTipoDocRespaldo() {
		return this.tipoDocRespaldo;
	}

	public void setTipoDocRespaldo(Long tipoDocRespaldo) {
		this.tipoDocRespaldo = tipoDocRespaldo;
	}

	@Column(name = "D_SUBMATERIA_DOC_RESPALDO", length = 240)
	public String getDescSubmateriaDocRespaldo() {
		return this.descSubmateriaDocRespaldo;
	}

	public void setDescSubmateriaDocRespaldo(String descSubmateriaDocRespaldo) {
		this.descSubmateriaDocRespaldo = descSubmateriaDocRespaldo;
	}

	@Column(name = "S_SUBMATERIA_DOC_RESPALDO", length = 10)
	public String getSubmateriaDocRespaldo() {
		return this.submateriaDocRespaldo;
	}

	public void setSubmateriaDocRespaldo(String submateriaDocRespaldo) {
		this.submateriaDocRespaldo = submateriaDocRespaldo;
	}

	@Column(name = "T_NUM_DOC_RESPALDO", length = 255)
	public String getNumDocRespaldo() {
		return this.numDocRespaldo;
	}

	public void setNumDocRespaldo(String numDocRespaldo) {
		this.numDocRespaldo = numDocRespaldo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_DESDE", length = 7)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_HASTA", length = 7)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoRespaldo", cascade = CascadeType.ALL)
	public Set<PeriodoDocRespaldo> getPeriodoDocRespaldos() {
		return this.periodoDocRespaldos;
	}

	public void setPeriodoDocRespaldos(
			Set<PeriodoDocRespaldo> periodoDocRespaldos) {
		this.periodoDocRespaldos = periodoDocRespaldos;
	}
	
	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}
	
	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@Column(name = "NUM_DOC_RESPALDO_SIAPER", length = 12)
	public Long getNumDocRespaldoSiaper() {
		return numDocRespaldoSiaper;
	}

	public void setNumDocRespaldoSiaper(Long numDocRespaldoSiaper) {
		this.numDocRespaldoSiaper = numDocRespaldoSiaper;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		} else {
			if (obj instanceof DocumentoRespaldo) {
				DocumentoRespaldo docResp = (DocumentoRespaldo) obj;
				if (docResp.getId() != null) {
					if (docResp.getId().equals(this.getId())) {
						return true;
					} else {
						return false;
					}
				} else {
					return false;
				}
			} else {
				return false;
			}
		}
	}
}