package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 18-oct-2011 11:46:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;
//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

//Generated 09-feb-2012 17:49:44 by Hibernate Tools 3.4.0.CR1

//import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;
//import jakarta.persistence.Column;
//import jakarta.persistence.Entity;
//import jakarta.persistence.FetchType;
//import jakarta.persistence.GeneratedValue;
//import jakarta.persistence.Id;
//import jakarta.persistence.JoinColumn;
//import jakarta.persistence.ManyToOne;
//import jakarta.persistence.OneToMany;
//import jakarta.persistence.SequenceGenerator;
//import jakarta.persistence.Table;
//import jakarta.persistence.Temporal;
//import jakarta.persistence.TemporalType;
//import jakarta.persistence.Version;
//import org.hibernate.annotations.Type;
//import org.hibernate.envers.Audited;

/**
 * Dotacion generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_REG_PLANTA_SERV")
public class Dotacion implements java.io.Serializable, Cloneable, Comparable<Dotacion> {

	private Long id;
	private Date version;
	private Naturaleza naturaleza;
	private TipoHora tipoHora;
	private Cargo cargo;
	private Remuneracion remuneracionGrado;
	private PlantaServicio plantaServicio;
	private PlantaCargo plantaCargo;
	private Remuneracion remuneracionHoras;
	private Grado grado;
	private Servicio servicio;
	private Categoria categoria;
	private Especialidad especialidad;
	private Nivel nivel;
	private long numOrden;
	private Long numHoras;
	private Long numCargos;
	private Boolean art55bis;
	private Boolean activo;
	private String codUsuarioBloq;
	private String firmantes;
	private Boolean bolsaHoras;
	private Set<Subcargo> subcargos = new HashSet<Subcargo>(0);
	private Set<MateriaDotacion> materiasDotacion = new HashSet<MateriaDotacion>(0);
	private Set<CasoDocumento> casosDocumento = new HashSet<CasoDocumento>(0);
	private Set<CaminoTraEsp> caminosTraEsp = new HashSet<CaminoTraEsp>(0);
	
	
	// Transient attributes
	private boolean seleccionadoPreviamente;
	private String msnss="";
	private Subcargo subcargoCamino;
	private int ordenCamino;
	

	


	
	
	public Dotacion() {
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_RPLS_X_RPLS")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_RPLS", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NATU_X_NATU", nullable = false)
	public Naturaleza getNaturaleza() {
		return this.naturaleza;
	}

	public void setNaturaleza(Naturaleza naturaleza) {
		this.naturaleza = naturaleza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIHO_X_TIHO")
	public TipoHora getTipoHora() {
		return this.tipoHora;
	}

	public void setTipoHora(TipoHora tipoHora) {
		this.tipoHora = tipoHora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARG_X_CARG", nullable = false)
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REMU_X_REMU")
	public Remuneracion getRemuneracionGrado() {
		return remuneracionGrado;
	}
	
	public void setRemuneracionGrado(Remuneracion remuneracionGrado) {
		this.remuneracionGrado = remuneracionGrado;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLSE_X_PLSE", nullable = false)
	public PlantaServicio getPlantaServicio() {
		return this.plantaServicio;
	}


	public void setPlantaServicio(PlantaServicio plantaServicio) {
		this.plantaServicio = plantaServicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLCA_X_PLCA", nullable = false)
	public PlantaCargo getPlantaCargo() {
		return this.plantaCargo;
	}

	public void setPlantaCargo(PlantaCargo plantaCargo) {
		this.plantaCargo = plantaCargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REMU_X_REMU_H")
	public Remuneracion getRemuneracionHoras() {
		return remuneracionHoras;
	}

	public void setRemuneracionHoras(Remuneracion remuneracionHoras) {
		this.remuneracionHoras = remuneracionHoras;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRAD_X_GRAD")
	public Grado getGrado() {
		return this.grado;
	}

	public void setGrado(Grado grado) {
		this.grado = grado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV", nullable = false)
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATE_X_CATE")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESPE_X_ESPE")
	public Especialidad getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(Especialidad especialidad) {
		this.especialidad = especialidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NIVE_X_NIVE")
	public Nivel getNivel() {
		return this.nivel;
	}

	public void setNivel(Nivel nivel) {
		this.nivel = nivel;
	}

	@Column(name = "N_ORDEN", nullable = false, precision = 10, scale = 0)
	public long getNumOrden() {
		return this.numOrden;
	}

	public void setNumOrden(long numOrden) {
		this.numOrden = numOrden;
	}

	@Column(name = "N_HORAS", precision = 10, scale = 0)
	public Long getNumHoras() {
		return this.numHoras;
	}

	public void setNumHoras(Long numHoras) {
		this.numHoras = numHoras;
	}

	@Column(name = "N_CARGOS", precision = 10, scale = 0)
	public Long getNumCargos() {
		return this.numCargos;
	}

	public void setNumCargos(Long numCargos) {
		this.numCargos = numCargos;
	}

	@Column(name = "L_ART_55BIS", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getArt55bis() {
		return this.art55bis;
	}

	public void setArt55bis(Boolean art55bis) {
		this.art55bis = art55bis;
	}

	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "T_FIRMANTES", length = 3000)
	public String getFirmantes() {
		return this.firmantes;
	}

	public void setFirmantes(String firmantes) {
		this.firmantes = firmantes;
	}

	@Column(name = "L_BOLSA_HORAS", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getBolsaHoras() {
		return this.bolsaHoras;
	}

	public void setBolsaHoras(Boolean bolsaHoras) {
		this.bolsaHoras = bolsaHoras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dotacion")
	public Set<Subcargo> getSubcargos() {
		return this.subcargos;
	}

	public void setSubcargos(Set<Subcargo> subcargos) {
		this.subcargos = subcargos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dotacion")
	public Set<MateriaDotacion> getMateriasDotacion() {
		return this.materiasDotacion;
	}

	public void setMateriasDotacion(Set<MateriaDotacion> materiasDotacion) {
		this.materiasDotacion = materiasDotacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dotacion")
	public Set<CasoDocumento> getCasosDocumento() {
		return this.casosDocumento;
	}
	public void setCasosDocumento(Set<CasoDocumento> casosDocumento) {
		this.casosDocumento = casosDocumento;
	}

	@Transient
	public boolean isSeleccionadoPreviamente() {
		return seleccionadoPreviamente;
	}

	public void setSeleccionadoPreviamente(boolean seleccionadoPreviamente) {
		this.seleccionadoPreviamente = seleccionadoPreviamente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dotacion")
	public Set<CaminoTraEsp> getCaminosTraEsp() {
		return caminosTraEsp;
	}

	public void setCaminosTraEsp(Set<CaminoTraEsp> caminosTraEsp) {
		this.caminosTraEsp = caminosTraEsp;
	}

	public int compareTo(Dotacion dotacion) {
		return (int) (this.numOrden - dotacion.numOrden);
	}
	
	public Dotacion clone() {
		try {
			return (Dotacion) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	@Transient
	public String boolToString (boolean b)
	{
		if (b)
			return "Sí";
		else
			return "No";
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Dotacion))
			return false;
		Dotacion castOther = (Dotacion) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		StringBuilder dotacion = new StringBuilder();
		dotacion.append("Servicio: ");
		dotacion.append(servicio.getCodSiaper());
		dotacion.append(" - ");
		dotacion.append(plantaServicio.getPlanta().getCodSiaper());
		dotacion.append(": ");
		dotacion.append(cargo.getCodSiaper());
		if (grado != null) {
			dotacion.append(" - ");
			dotacion.append(grado.getCodSiaper());
		}
		if (categoria != null) {
			dotacion.append(" - ");
			dotacion.append(categoria.getCodSiaper());
		}
		return dotacion.toString();
	}
	
	@Transient
	public String getMsnss(){
		return msnss;
	}

	public void setMsnss(String msnss){
		this.msnss = msnss;
	}

	@Transient
	public Subcargo getSubcargoCamino() {
		return subcargoCamino;
	}

	public void setSubcargoCamino(Subcargo subcargoCamino) {
		this.subcargoCamino = subcargoCamino;
	}

	@Transient
	public int getOrdenCamino() {
		return ordenCamino;
	}

	public void setOrdenCamino(int ordenCamino) {
		this.ordenCamino = ordenCamino;
	}
}
