package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 09-mar-2012 9:24:55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * EnsenianzaMedia generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ENSENIANZA_MEDIA", uniqueConstraints = @UniqueConstraint(columnNames = "S_ENME"))
public class EnsenianzaMedia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7223561141279653862L;
	private String id;
	private Date version;
	private Long codSiaper;
	private String nombre;
	private String descripcion;
	private String codUsuarioBloq;
	private boolean activo;
	private Set<AntecedenteEducacional> antecedenteEducacionales = new HashSet<AntecedenteEducacional>(0);
	private Set<MineducEnsenanzaMedia> mineduc = new HashSet<MineducEnsenanzaMedia>(0);

	public EnsenianzaMedia() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ENME_X_ENME")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ENME", unique = true, nullable = false, precision = 10, scale = 0)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "S_ENME", precision = 12, scale = 0)
	public Long getCodSiaper() {
		return this.codSiaper;
	}

	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}

	@Column(name = "C_ENME", length = 10, nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column(name = "D_ENME", length=255, nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 30)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ensenianzaMedia")
	public Set<AntecedenteEducacional> getAntecedenteEducacionales() {
		return this.antecedenteEducacionales;
	}

	public void setAntecedenteEducacionales(
			Set<AntecedenteEducacional> antecedenteEducacionales) {
		this.antecedenteEducacionales = antecedenteEducacionales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ensenanzaMedia")
	public Set<MineducEnsenanzaMedia> getMineduc() {
		return mineduc;
	}

	public void setMineduc(Set<MineducEnsenanzaMedia> mineduc) {
		this.mineduc = mineduc;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnsenianzaMedia))
			return false;
		EnsenianzaMedia castOther = (EnsenianzaMedia) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
}
