package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 03-oct-2011 16:27:55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * EntidadOtorgadora generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ENTIDADES_OTORGADORAS", uniqueConstraints = @UniqueConstraint(columnNames = "C_ENOT"))
public class EntidadOtorgadora implements java.io.Serializable, Comparable<EntidadOtorgadora> {

	private static final long serialVersionUID = -6434695231134527281L;

	private Long id;
	private Date version;
	private String codigo;
	private Long codSiaper;
	private String descripcion;
	private Boolean activo;
	private String codUsuarioBloq;
	private Set<EntidadNivelEducacional> nivelesEducacionales = new HashSet<EntidadNivelEducacional>(0);
	private Set<EntiotorgNivconv> nivelesConvalidacion = new HashSet<EntiotorgNivconv>(0);
	private Set<EntidadTipoEstudio> tiposEstudio = new HashSet<EntidadTipoEstudio>(0);
	private Set<AntecedenteEducacional> antecedentesEducacionales = new HashSet<AntecedenteEducacional>(0);

	public EntidadOtorgadora() {
	}
	
	public EntidadOtorgadora(long id) {
		this.id = id;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ENOT_X_ENOT")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ENOT", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "C_ENOT", unique = true, nullable = false, length = 5)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "D_ENOT", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "L_ACTIVO", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidadOtorgadora")
	public Set<EntidadNivelEducacional> getNivelesEducacionales() {
		return this.nivelesEducacionales;
	}

	public void setNivelesEducacionales(Set<EntidadNivelEducacional> entidadNivelEducacionales) {
		this.nivelesEducacionales = entidadNivelEducacionales;
	}
	
	@Column(name = "S_ENOT", precision = 12, scale = 0)
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidadOtorgadora")
	public Set<EntiotorgNivconv> getNivelesConvalidacion() {
		return this.nivelesConvalidacion;
	}

	public void setNivelesConvalidacion(Set<EntiotorgNivconv> entiotorgNivconves) {
		this.nivelesConvalidacion = entiotorgNivconves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidadOtorgadora")
	public Set<EntidadTipoEstudio> getTiposEstudio() {
		return this.tiposEstudio;
	}

	public void setTiposEstudio(Set<EntidadTipoEstudio> entidadTipoEstudios) {
		this.tiposEstudio = entidadTipoEstudios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidadOtorgadora")
	public Set<AntecedenteEducacional> getAntecedentesEducacionales() {
		return this.antecedentesEducacionales;
	}

	public void setAntecedentesEducacionales(Set<AntecedenteEducacional> antecedenteEducacionales) {
		this.antecedentesEducacionales = antecedenteEducacionales;
	}

	public int compareTo(EntidadOtorgadora entidad) {
		return this.getId().compareTo(entidad.getId());
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EntidadOtorgadora))
			return false;
		EntidadOtorgadora castOther = (EntidadOtorgadora) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion;
	}
	
}
