package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * EntidadNivelEducacional generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ENTIOTORG_X_NIVELEF", uniqueConstraints = @UniqueConstraint(columnNames = { "NIEF_X_NIEF", "ENOT_X_ENOT" }))
public class EntidadNivelEducacional implements java.io.Serializable {

	private static final long serialVersionUID = 5365896932281487123L;

	private Long id;
	private Date version;
	private EntidadOtorgadora entidadOtorgadora;
	private NivelEstudioFormal nivelEstudioFormal;
	private String codUsuarioBloq;

	public EntidadNivelEducacional() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_EONE_X_EONE")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_EONE", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENOT_X_ENOT", nullable = false)
	public EntidadOtorgadora getEntidadOtorgadora() {
		return this.entidadOtorgadora;
	}

	public void setEntidadOtorgadora(EntidadOtorgadora entidadOtorgadora) {
		this.entidadOtorgadora = entidadOtorgadora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NIEF_X_NIEF", nullable = false)
	public NivelEstudioFormal getNivelEstudioFormal() {
		return this.nivelEstudioFormal;
	}

	public void setNivelEstudioFormal(NivelEstudioFormal nivelEstudioFormal) {
		this.nivelEstudioFormal = nivelEstudioFormal;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EntidadNivelEducacional))
			return false;
		EntidadNivelEducacional castOther = (EntidadNivelEducacional) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Entidad: (" + entidadOtorgadora + "), nivel: (" + nivelEstudioFormal + ")";
	}
	
}
