package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 22-sep-2011 11:36:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * Estado generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ESTA_DIARIO_DOCU")
public class EstadoDiarioDoc implements java.io.Serializable {

	private static final long serialVersionUID = -6128531572734924386L;

	private Long id;	
	private Date version;
	private EstadoDiario estadoDiario;	
	private Documento documento;
	private String codUsuarioBloq;
	private Date fechaEntrada;
	private Date fechaSalida;
	private String observaciones;
	private String codUsuarioEnt;
	private String codUsuarioSal;

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_DIDO_X_DIDO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_DIDO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESDI_X_ESDI", nullable = false)
	public EstadoDiario getEstadoDiario() {
		return estadoDiario;
	}

	public void setEstadoDiario(EstadoDiario estadoDiario) {
		this.estadoDiario = estadoDiario;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCU_X_DOCU", nullable = false)
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}


	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_ENTRADA", length = 7)
	public Date getFechaEntrada() {
		return this.fechaEntrada;
	}

	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_SALIDA", length = 7)
	public Date getFechaSalida() {
		return this.fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}

	@Column(name = "T_OBSERVACIONES", length = 3000)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "C_USUARIO_ENT", length = 50)
	public String getCodUsuarioEnt() {
		return this.codUsuarioEnt;
	}

	public void setCodUsuarioEnt(String codUsuarioEnt) {
		this.codUsuarioEnt = codUsuarioEnt;
	}

	@Column(name = "C_USUARIO_SAL", length = 50)
	public String getCodUsuarioSal() {
		return this.codUsuarioSal;
	}

	public void setCodUsuarioSal(String codUsuarioSal) {
		this.codUsuarioSal = codUsuarioSal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstadoDiarioDoc))
			return false;
		EstadoDiarioDoc castOther = (EstadoDiarioDoc) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Estado Diario: (" + estadoDiario + "), documento: (" + documento + ")";
	}

	public int compareTo(EstadoDiarioDoc o) {
		if (o.getFechaSalida().before(fechaSalida)) {
			return -1;
		} else {
			return 1;
		}
	}

}
