package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 27-sep-2011 11:33:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * EstadoDocumento generated by hbm2java
 */
@Entity
@Audited
@AuditTable("TRA_ESTADOS_DOCU_HIST")
@Table(name = "TRA_ESTADOS_DOCUMENTOS")
public class EstadoDocumento implements java.io.Serializable, Comparable<EstadoDocumento> {

	private static final long serialVersionUID = 7076581963567838846L;

	private Long id;
	private Date version;
	private Documento documento;
	private Estado estado;
	private String codUsuarioBloq;
	private Date fechaEntrada;
	private Date fechaSalida;
	private String observaciones;
	private String codUsuarioEnt;
	private String codUsuarioSal;

	public EstadoDocumento() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ESDO_X_ESDO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ESDO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCU_X_DOCU", nullable = false)
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESTA_X_ESTA", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_ENTRADA", length = 7)
	public Date getFechaEntrada() {
		return this.fechaEntrada;
	}

	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_SALIDA", length = 7)
	public Date getFechaSalida() {
		return this.fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}

	@Column(name = "T_OBSERVACIONES", length = 3000)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "C_USUARIO_ENT", length = 50)
	public String getCodUsuarioEnt() {
		return this.codUsuarioEnt;
	}

	public void setCodUsuarioEnt(String codUsuarioEnt) {
		this.codUsuarioEnt = codUsuarioEnt;
	}

	@Column(name = "C_USUARIO_SAL", length = 50)
	public String getCodUsuarioSal() {
		return this.codUsuarioSal;
	}

	public void setCodUsuarioSal(String codUsuarioSal) {
		this.codUsuarioSal = codUsuarioSal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstadoDocumento))
			return false;
		EstadoDocumento castOther = (EstadoDocumento) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Estado: (" + estado + "), documento: (" + documento + ")";
	}

	public int compareTo(EstadoDocumento o) {
		int BEFORE = -1;
		int EQUAL = 0;
		int AFTER = 1;
		if ((this.fechaSalida == null) && (o.getFechaSalida() == null)) {
			return 0;
		}
		if (this.fechaSalida == null) {
			return 1;
		}
		if (o.getFechaSalida() == null) {
			return -1;
		}
		if (o.getFechaSalida().before(this.fechaSalida)) {
			return -1;
		}
		return 1;
	}

}
