package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 22-sep-2011 11:36:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * Estado generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ESTADOS_DIARIO", uniqueConstraints = @UniqueConstraint(columnNames = "C_ESDI"))
public class EstadoDiario implements java.io.Serializable {

	private static final long serialVersionUID = -6128531572734924386L;

	private Long id;	
	private String codigo;
	private String descripcion;
	private Date version;
	private String codUsuarioBloq;

	private Set<EstadoDiarioDoc> estadoDiarioDoc = new HashSet<EstadoDiarioDoc>(0);	

	

	public EstadoDiario() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ESDI_X_ESDI")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ESDI", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "C_ESDI", unique = true, nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "D_ESDI", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
		
	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoDiario")
	public Set<EstadoDiarioDoc> getEstadoDiarioDoc() {
		return estadoDiarioDoc;
	}

	public void setEstadoDiarioDoc(Set<EstadoDiarioDoc> estadoDiarioDoc) {
		this.estadoDiarioDoc = estadoDiarioDoc;
	}
	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstadoDiario))
			return false;
		EstadoDiario castOther = (EstadoDiario) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion;
	}

}
