package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 07-jul-2017 9:24:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * EstCargMasivo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_EST_CARG_MASIVO")
public class EstadoCargaMasiva implements Serializable, Comparable<EstadoCargaMasiva> {

	private static final long serialVersionUID = 5132240464083640203L;
	private Long id;
	private CargaMasiva cargaMasiva;
	private Estado estado;
	private Date version;
	private Date entrada;
	private Date salida;
	private String usuarioEnt;
	private String usuarioSal;

	public EstadoCargaMasiva() {
	}

	public EstadoCargaMasiva(CargaMasiva cargaMasiva, 
						 Estado estado, 
						 Date entrada,
			             Date salida,
			             String usuarioEnt,
			             String usuarioSal) {
		
		this.cargaMasiva = cargaMasiva;
		this.estado = estado;
		this.entrada = entrada;
		this.salida = salida;
		this.usuarioEnt = usuarioEnt;
		this.usuarioSal = usuarioSal;
	}

	public EstadoCargaMasiva(CargaMasiva cargaMasiva,
	                     Estado estado,
	                     Date version,
	                     Date entrada,
	                     Date salida,
	                     String usuarioEnt,
	                     String usuarioSal) {

		this.cargaMasiva = cargaMasiva;
		this.estado = estado;
		this.version = version;
		this.entrada = entrada;
		this.salida = salida;
		this.usuarioEnt = usuarioEnt;
		this.usuarioSal = usuarioSal;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ESCA_X_ESCA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ESCA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAMA_X_CAMA", nullable = false)
	public CargaMasiva getCargaMasiva() {
		return this.cargaMasiva;
	}

	public void setCargaMasiva(CargaMasiva cargaMasiva) {
		this.cargaMasiva = cargaMasiva;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESTA_X_ESTA", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_ENTRADA", length = 7)
	public Date getEntrada() {
		return this.entrada;
	}

	public void setEntrada(Date entrada) {
		this.entrada = entrada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_SALIDA", length = 7)
	public Date getSalida() {
		return this.salida;
	}

	public void setSalida(Date salida) {
		this.salida = salida;
	}

	@Column(name = "C_USUARIO_ENT", length = 50)
	public String getUsuarioEnt() {
		return this.usuarioEnt;
	}

	public void setUsuarioEnt(String usuarioEnt) {
		this.usuarioEnt = usuarioEnt;
	}

	@Column(name = "C_USUARIO_SAL", length = 50)
	public String getUsuarioSal() {
		return this.usuarioSal;
	}

	public void setUsuarioSal(String usuarioSal) {
		this.usuarioSal = usuarioSal;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstadoCargaMasiva))
			return false;
		EstadoCargaMasiva castOther = (EstadoCargaMasiva) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	@Override
	public int compareTo(EstadoCargaMasiva o) {
		if (this.id == null && o.getId() == null) {
			return 0;
		}
		if (this.id == null ) {
			return 1;
		}
		if (o.getId() == null) {
			return -1;
		}
		return o.getId().compareTo(this.id);
	}

}