package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 22-sep-2011 11:36:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.envers.Audited;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;


/**
 * Estado generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_ESTADOS", uniqueConstraints = @UniqueConstraint(columnNames = "C_ESTA"))
public class Estado implements java.io.Serializable {

	private static final long serialVersionUID = -6128531572734924386L;

	private Long id;
	private Date version;
	private String codigo;
	private String descripcion;
	private String descripcionExterna;
	private String codUsuarioBloq;
	private Set<EstadoDocumento> estadoDocumentos = new HashSet<EstadoDocumento>(0);
	private Set<PerfilEstado> perfilesEstado = new HashSet<PerfilEstado>(0);
	private Set<EstadoCargaMasiva> estadosCargaMasiva = new HashSet<EstadoCargaMasiva>(0);


	public Estado() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_ESTA_X_ESTA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_ESTA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "C_ESTA", unique = true, nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "D_ESTA", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "D_ESTA_EXT", nullable = false, length = 150)
	public String getDescripcionExterna() {
		return this.descripcionExterna;
	}

	public void setDescripcionExterna(String descripcionExterna) {
		this.descripcionExterna = descripcionExterna;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<EstadoDocumento> getEstadoDocumentos() {
		return this.estadoDocumentos;
	}

	public void setEstadoDocumentos(Set<EstadoDocumento> estadoDocumentos) {
		this.estadoDocumentos = estadoDocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<PerfilEstado> getPerfilesEstado() {
		return this.perfilesEstado;
	}

	public void setPerfilesEstado(Set<PerfilEstado> perfilEstados) {
		this.perfilesEstado = perfilEstados;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<EstadoCargaMasiva> getEstadosCargaMasiva() {
		return this.estadosCargaMasiva;
	}

	public void setEstadosCargaMasiva(Set<EstadoCargaMasiva> estadosCargaMasiva) {
		this.estadosCargaMasiva = estadosCargaMasiva;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Estado))
			return false;
		Estado castOther = (Estado) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion;
	}

}
