package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 02-nov-2011 16:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * Fichero generated by hbm2java
 */
/**
 * @author antoniojrodriguez
 *
 */
@Entity
@Audited
@Table(name = "TRA_FICHEROS")
public class Fichero implements java.io.Serializable {

	private static final long serialVersionUID = 4233823951762255525L;

	private Long id;
	private Date version;
	private String hash;
	private String repositorio;
	private String codUsuarioBloq;
	private Firmas ficheroPDF;
	private Firmas ficheroXML;
	private Set<FirmaDoc> xmlsFirma = new HashSet<FirmaDoc>(0);
	private Set<AnexoCaso> anexoCasos = new HashSet<AnexoCaso>(0);
	private Set<DatoRaiz> datoRaizes = new HashSet<DatoRaiz>(0);
	private Set<Materia> materias = new HashSet<Materia>(0);
	private Set<AntecedenteAdjunto> antecedenteAdjunto = new HashSet<AntecedenteAdjunto>(0);
	private Set<AntecedenteEducacional> antecedenteEducacionales = new HashSet<AntecedenteEducacional>(0);
	private Set<FirmaDoc> recibosFirma = new HashSet<FirmaDoc>(0);
	private Set<Documento> documentosFirma = new HashSet<Documento>(0);
	private Documento documentoOficioRep;
	private Documento documentoRetirarDocumento;
	private Set<FirmaDoc> pdfsFirma = new HashSet<FirmaDoc>(0);
	private Set<PeticionMasiva> peticionesMasiva = new HashSet<PeticionMasiva>(0);
	private Set<ActoMasivo> actosMasivo = new HashSet<ActoMasivo>(0);


	public Fichero() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_FICH_X_FICH")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_FICH", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "T_HASH", nullable = false, length = 250)
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	@Column(name = "V_REPOSITORIO", nullable = false, length = 1)
	public String getRepositorio() {
		return this.repositorio;
	}

	public void setRepositorio(String repositorio) {
		this.repositorio = repositorio;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "xmlFirma")
	public Set<FirmaDoc> getXmlsFirma() {
		return this.xmlsFirma;
	}

	public void setXmlsFirma(Set<FirmaDoc> firmaDocesForFichXFichX) {
		this.xmlsFirma = firmaDocesForFichXFichX;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichero")
	public Set<AnexoCaso> getAnexoCasos() {
		return this.anexoCasos;
	}

	public void setAnexoCasos(Set<AnexoCaso> anexoCasos) {
		this.anexoCasos = anexoCasos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichero")
	public Set<DatoRaiz> getDatoRaizes() {
		return this.datoRaizes;
	}

	public void setDatoRaizes(Set<DatoRaiz> datoRaizes) {
		this.datoRaizes = datoRaizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichero")
	public Set<Materia> getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set<Materia> materias) {
		this.materias = materias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichero")
	public Set<AntecedenteAdjunto> getAntecedenteAdjunto() {
		return antecedenteAdjunto;
	}

	public void setAntecedenteAdjunto(Set<AntecedenteAdjunto> antecedentesAdjuntos) {
		this.antecedenteAdjunto = antecedentesAdjuntos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichero")
	public Set<AntecedenteEducacional> getAntecedenteEducacionales() {
		return this.antecedenteEducacionales;
	}

	public void setAntecedenteEducacionales(Set<AntecedenteEducacional> antecedenteEducacionales) {
		this.antecedenteEducacionales = antecedenteEducacionales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reciboFirma")
	public Set<FirmaDoc> getRecibosFirma() {
		return this.recibosFirma;
	}

	public void setRecibosFirma(Set<FirmaDoc> firmaDocesForFichXFichP) {
		this.recibosFirma = firmaDocesForFichXFichP;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ficheroFirmaContralor")
	public Set<Documento> getDocumentosFirma() {
		return documentosFirma;
	}

	public void setDocumentosFirma(Set<Documento> documentosFirma) {
		this.documentosFirma = documentosFirma;
	}
	
	@OneToOne(mappedBy = "ficheroPDF")
	public Firmas getFicheroPDF() {
		return ficheroPDF;
	}

	public void setFicheroPDF(Firmas ficheroPDF) {
		this.ficheroPDF = ficheroPDF;
	}

	@OneToOne(mappedBy = "ficheroXML")
	public Firmas getFicheroXML() {
		return ficheroXML;
	}

	public void setFicheroXML(Firmas ficheroXML) {
		this.ficheroXML = ficheroXML;
	}

	@OneToOne(mappedBy = "ficheroOficioRepresentacion")
	public Documento getDocumentoOficioRep() {
		return documentoOficioRep;
	}

	public void setDocumentoOficioRep(Documento documentoOficioRep) {
		this.documentoOficioRep = documentoOficioRep;
	}
	
	@OneToOne(mappedBy = "ficheroRetirarDocumento")
	public Documento getDocumentoRetirarDocumento() {
		return documentoRetirarDocumento;
	}

	public void setDocumentoRetirarDocumento(Documento documentoRetirarDocumento) {
		this.documentoRetirarDocumento = documentoRetirarDocumento;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdfFirma")
	public Set<FirmaDoc> getPdfsFirma() {
		return pdfsFirma;
	}

	public void setPdfsFirma(Set<FirmaDoc> pdfsFirma) {
		this.pdfsFirma = pdfsFirma;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichero")
	public Set<PeticionMasiva> getPeticionesMasiva() {
		return peticionesMasiva;
	}
	public void setPeticionesMasiva(Set<PeticionMasiva> peticionesMasiva) {
		this.peticionesMasiva = peticionesMasiva;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preview", cascade = CascadeType.ALL)
	public Set<ActoMasivo> getActosMasivo() {
		return actosMasivo;
	}

	public void setActosMasivo(Set<ActoMasivo> actosMasivo) {
		this.actosMasivo = actosMasivo;
	}


	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Fichero))
			return false;
		Fichero castOther = (Fichero) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

//	public String toString() {
//		return "Hash: " + hash + ", repositorio: " + (repositorio != null && "F".equals(repositorio) ? "FileSystem" : "ContentManager");
//	}


	//add siaper-ru
	@Override
	public String toString() {
	    StringBuilder sb = new StringBuilder();
	    sb.append("{\n");

	    sb.append("  \"id\": ").append(id).append(",\n");
	    sb.append("  \"version\": ").append(version != null ? "\"" + version + "\"" : null).append(",\n");
	    sb.append("  \"hash\": ").append(hash != null ? "\"" + hash + "\"" : null).append(",\n");
	    sb.append("  \"repositorio\": ").append(repositorio != null ? "\"" + repositorio + "\"" : null).append(",\n");
	    sb.append("  \"codUsuarioBloq\": ").append(codUsuarioBloq != null ? "\"" + codUsuarioBloq + "\"" : null).append(",\n");

	    sb.append("  \"ficheroPDF\": ").append(ficheroPDF != null ? "\"" + ficheroPDF.getId() + "\"" : null).append(",\n");
	    sb.append("  \"ficheroXML\": ").append(ficheroXML != null ? "\"" + ficheroXML.getId() + "\"" : null).append(",\n");

	    sb.append("  \"xmlsFirma\": ").append(xmlsFirma != null ? xmlsFirma.size() : 0).append(",\n");
	    sb.append("  \"anexoCasos\": ").append(anexoCasos != null ? anexoCasos.size() : 0).append(",\n");
	    sb.append("  \"datoRaizes\": ").append(datoRaizes != null ? datoRaizes.size() : 0).append(",\n");
	    sb.append("  \"materias\": ").append(materias != null ? materias.size() : 0).append(",\n");
	    sb.append("  \"antecedenteAdjunto\": ").append(antecedenteAdjunto != null ? antecedenteAdjunto.size() : 0).append(",\n");
	    sb.append("  \"antecedenteEducacionales\": ").append(antecedenteEducacionales != null ? antecedenteEducacionales.size() : 0).append(",\n");
	    sb.append("  \"recibosFirma\": ").append(recibosFirma != null ? recibosFirma.size() : 0).append(",\n");
	    sb.append("  \"documentosFirma\": ").append(documentosFirma != null ? documentosFirma.size() : 0).append(",\n");

	    sb.append("  \"documentoOficioRep\": ").append(documentoOficioRep != null ? "\"" + documentoOficioRep.getId() + "\"" : null).append(",\n");
	    sb.append("  \"documentoRetirarDocumento\": ").append(documentoRetirarDocumento != null ? "\"" + documentoRetirarDocumento.getId() + "\"" : null).append(",\n");

	    sb.append("  \"pdfsFirma\": ").append(pdfsFirma != null ? pdfsFirma.size() : 0).append(",\n");
	    sb.append("  \"peticionesMasiva\": ").append(peticionesMasiva != null ? peticionesMasiva.size() : 0).append(",\n");
	    sb.append("  \"actosMasivo\": ").append(actosMasivo != null ? actosMasivo.size() : 0).append("\n");

	    sb.append("}");

	    return sb.toString();
	}

	
}
