package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 02-nov-2011 16:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Iterator;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * FirmaDoc generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_FIRMAS_DOC")
public class FirmaDoc implements java.io.Serializable {

	private static final long serialVersionUID = -6972173126643533678L;

	private Long id;
	private Date version;
	private Documento documento;
	private Fichero xmlFirma;
	private Usuario usuario;
	private Servicio servicio;
	private Fichero reciboFirma;
	private String codTransaccion;
	private Date fechaFirma;
	private String codUsuarioBloq;
	private String nombreFirmante;
	private Fichero pdfFirma;
	private String csvFirma;

	public FirmaDoc() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_FIDO_X_FIDO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_FIDO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCU_X_DOCU", nullable = false)
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FICH_X_FICH_X")
	public Fichero getXmlFirma() {
		return this.xmlFirma;
	}

	public void setXmlFirma(Fichero ficheroByFichXFichX) {
		this.xmlFirma = ficheroByFichXFichX;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUA_X_USUA", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV", nullable = false)
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FICH_X_FICH_P")
	public Fichero getReciboFirma() {
		return this.reciboFirma;
	}

	public void setReciboFirma(Fichero ficheroByFichXFichP) {
		this.reciboFirma = ficheroByFichXFichP;
	}

	@Column(name = "C_TRANSACCION", length = 250)
	public String getCodTransaccion() {
		return this.codTransaccion;
	}

	public void setCodTransaccion(String codTransaccion) {
		this.codTransaccion = codTransaccion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FIRMA", length = 7)
	public Date getFechaFirma() {
		return this.fechaFirma;
	}

	public void setFechaFirma(Date fechaFirma) {
		this.fechaFirma = fechaFirma;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@Column(name = "T_NOMBRE_FIRMANTE", length = 250)
	public String getNombreFirmante() {
		return nombreFirmante;
	}

	public void setNombreFirmante(String nombreFirmante) {
		this.nombreFirmante = nombreFirmante;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FICH_X_FICH_F")
	public Fichero getPdfFirma() {
		return pdfFirma;
	}

	public void setPdfFirma(Fichero pdfFirma) {
		this.pdfFirma = pdfFirma;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FirmaDoc))
			return false;
		FirmaDoc castOther = (FirmaDoc) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	/**
	 * @return the csvFirma
	 */
	@Column(name = "C_CSV", length = 50)
	public String getCsvFirma() {
		return csvFirma;
	}

	/**
	 * @param csvFirma the csvFirma to set
	 */
	public void setCsvFirma(String csvFirma) {
		this.csvFirma = csvFirma;
	}

	public static FirmaDoc getFirmaIterating(Set<FirmaDoc> firmas) {

		FirmaDoc firma = null;

		if (firmas != null && !firmas.isEmpty()) {
			Iterator<FirmaDoc> it = firmas.iterator();
			while (it.hasNext()) {
				FirmaDoc firmaAux = it.next();
				if (firmaAux.getXmlFirma() != null) {
					if (firma == null || firma.getId() < firmaAux.getId()) {
						firma = firmaAux;
					}
				}
			}
		}

		return firma;
	}
	
}
