package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_FIRMANTES_ADJUNTOS")
public class FirmanteAdjunto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6573784689065752808L;
	private Long id;
	private Date version;	
	private String codUsuarioBloq;	
	private Usuario usuarioFirmante; 
	private Servicio servicioFirmante;
			
	public FirmanteAdjunto() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_FIAD_X_FIAD")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_FIAD", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
		
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUA_X_USUA", nullable = false)
	public Usuario getUsuarioFirmante() {
		return usuarioFirmante;
	}

	public void setUsuarioFirmante(Usuario usuarioFirmante) {
		this.usuarioFirmante = usuarioFirmante;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV", nullable = false)
	public Servicio getServicioFirmante() {
		return servicioFirmante;
	}

	public void setServicioFirmante(Servicio servicioFirmante) {
		this.servicioFirmante = servicioFirmante;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FirmanteAdjunto))
			return false;
		FirmanteAdjunto castOther = (FirmanteAdjunto) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
				
}
