package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 11-oct-2011 13:25:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * Formulario generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_FORMULARIOS")
public class Formulario implements java.io.Serializable, Comparable<Formulario>, Cloneable {

	private static final long serialVersionUID = 8898999316701386374L;

	private Long id;
	private Date version;
	private Materia materia;
	private Date fechaInicio;
	private Date fechaFin;
	private String pkgUri;
	private String drlUri;
	private String xmlUri;
	private String xmlBorradorUri;
	private Boolean valido;
	private Boolean activo;
	private String codUsuarioBloq;
	private Servicio servicio;
	private Set<CasoDocumento> casoDocumentos = new HashSet<CasoDocumento>(0);
	private Set<CaminoTraGen> caminosTra = new HashSet<CaminoTraGen>();
	private Set<CaminoTraEsp> caminosTraEsp = new HashSet<CaminoTraEsp>();
	private String comentario;
	private Boolean precargado;
	private Set<CargaFormulario> tiemposCargaFormulario = new HashSet<CargaFormulario>(0);
	
	// Transient
	private boolean vigente;

	public Formulario() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_FORM_X_FORM")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_FORM", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATE_X_MATE", nullable = false)
	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_INICIO", nullable = false, length = 7)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FIN", length = 7)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}



	@Column(name = "T_PKG_URI", length = 500)
	public String getPkgUri() {
		return this.pkgUri;
	}
	
	public void setPkgUri(String pkgUri) {
		this.pkgUri = pkgUri;
	}
	
	@Column(name = "T_DRL_URI", length = 500)
	public String getDrlUri() {
		return this.drlUri;
	}
	
	public void setDrlUri(String drlUri) {
		this.drlUri = drlUri;
	}	

	@Column(name = "T_XML_URI")
	public String getXmlUri() {
		return xmlUri;
	}

	public void setXmlUri(String xmlUri) {
		this.xmlUri = xmlUri;
	}

	@Column(name = "T_XML_BORRADOR_URI")
	public String getXmlBorradorUri() {
		return xmlBorradorUri;
	}

	public void setXmlBorradorUri(String xmlBorradorUri) {
		this.xmlBorradorUri = xmlBorradorUri;
	}

	@Column(name = "L_VALIDO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getValido() {
		return this.valido;
	}

	public void setValido(Boolean valido) {
		this.valido = valido;
	}

	@Column(name = "L_PRECARGADO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getPrecargado() {
		return this.precargado;
	}

	public void setPrecargado(Boolean precargado) {
		this.precargado = precargado;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formulario")
	public Set<CasoDocumento> getCasoDocumentos() {
		return this.casoDocumentos;
	}

	public void setCasoDocumentos(Set<CasoDocumento> casoDocumentos) {
		this.casoDocumentos = casoDocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formulario")
	public Set<CaminoTraGen> getCaminosTra() {
		return caminosTra;
	}

	public void setCaminosTra(Set<CaminoTraGen> caminosTra) {
		this.caminosTra = caminosTra;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formulario")
	public Set<CaminoTraEsp> getCaminosTraEsp() {
		return caminosTraEsp;
	}

	public void setCaminosTraEsp(Set<CaminoTraEsp> caminosTraEsp) {
		this.caminosTraEsp = caminosTraEsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV", nullable = true)
	public Servicio getServicio() {
		return servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}
	
	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Formulario))
			return false;
		Formulario castOther = (Formulario) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public int compareTo(Formulario f) {
		Formulario form = (Formulario) f;
		return this.getFechaInicio().compareTo(form.getFechaInicio());
	}
	
	public Formulario clone() {
		try {
			return (Formulario) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}

	public String toString() {
		return "Materia: (" + materia + "), inicio: " + fechaInicio + ", fin: " + fechaFin;
	}

	@Transient
	public boolean isVigente() {
		return vigente;
	}

	public void setVigente(boolean vigente) {
		this.vigente = vigente;
	}

	@Column(name = "T_COMENTARIO", length = 500)
	public String getComentario() {
		return comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	/**
	 * @return the tiemposCargaFormulario
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formulario")
	public Set<CargaFormulario> getTiemposCargaFormulario() {
		return tiemposCargaFormulario;
	}

	/**
	 * @param tiemposCargaFormulario the tiemposCargaFormulario to set
	 */
	public void setTiemposCargaFormulario(Set<CargaFormulario> tiemposCargaFormulario) {
		this.tiemposCargaFormulario = tiemposCargaFormulario;
	}

}
