package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 05-mar-2012 9:06:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * FuncSuplidoReemplazado generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_FUNC_SUPL_REEMPLAZADO")
public class FuncSuplidoReemplazado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 542077385676676424L;
	private Long id;
	private Date version;
	private PanelSuplenciaReemplazo panelSuplenciaReemplazo;
	private String codUsuarioBloq;
	private String run;
	private String otraIdentificacion;
	private String nombres;
	private String tipoRespaldo;
	private Long funcionario;
	private Set<ActoRespaldo> actoRespaldos = new HashSet<ActoRespaldo>(0);
	private Set<DocumentoRespaldo> documentoRespaldos = new HashSet<DocumentoRespaldo>(
			0);

	public FuncSuplidoReemplazado() {
	}

	public FuncSuplidoReemplazado(
			PanelSuplenciaReemplazo panelSuplenciaReemplazo) {
		this.panelSuplenciaReemplazo = panelSuplenciaReemplazo;
	}

	public FuncSuplidoReemplazado(
			PanelSuplenciaReemplazo panelSuplenciaReemplazo, String run,
			String otraIdentificacion, String tipoRespaldo, Long funcionario,
			Set<ActoRespaldo> actoRespaldos,
			Set<DocumentoRespaldo> documentoRespaldos) {
		this.panelSuplenciaReemplazo = panelSuplenciaReemplazo;
		this.run = run;
		this.otraIdentificacion = otraIdentificacion;
		this.tipoRespaldo = tipoRespaldo;
		this.funcionario = funcionario;
		this.actoRespaldos = actoRespaldos;
		this.documentoRespaldos = documentoRespaldos;
	}
	
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_FUSR_X_FUSR")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_FUSR", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PASR_X_PASR", nullable = false)
	public PanelSuplenciaReemplazo getPanelSuplenciaReemplazo() {
		return this.panelSuplenciaReemplazo;
	}

	public void setPanelSuplenciaReemplazo(
			PanelSuplenciaReemplazo panelSuplenciaReemplazo) {
		this.panelSuplenciaReemplazo = panelSuplenciaReemplazo;
	}

	@Column(name = "T_RUN", length = 10)
	public String getRun() {
		return this.run;
	}

	public void setRun(String run) {
		this.run = run;
	}

	@Column(name = "T_OTRA_IDENTIFICACION", length = 15)
	public String getOtraIdentificacion() {
		return this.otraIdentificacion;
	}

	public void setOtraIdentificacion(String otraIdentificacion) {
		this.otraIdentificacion = otraIdentificacion;
	}

	@Column(name = "V_TIPO_RESPALDO", length = 1)
	public String getTipoRespaldo() {
		return this.tipoRespaldo;
	}

	public void setTipoRespaldo(String tipoRespaldo) {
		this.tipoRespaldo = tipoRespaldo;
	}
	
	@Column(name = "S_FUNCIONARIO", precision = 15, scale = 0)
	public Long getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Long funcionario) {
		this.funcionario = funcionario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcSuplidoReemplazado", cascade = CascadeType.ALL)
	public Set<ActoRespaldo> getActoRespaldos() {
		return this.actoRespaldos;
	}

	public void setActoRespaldos(Set<ActoRespaldo> actoRespaldos) {
		this.actoRespaldos = actoRespaldos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcSuplidoReemplazado", cascade = CascadeType.ALL)
	public Set<DocumentoRespaldo> getDocumentoRespaldos() {
		return this.documentoRespaldos;
	}

	public void setDocumentoRespaldos(Set<DocumentoRespaldo> documentoRespaldos) {
		this.documentoRespaldos = documentoRespaldos;
	}
	
	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "T_NOMBRES", length = 300)
	public String getNombres() {
		return nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		} else {
			if (obj instanceof FuncSuplidoReemplazado) {
				FuncSuplidoReemplazado funcSuplido = (FuncSuplidoReemplazado) obj;
				if (funcSuplido.getId() != null) {
					if (funcSuplido.getId().equals(this.getId())) {
						return true;
					} else {
						return false;
					}
				} else {
					return false;
				}
			} else {
				return false;
			}
		}
	}
}

	