package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

// Generated 09-feb-2012 17:49:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * Ley generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_LEYES", uniqueConstraints = @UniqueConstraint(columnNames = "N_LEY"))
public class Ley implements java.io.Serializable, Cloneable{

	private Long id;
	private Date version;
	private Ley ley;
	private Date fechaInicio;
	private Date fechaFin;
	private String numLey;
	private String texto;
	private String codUsuarioBloq;
	private Boolean especifica;
	private Set<ArticuloMateria> materiasArticulos = new HashSet<ArticuloMateria>(0);
	private Set<Articulo> articulos = new HashSet<Articulo>(0);
	private Set<Ley> leyes = new HashSet<Ley>(0);

	public Ley() {
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_LEYE_X_LEYE")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_LEYE", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEYE_X_LEYE")
	public Ley getLey() {
		return this.ley;
	}

	public void setLey(Ley ley) {
		this.ley = ley;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_INICIO", nullable = false, length = 7)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FIN", length = 7)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "N_LEY", unique = true, length = 50)
	public String getNumLey() {
		return this.numLey;
	}

	public void setNumLey(String numLey) {
		this.numLey = numLey;
	}

	@Column(name = "T_TEXTO_LEY")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "L_ESPECIFICA", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getEspecifica() {
		return this.especifica;
	}

	public void setEspecifica(Boolean especifica) {
		this.especifica = especifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ley")
	public Set<ArticuloMateria> getMateriasArticulos() {
		return materiasArticulos;
	}
	
	public void setMateriasArticulos(Set<ArticuloMateria> materiasArticulos) {
		this.materiasArticulos = materiasArticulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ley", cascade = CascadeType.REMOVE)
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ley")
	public Set<Ley> getLeyes() {
		return this.leyes;
	}

	public void setLeyes(Set<Ley> leyes) {
		this.leyes = leyes;
	}

	public Ley clone() {
		try {
			return (Ley) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Ley))
			return false;
		Ley castOther = (Ley) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Número: " + numLey;
	}

}
