package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 03-oct-2011 16:27:55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * MatConvalNivConval generated by hbm2java
 */
@Entity
@Audited
@AuditTable("TRA_MAT_CONVAL_X_NIV_CONV_HIST")
@Table(name = "TRA_MAT_CONVAL_X_NIV_CONVAL", uniqueConstraints = @UniqueConstraint(columnNames = { "MACO_X_MACO", "NICO_X_NICO" }))
public class MatConvalNivConval implements java.io.Serializable {

	private static final long serialVersionUID = -9065984505860415792L;

	private Long id;
	private Date version;
	private NivelConvalidado nivelConvalidado;
	private MateriaConvalida materiaConvalida;
	private String codUsuarioBloq;

	public MatConvalNivConval() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_MANC_X_MANC")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_MANC", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NICO_X_NICO", nullable = false)
	public NivelConvalidado getNivelConvalidado() {
		return this.nivelConvalidado;
	}

	public void setNivelConvalidado(NivelConvalidado nivelConvalidado) {
		this.nivelConvalidado = nivelConvalidado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MACO_X_MACO", nullable = false)
	public MateriaConvalida getMateriaConvalida() {
		return this.materiaConvalida;
	}

	public void setMateriaConvalida(MateriaConvalida materiaConvalida) {
		this.materiaConvalida = materiaConvalida;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatConvalNivConval))
			return false;
		MatConvalNivConval castOther = (MatConvalNivConval) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	public String toString() {
		return "Nivel: (" + nivelConvalidado + "), materia: (" + materiaConvalida + ")";
	}
	
}
