package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 06-oct-2011 12:06:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * MateriaConvalida generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_MATERIAS_CONVALIDA", uniqueConstraints = @UniqueConstraint(columnNames = "C_MACO"))
public class MateriaConvalida implements java.io.Serializable {

	private static final long serialVersionUID = 6744000040021922486L;

	private Long id;
	private Date version;
	private Long codSiaper;
	private String codigo;
	private String descripcion;
	private Boolean activo;
	private String codUsuarioBloq;
	private Set<MatConvalNivConval> matConvalNivConvales = new HashSet<MatConvalNivConval>(0);
	private Set<AntecedenteEducacional> antecedentesEducacionales = new HashSet<AntecedenteEducacional>(0);

	public MateriaConvalida() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_MACO_X_MACO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_MACO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@Column(name = "S_MACO", precision = 12, scale = 0)
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}
	
	@Column(name = "C_MACO", unique = true, nullable = false, length = 5)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "D_MACO", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiaConvalida")
	public Set<MatConvalNivConval> getMatConvalNivConvales() {
		return this.matConvalNivConvales;
	}

	public void setMatConvalNivConvales(Set<MatConvalNivConval> matConvalNivConvales) {
		this.matConvalNivConvales = matConvalNivConvales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiaConvalida")
	public Set<AntecedenteEducacional> getAntecedentesEducacionales() {
		return this.antecedentesEducacionales;
	}

	public void setAntecedentesEducacionales(Set<AntecedenteEducacional> antecedenteEducacionales) {
		this.antecedentesEducacionales = antecedenteEducacionales;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MateriaConvalida))
			return false;
		MateriaConvalida castOther = (MateriaConvalida) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion;
	}

}
