package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 09-feb-2012 17:49:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * Materia generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_MATERIA_RAIZ_VALIDA")
public class MateriaRaizValida implements java.io.Serializable, Comparable<MateriaRaizValida>{

	/**
	 * 
	 */
	private static final long serialVersionUID = -9110830547499484025L;
	
	
	private Long id;
	private Date version;	
	private String codMateria;
	private String nombreMateria;	

	public MateriaRaizValida() {
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_MAVA_X_MAVA")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_MAVA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "C_MATE", unique = true, nullable = false, length = 20)
	public String getCodMateria() {
		return this.codMateria;
	}

	public void setCodMateria(String codMateria) {
		this.codMateria = codMateria;
	}
	
	@Column(name = "T_NOMBRE_MATERIA", length = 250)
	public String getNombreMateria() {
		return this.nombreMateria;
	}

	public void setNombreMateria(String nombreMateria) {
		this.nombreMateria = nombreMateria;
	}
	
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MateriaRaizValida))
			return false;
		MateriaRaizValida castOther = (MateriaRaizValida) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	

	public String toString() {
		return "Código: " + codMateria + ", nombre: " + nombreMateria;
	}

	public int compareTo(MateriaRaizValida arg) {
		return(this.codMateria.compareTo(arg.getCodMateria()));
	}
		
}
