package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * MateriaServicio generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_MATERIAS_SERVICIOS", uniqueConstraints = @UniqueConstraint(columnNames = { "SERV_X_SERV_OPERANTE", "MATE_X_MATE" }))
public class MateriaServicio implements java.io.Serializable {

	private static final long serialVersionUID = 6729928406430369712L;

	private Long id;
	private Date version;
	private Servicio servicioOperado;
	private Servicio servicioOperante;
	private Materia materia;
	private String codUsuarioBloq;
	private boolean visarSubsecretario;
	private String textoVisarSubsecretario;
	private boolean tomarazonElectronica;
	private boolean controlVisacion;
	private boolean mateSinCatalogo;
	private boolean registroAutomatico;
	
	public MateriaServicio() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_MASE_X_MASE")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_MASE", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV_OPERADO", nullable = false)
	public Servicio getServicioOperado() {
		return this.servicioOperado;
	}

	public void setServicioOperado(Servicio servicioByServXServOperado) {
		this.servicioOperado = servicioByServXServOperado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV_OPERANTE", nullable = false)
	public Servicio getServicioOperante() {
		return this.servicioOperante;
	}

	public void setServicioOperante(Servicio servicioByServXServOperante) {
		this.servicioOperante = servicioByServXServOperante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATE_X_MATE", nullable = false)
	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "L_VISAR_SUBSECR", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isVisarSubsecretario() {
		return visarSubsecretario;
	}

	public void setVisarSubsecretario(boolean visarSubsecretario) {
		this.visarSubsecretario = visarSubsecretario;
	}

	@Column(name = "T_TEXTO_VISAR", length = 4000)
	public String getTextoVisarSubsecretario() {
		return textoVisarSubsecretario;
	}

	public void setTextoVisarSubsecretario(String textoVisarSubsecretario) {
		this.textoVisarSubsecretario = textoVisarSubsecretario;
	}

	@Column(name = "L_TOMARA_ELECTRONICA", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isTomarazonElectronica() {
		return tomarazonElectronica;
	}

	public void setTomarazonElectronica(boolean tomarazonElectronica) {
		this.tomarazonElectronica = tomarazonElectronica;
	}
	
	@Column(name = "L_CATALOGO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isMateSinCatalogo() {
		return mateSinCatalogo;
	}

	public void setMateSinCatalogo(boolean mateSinCatalogo) {
		this.mateSinCatalogo = mateSinCatalogo;
	}
	
	@Column(name = "L_CONTROL_VISACION", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isControlVisacion() {
		return controlVisacion;
	}

	public void setControlVisacion(boolean controlVisacion) {
		this.controlVisacion = controlVisacion;
	}
	
	@Column(name = "L_REGISTRO_AUTOMATICO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isRegistroAutomatico() {
		return registroAutomatico;
	}

	public void setRegistroAutomatico(boolean registroAutomatico) {
		this.registroAutomatico = registroAutomatico;
	}
	
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MateriaServicio))
			return false;
		MateriaServicio castOther = (MateriaServicio) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Serv. operante: (" + servicioOperante + "), serv. operado (: " + servicioOperado + "), materia: (" + materia + ")";
	}
}
