package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 09-feb-2012 17:49:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * Materia generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_MATERIAS", uniqueConstraints = @UniqueConstraint(columnNames = "C_CODIGO"))
public class Materia implements java.io.Serializable, Comparable<Materia>{

	/**
	 * 
	 */
	private static final long serialVersionUID = -9110830547499484025L;
	
	
	private Long id;
	private Date version;
	private TipoMateria tipoMateria;
	private Fichero fichero;
	private String codCodigo;
	private String nombreMateria;
	private String grillaLista;
	private String formaOperar;
	private Boolean panelAntecedentes = false;
	private Boolean activaCampos12;
	private Boolean activaCampo3;
	private Boolean campo1Defecto;
	private Boolean activo;
	private String codUsuarioBloq;
	private Boolean operaEspecificos;
	private Boolean tomaRazonManual;
	private boolean revisionRepresentacion;
	private CalidadContractual calidadContractual;
	private Boolean adjuntaConvenio;
	private Boolean operaMulticaso;
	private Boolean panelOtrosAntecedentes;
	private String tipoActoAdministrativo;
	private Boolean cargaMasiva;
	private Fichero ficheroCargaMasiva;
		

	private String leyendaOficio;
	private Set<Formulario> formularios = new HashSet<Formulario>(0);
	private Set<ArtservMateria> artservMaterias = new HashSet<ArtservMateria>(0);
	private Set<MateriaServicio> materiaServicios = new HashSet<MateriaServicio>(0);
	private Set<MateriaDotacion> materiaDotaciones = new HashSet<MateriaDotacion>(0);
	private Set<AccionCondicion> accionCondiciones = new HashSet<AccionCondicion>(0);
	private Set<ArticuloMateria> articulos = new HashSet<ArticuloMateria>(0);
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<DocumentoModificaRectifica> documentosModificaRectifica = new HashSet<DocumentoModificaRectifica>(0);
	
	private Set<BeneficioMateria> beneficiosMateria = new HashSet<BeneficioMateria>(0);
	
	private Set<PeticionMasiva> peticionesMasiva = new HashSet<PeticionMasiva>(0);

	public Materia() {
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_MATE_X_MATE")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_MATE", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FICH_X_FICH")
	public Fichero getFichero() {
		return this.fichero;
	}

	public void setFichero(Fichero fichero) {
		this.fichero = fichero;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FICH_X_FICH_C")
	public Fichero getFicheroCargaMasiva() {
		return ficheroCargaMasiva;
	}

	public void setFicheroCargaMasiva(Fichero ficheroCargaMasiva) {
		this.ficheroCargaMasiva = ficheroCargaMasiva;
	}

	@Column(name = "C_CODIGO", unique = true, nullable = false, length = 20)
	public String getCodCodigo() {
		return this.codCodigo;
	}

	public void setCodCodigo(String codCodigo) {
		this.codCodigo = codCodigo;
	}

	@Column(name = "T_NOMBRE_MATERIA", length = 250)
	public String getNombreMateria() {
		return this.nombreMateria;
	}

	public void setNombreMateria(String nombreMateria) {
		this.nombreMateria = nombreMateria;
	}
	
	@Column(name = "T_ACTO_ADMIN", length = 250)
	public String getTipoActoAdministrativo() {
		return tipoActoAdministrativo;
	}

	public void setTipoActoAdministrativo(String tipoActoAdministrativo) {
		this.tipoActoAdministrativo = tipoActoAdministrativo;
	}
	
	@Column(name = "V_GRILLA_LISTA", length = 1)
	public String getGrillaLista() {
		return this.grillaLista;
	}

	public void setGrillaLista(String grillaLista) {
		this.grillaLista = grillaLista;
	}

	@Column(name = "V_FORMA_OPERAR", length = 1)
	public String getFormaOperar() {
		return this.formaOperar;
	}

	public void setFormaOperar(String formaOperar) {
		this.formaOperar = formaOperar;
	}
	
	
	@Column(name = "T_LEYENDA_OFICIO", length = 500)
	public String getLeyendaOficio() {
		return leyendaOficio;
	}

	public void setLeyendaOficio(String leyendaOficio) {
		this.leyendaOficio = leyendaOficio;
	}

	@Column(name = "L_PANEL_ANTECEDENTES", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getPanelAntecedentes() {
		return this.panelAntecedentes;
	}

	public void setPanelAntecedentes(Boolean panelAntecedentes) {
		this.panelAntecedentes = panelAntecedentes;
	}

	@Column(name = "L_ACTIVA_CAMPOS12", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivaCampos12() {
		return this.activaCampos12;
	}

	public void setActivaCampos12(Boolean activaCampos12) {
		this.activaCampos12 = activaCampos12;
	}

	@Column(name = "L_ACTIVA_CAMPO3", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivaCampo3() {
		return this.activaCampo3;
	}

	public void setActivaCampo3(Boolean activaCampo3) {
		this.activaCampo3 = activaCampo3;
	}

	@Column(name = "L_CAMPO1_DEFECTO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getCampo1Defecto() {
		return this.campo1Defecto;
	}

	public void setCampo1Defecto(Boolean campo1Defecto) {
		this.campo1Defecto = campo1Defecto;
	}

	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "L_OPERA_ESPECIFICOS", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getOperaEspecificos() {
		return this.operaEspecificos;
	}

	public void setOperaEspecificos(Boolean operaEspecificos) {
		this.operaEspecificos = operaEspecificos;
	}
	
	@Column(name = "L_TR_MANUAL", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getTomaRazonManual() {
		return tomaRazonManual;
	}

	public void setTomaRazonManual(Boolean tomaRazonManual) {
		this.tomaRazonManual = tomaRazonManual;
	}

	@Column(name = "L_REV_REPRESENTACION", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isRevisionRepresentacion() {
		return revisionRepresentacion;
	}

	public void setRevisionRepresentacion(boolean revisionRepresentacion) {
		this.revisionRepresentacion = revisionRepresentacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<Formulario> getFormularios() {
		return this.formularios;
	}	

	public void setFormularios(Set<Formulario> formularios) {
		this.formularios = formularios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<ArtservMateria> getArtservMaterias() {
		return this.artservMaterias;
	}

	public void setArtservMaterias(Set<ArtservMateria> artservMaterias) {
		this.artservMaterias = artservMaterias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<MateriaServicio> getMateriaServicios() {
		return this.materiaServicios;
	}

	public void setMateriaServicios(Set<MateriaServicio> materiaServicios) {
		this.materiaServicios = materiaServicios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<MateriaDotacion> getMateriaDotaciones() {
		return this.materiaDotaciones;
	}

	public void setMateriaDotaciones(Set<MateriaDotacion> materiaDotaciones) {
		this.materiaDotaciones = materiaDotaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<AccionCondicion> getAccionCondiciones() {
		return this.accionCondiciones;
	}

	public void setAccionCondiciones(Set<AccionCondicion> accionCondiciones) {
		this.accionCondiciones = accionCondiciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<ArticuloMateria> getArticulos() {
		return articulos;
	}
	
	public void setArticulos(Set<ArticuloMateria> articulos) {
		this.articulos = articulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}
	
	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIMA_X_TIMA", nullable = false)
	public TipoMateria getTipoMateria() {
		return tipoMateria;
	}
	
	public void setTipoMateria(TipoMateria tipoMateria) {
		this.tipoMateria = tipoMateria;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CACO_X_CACO", nullable = true)
	public CalidadContractual getCalidadContractual() {
		return calidadContractual;
	}

	public void setCalidadContractual(CalidadContractual calidadContractual) {
		this.calidadContractual = calidadContractual;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Materia))
			return false;
		Materia castOther = (Materia) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	

	public String toString() {
		return "Código: " + codCodigo + ", nombre: " + nombreMateria;
	}

	public int compareTo(Materia arg) {
		return(this.nombreMateria.toUpperCase().compareTo(arg.getNombreMateria().toUpperCase()));
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<BeneficioMateria> getBeneficiosMateria() {
		return beneficiosMateria;
	}
	public void setBeneficiosMateria(Set<BeneficioMateria> beneficiosMateria) {
		this.beneficiosMateria = beneficiosMateria;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<PeticionMasiva> getPeticionesMasiva() {
		return peticionesMasiva;
	}
	public void setPeticionesMasiva(Set<PeticionMasiva> peticionesMasiva) {
		this.peticionesMasiva = peticionesMasiva;
	}

	@Column(name = "L_ADJUNTA_CONVENIO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getAdjuntaConvenio() {
		return adjuntaConvenio;
	}

	public void setAdjuntaConvenio(Boolean adjuntaConvenio) {
		this.adjuntaConvenio = adjuntaConvenio;
	}

	@Column(name = "L_OPERA_MULTICASO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getOperaMulticaso() {
		return operaMulticaso;
	}

	public void setOperaMulticaso(Boolean operaMulticaso) {
		this.operaMulticaso = operaMulticaso;
	}

	@Column(name = "L_MOSTRAR_ANTECEDENTES", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getPanelOtrosAntecedentes() {
		return panelOtrosAntecedentes;
	}

	public void setPanelOtrosAntecedentes(Boolean panelOtrosAntecedentes) {
		this.panelOtrosAntecedentes = panelOtrosAntecedentes;
	}
	
	@Column(name = "L_CARGA_MASIVA", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean isCargaMasiva() {
		return cargaMasiva;
	}

	public void setCargaMasiva(Boolean cargaMasiva) {
		this.cargaMasiva = cargaMasiva;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<DocumentoModificaRectifica> getDocumentosModificaRectifica() {
		return this.documentosModificaRectifica;
	}
	
	public void setDocumentosModificaRectifica(Set<DocumentoModificaRectifica> documentosModificaRectifica) {
		this.documentosModificaRectifica = documentosModificaRectifica;
	}
}
