package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 11-oct-2011 11:53:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * MedioVerificacion generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_MEDIOS_VERIFICACION", uniqueConstraints = @UniqueConstraint(columnNames = "C_MEVE"))
public class MedioVerificacion implements java.io.Serializable {

	private static final long serialVersionUID = 2180024432312615149L;

	private Long id;
	private Date version;
	private String codSiaper;
	private String descripcion;
	private String codUsuarioBloq;
	private String codigo;
	private Set<Requisito> requisitosAlternativaSi = new HashSet<Requisito>(0);
	private Set<Requisito> requisitosAlternativaNo = new HashSet<Requisito>(0);
	private Set<AnexoCaso> anexosCasos = new HashSet<AnexoCaso>(0);

	public MedioVerificacion() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_MEVE_X_MEVE")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_MEVE", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "S_MEVE", nullable = false, length = 50)
	public String getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(String codSiaper) {
		this.codSiaper = codSiaper;
	}

	@Column(name = "D_MEVE", length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}


	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "C_MEVE", nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medioVerificacionAlternativaSi")
	public Set<Requisito> getRequisitosAlternativaSi() {
		return this.requisitosAlternativaSi;
	}

	public void setRequisitosAlternativaSi(Set<Requisito> requisitosForMeveAlternatSi) {
		this.requisitosAlternativaSi = requisitosForMeveAlternatSi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medioVerificacionAlternativaNo")
	public Set<Requisito> getRequisitosAlternativaNo() {
		return this.requisitosAlternativaNo;
	}

	public void setRequisitosAlternativaNo(Set<Requisito> requisitosForMeveAlternatNo) {
		this.requisitosAlternativaNo = requisitosForMeveAlternatNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medioVerificacion")
	public Set<AnexoCaso> getAnexosCasos() {
		return this.anexosCasos;
	}

	public void setAnexosCasos(Set<AnexoCaso> anexoCasos) {
		this.anexosCasos = anexoCasos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MedioVerificacion))
			return false;
		MedioVerificacion castOther = (MedioVerificacion) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion;
	}

}