package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * TipoHora generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_MOTIVO_DOTACION", uniqueConstraints = @UniqueConstraint(columnNames = "C_DOMO"))
public class MotivoDotacion implements java.io.Serializable {

	private static final long serialVersionUID = -5416522043274077147L;

	private Long id;
	private Long codSiaper;
	private String descripcion;
	private Date version;
	
	public MotivoDotacion() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_DOMO_X_DOMO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_DOMO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	
	
	@Column(name = "T_DESCRIPCION", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}


	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "C_DOMO", length = 10, precision = 12, nullable=false, scale = 0)
	public Long getCodSiaper() {
		return this.codSiaper;
	}

	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MotivoDotacion))
			return false;
		MotivoDotacion castOther = (MotivoDotacion) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Nombre: " + codSiaper + ", descripción: " + descripcion;
	}
}