package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 18-oct-2011 11:46:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * NivelEstudioFormal generated by hbm2java
 */
@Entity
@Audited
@AuditTable("TRA_NIVELES_ESTUDIOS_FORM_HIST")
@Table(name = "TRA_NIVELES_ESTUDIOS_FORMALES", uniqueConstraints = @UniqueConstraint(columnNames = "C_NIEF"))
public class NivelEstudioFormal implements java.io.Serializable {

	private static final long serialVersionUID = 2950242928098581116L;

	private Long id;
	private Date version;
	private String codigo;
	private Long codSiaper;
	private String descripcion;
	private Boolean activo;
	private String codUsuarioBloq;
	private Set<AntecedenteEducacional> antecedentesEducacionales = new HashSet<AntecedenteEducacional>(0);
	private Set<EntidadNivelEducacional> entidadesOtorgadoras = new HashSet<EntidadNivelEducacional>(0);
	private Set<NivelEducacional> nivelesEducacionales = new HashSet<NivelEducacional>(0);
	private Set<NivelEducacional> nivelesEducacionalesConv = new HashSet<NivelEducacional>(0);
	private Set<GradoAcademico> gradosAcademicos = new HashSet<GradoAcademico>(0);

	public NivelEstudioFormal() {
	}

	public NivelEstudioFormal(long id) {
		this.id = id;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_NIEF_X_NIEF")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_NIEF", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@Column(name = "S_NIEF", precision = 12, scale = 0)
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}
	
	@Column(name = "C_NIEF", unique = true, nullable = false, length = 5)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "D_NIEF", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "L_ACTIVO", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEstudioFormal")
	public Set<AntecedenteEducacional> getAntecedentesEducacionales() {
		return this.antecedentesEducacionales;
	}

	public void setAntecedentesEducacionales(Set<AntecedenteEducacional> antecedenteEducacionales) {
		this.antecedentesEducacionales = antecedenteEducacionales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEstudioFormal")
	public Set<EntidadNivelEducacional> getEntidadesOtorgadoras() {
		return this.entidadesOtorgadoras;
	}

	public void setEntidadesOtorgadoras(Set<EntidadNivelEducacional> entidadNivelEducacionales) {
		this.entidadesOtorgadoras = entidadNivelEducacionales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEstudioFormal")
	public Set<NivelEducacional> getNivelesEducacionales() {
		return this.nivelesEducacionales;
	}

	public void setNivelesEducacionales(Set<NivelEducacional> nivelEducacionales) {
		this.nivelesEducacionales = nivelEducacionales;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEstudioFormalConv")
	public Set<NivelEducacional> getNivelesEducacionalesConv() {
		return nivelesEducacionalesConv;
	}
	
	public void setNivelesEducacionalesConv(
			Set<NivelEducacional> nivelesEducacionalesConv) {
		this.nivelesEducacionalesConv = nivelesEducacionalesConv;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEstudioFormalConv")
	public Set<GradoAcademico> getGradosAcademicos() {
		return gradosAcademicos;
	}

	public void setGradosAcademicos(Set<GradoAcademico> gradosAcademicos) {
		this.gradosAcademicos = gradosAcademicos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NivelEstudioFormal))
			return false;
		NivelEstudioFormal castOther = (NivelEstudioFormal) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	

	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion;
	}

}
