package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 03-oct-2011 16:27:55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * NivelDocente generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_NIVELES_DOCENTES", uniqueConstraints = @UniqueConstraint(columnNames = "C_NIDO"))
public class NivelDocente implements java.io.Serializable {

	private static final long serialVersionUID = -3520539123955545244L;

	private Long id;
	private Date version;
	private String codigo;
	private String descripcion;
	private Boolean activo;
	private String codUsuarioBloq;
	private Set<AntecedenteEducacional> antecedenteEducacionales = new HashSet<AntecedenteEducacional>(0);

	public NivelDocente() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_NIDO_X_NIDO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_NIDO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "C_NIDO", unique = true, nullable = false, length = 5)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "D_NIDO", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelDocente")
	public Set<AntecedenteEducacional> getAntecedenteEducacionales() {
		return this.antecedenteEducacionales;
	}

	public void setAntecedenteEducacionales(Set<AntecedenteEducacional> antecedenteEducacionales) {
		this.antecedenteEducacionales = antecedenteEducacionales;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NivelDocente))
			return false;
		NivelDocente castOther = (NivelDocente) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion;
	}

}
