package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 03-oct-2011 16:27:55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * NivelConvalidado generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_NIVELES_CONVALIDADOS", uniqueConstraints = @UniqueConstraint(columnNames = "C_NICO"))
public class NivelConvalidado implements java.io.Serializable {

	private static final long serialVersionUID = 4970350569606981005L;

	private Long id;
	private Date version;
	private String codigo;
	private String descripcion;
	private Boolean activo;
	private String codUsuarioBloq;
	private Set<EntiotorgNivconv> entiotorgNivconves = new HashSet<EntiotorgNivconv>(0);
	private Set<MatConvalNivConval> matConvalNivConvales = new HashSet<MatConvalNivConval>(0);
	private Set<AntecedenteEducacional> antecedentesEducacionales = new HashSet<AntecedenteEducacional>(0);

	public NivelConvalidado() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_NICO_X_NICO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_NICO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "C_NICO", unique = true, nullable = false, length = 5)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "D_NICO", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelConvalidado")
	public Set<EntiotorgNivconv> getEntiotorgNivconves() {
		return this.entiotorgNivconves;
	}

	public void setEntiotorgNivconves(Set<EntiotorgNivconv> entiotorgNivconves) {
		this.entiotorgNivconves = entiotorgNivconves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelConvalidado")
	public Set<MatConvalNivConval> getMatConvalNivConvales() {
		return this.matConvalNivConvales;
	}

	public void setMatConvalNivConvales(Set<MatConvalNivConval> matConvalNivConvales) {
		this.matConvalNivConvales = matConvalNivConvales;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelConvalidado")
	public Set<AntecedenteEducacional> getAntecedentesEducacionales() {
		return antecedentesEducacionales;
	}

	public void setAntecedentesEducacionales(
			Set<AntecedenteEducacional> antecedentesEducacionales) {
		this.antecedentesEducacionales = antecedentesEducacionales;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NivelConvalidado))
			return false;
		NivelConvalidado castOther = (NivelConvalidado) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion;
	}

}
