package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 18-oct-2011 11:46:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * NivelEducacional generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_NIVELES_EDUCACIONALES")
public class NivelEducacional implements java.io.Serializable, Comparable<NivelEducacional> {

	

	/**
	 * 
	 */
	private static final long serialVersionUID = -3199044349023508680L;
	private Long id;
	private Date version;
	private NivelEstudioFormal nivelEstudioFormal;
	private NivelEstudioFormal nivelEstudioFormalConv;
	private String codigo;
	private String descripcion;
	private Boolean activo;
	private Long codSiaper;
	private String codUsuarioBloq;
	private Set<AntecedenteEducacional> antecedentesEducacionales = new HashSet<AntecedenteEducacional>(0);
	private Set<MineducNivelEducacional> mineducNivelEducacional = new HashSet<MineducNivelEducacional>();
	

	public NivelEducacional() {
	}

	public NivelEducacional(long id) {
		this.id = id;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_NIED_X_NIED")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_NIED", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NIEF_X_NIEF", nullable = false)
	public NivelEstudioFormal getNivelEstudioFormal() {
		return this.nivelEstudioFormal;
	}

	public void setNivelEstudioFormal(NivelEstudioFormal nivelEstudioFormal) {
		this.nivelEstudioFormal = nivelEstudioFormal;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NIEF_X_NIEF_CONV", nullable = false)
	public NivelEstudioFormal getNivelEstudioFormalConv() {
		return nivelEstudioFormalConv;
	}
	
	public void setNivelEstudioFormalConv(NivelEstudioFormal nivelEstudioFormalConv) {
		this.nivelEstudioFormalConv = nivelEstudioFormalConv;
	}
	
	@Column(name = "C_NIED", nullable = false, length = 5)
	public String getCodigo() {
		return this.codigo;
	}


	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "D_NIED", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "L_ACTIVO", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEducacional")
	public Set<AntecedenteEducacional> getAntecedentesEducacionales() {
		return this.antecedentesEducacionales;
	}

	public void setAntecedentesEducacionales(Set<AntecedenteEducacional> antecedenteEducacionales) {
		this.antecedentesEducacionales = antecedenteEducacionales;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEducacional")
	public Set<MineducNivelEducacional> getMineducNivelEducacional() {
		return mineducNivelEducacional;
	}

	public void setMineducNivelEducacional(
			Set<MineducNivelEducacional> mineducNivelEducacional) {
		this.mineducNivelEducacional = mineducNivelEducacional;
	}
	
	@Column(name = "S_NIED", precision = 12, scale = 0)
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}

	public int compareTo(NivelEducacional nivel) {
		return (int) (this.id - nivel.id);
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NivelEducacional))
			return false;
		NivelEducacional castOther = (NivelEducacional) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion;
	}

}
