package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 28-oct-2011 13:37:46 by Hibernate Tools 3.4.0.CR1

import static jakarta.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * Pais generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_PAISES")
public class Pais implements java.io.Serializable, Comparable<Pais> {

	private static final long serialVersionUID = 5090411405925677798L;

	private Long id;
	private Date version;
	private Long codSiaper;
	private String descripcion;
	private Boolean activo;
	private String codUsuarioBloq;
	private String descripcionWSRegCivil;
	//private Set<CasoDocumento> casoDocumentos = new HashSet<CasoDocumento>(0);
	//private Set<AntecedenteEducacional> antecedenteEducacionales = new HashSet<AntecedenteEducacional>(0);

	public Pais() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_PAIS_X_PAIS")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_PAIS", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "S_PAIS", precision = 12, nullable=false, scale = 0)
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}
	
	@Column(name = "D_PAIS", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "D_PAIS_REGCIVIL")
	public String getDescripcionWSRegCivil() {
		return descripcionWSRegCivil;
	}

	public void setDescripcionWSRegCivil(String descripcionWSRegCivil) {
		this.descripcionWSRegCivil = descripcionWSRegCivil;
	}

	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<CasoDocumento> getCasoDocumentos() {
		return this.casoDocumentos;
	}

	public void setCasoDocumentos(Set<CasoDocumento> casoDocumentos) {
		this.casoDocumentos = casoDocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<AntecedenteEducacional> getAntecedenteEducacionales() {
		return this.antecedenteEducacionales;
	}

	public void setAntecedenteEducacionales(Set<AntecedenteEducacional> antecedenteEducacionales) {
		this.antecedenteEducacionales = antecedenteEducacionales;
	}
*/
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Pais))
			return false;
		Pais castOther = (Pais) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	public int compareTo(Pais pais) {
		return this.getDescripcion().compareTo(pais.getDescripcion());
	}
	
}
