package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 05-mar-2012 9:06:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * PanelSuplenciaReemplazo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_PANEL_SUPL_REEMPLAZO")
public class PanelSuplenciaReemplazo implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6749323285784710281L;
	private Long id;
	private Date version;
	private String codUsuarioBloq;
	private CasoDocumento casoDocumento;
	private Boolean totalTramite;
	private Date fechaDesde;
	private Boolean mdat;
	private Boolean aceptaDecalogo;
	private Date fechaHasta;
	private Set<FuncSuplidoReemplazado> funcSuplidoReemplazados = new HashSet<FuncSuplidoReemplazado>(0);

	public PanelSuplenciaReemplazo() {
	}

	public PanelSuplenciaReemplazo(CasoDocumento casoDocumento,
			Boolean totalTramite) {
		this.casoDocumento = casoDocumento;
		this.totalTramite = totalTramite;
	}

	public PanelSuplenciaReemplazo(CasoDocumento casoDocumento,
			Boolean totalTramite, Date fechaDesde, Boolean mdat,
			Date fechaHasta, Set<FuncSuplidoReemplazado> funcSuplidoReemplazados) {
		this.casoDocumento = casoDocumento;
		this.totalTramite = totalTramite;
		this.fechaDesde = fechaDesde;
		this.mdat = mdat;
		this.fechaHasta = fechaHasta;
		this.funcSuplidoReemplazados = funcSuplidoReemplazados;
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_PASR_X_PASR")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_PASR", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CADO_X_CADO", nullable = false)
	public CasoDocumento getCasoDocumento() {
		return this.casoDocumento;
	}

	public void setCasoDocumento(CasoDocumento casoDocumento) {
		this.casoDocumento = casoDocumento;
	}

	@Column(name = "L_TOTAL_TRAMITE", length = 1, nullable = false)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getTotalTramite() {
		return this.totalTramite;
	}

	public void setTotalTramite(Boolean totalTramite) {
		this.totalTramite = totalTramite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_DESDE", length = 7)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Column(name = "L_MDAT", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getMdat() {
		return this.mdat;
	}

	public void setMdat(Boolean mdat) {
		this.mdat = mdat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_HASTA", length = 7)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "panelSuplenciaReemplazo", cascade = CascadeType.ALL)
	public Set<FuncSuplidoReemplazado> getFuncSuplidoReemplazados() {
		return this.funcSuplidoReemplazados;
	}

	public void setFuncSuplidoReemplazados(
			Set<FuncSuplidoReemplazado> funcSuplidoReemplazados) {
		this.funcSuplidoReemplazados = funcSuplidoReemplazados;
	}
	
	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@Column(name = "L_ACEPTA_DECALOGO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getAceptaDecalogo() {
		return aceptaDecalogo;
	}

	public void setAceptaDecalogo(Boolean aceptaDecalogo) {
		this.aceptaDecalogo = aceptaDecalogo;
	}

	public PanelSuplenciaReemplazo clone() {
		try {
			return (PanelSuplenciaReemplazo) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}
}
