package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 03-oct-2011 16:27:55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_PERFILES", uniqueConstraints = @UniqueConstraint(columnNames = "S_PERF"))
public class Perfil implements java.io.Serializable {

	private static final long serialVersionUID = -8151377835750452419L;

	private Long id;
	private Date version;
	private String nombre;
	private String descripcion;
	private String descripcionExterna;
	private Boolean activo;
	private String codUsuarioBloq;
	private Boolean interno;
	private Set<PerfilEstado> perfilesEstado = new HashSet<PerfilEstado>(0);
//	private Set<UsuarioPerfil> usuariosPerfil = new HashSet<UsuarioPerfil>(0);
//	private Set<Subrogacion> subrogaciones = new HashSet<Subrogacion>(0);

	public Perfil() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_PERF_X_PERF")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_PERF", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "S_PERF", unique = true, nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "D_PERF", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "D_PERF_EXT", nullable = true, length = 150)
	public String getDescripcionExterna() {
		return this.descripcionExterna;
	}

	public void setDescripcionExterna(String descripcionExterna) {
		this.descripcionExterna = descripcionExterna;
	}

	@Column(name = "L_ACTIVO", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "L_INTERNO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getInterno() {
		return this.interno;
	}

	public void setInterno(Boolean interno) {
		this.interno = interno;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<PerfilEstado> getPerfilesEstado() {
		return this.perfilesEstado;
	}

	public void setPerfilesEstado(Set<PerfilEstado> perfilEstados) {
		this.perfilesEstado = perfilEstados;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
//	public Set<UsuarioPerfil> getUsuariosPerfil() {
//		return this.usuariosPerfil;
//	}
//
//	public void setUsuariosPerfil(Set<UsuarioPerfil> usuarioPerfiles) {
//		this.usuariosPerfil = usuarioPerfiles;
//	}
	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
//	public Set<Subrogacion> getSubrogaciones() {
//		return this.subrogaciones;
//	}
//
//	public void setSubrogaciones(Set<Subrogacion> subrogaciones) {
//		this.subrogaciones = subrogaciones;
//	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Perfil))
			return false;
		Perfil castOther = (Perfil) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Nombre: " + nombre + ", descripción: " + descripcion;
	}

}