package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 05-mar-2012 9:06:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * PeriodoDocRespaldo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_PERIODOS_DOC_RESPALDO")
public class PeriodoDocRespaldo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8937266842753313116L;
	private Long id;
	private Date version;
	private DocumentoRespaldo documentoRespaldo;
	private String idPeriodoSeleccionado; //S_PERIODO
	private String codUsuarioBloq;
	private Date fechaDesdeRespaldo;
	private Date fechaHastaRespaldo;
	private Date fechaDesdeDisponible;
	private Date fechaHastaDisponible;

	public PeriodoDocRespaldo() {
	}

	public PeriodoDocRespaldo(DocumentoRespaldo documentoRespaldo) {
		this.documentoRespaldo = documentoRespaldo;
	}

	public PeriodoDocRespaldo(DocumentoRespaldo documentoRespaldo,
			Date fechaDesdeRespaldo, Date fechaHastaRespaldo,
			Date fechaDesdeDisponible, Date fechaHastaDisponible) {
		this.documentoRespaldo = documentoRespaldo;
		this.fechaDesdeRespaldo = fechaDesdeRespaldo;
		this.fechaHastaRespaldo = fechaHastaRespaldo;
		this.fechaDesdeDisponible = fechaDesdeDisponible;
		this.fechaHastaDisponible = fechaHastaDisponible;
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_PEDR_X_PEDR")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_PEDR", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DORE_X_DORE", nullable = false)
	public DocumentoRespaldo getDocumentoRespaldo() {
		return this.documentoRespaldo;
	}

	public void setDocumentoRespaldo(DocumentoRespaldo documentoRespaldo) {
		this.documentoRespaldo = documentoRespaldo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_DESDE_RESPALDO", nullable = false, length = 7)
	public Date getFechaDesdeRespaldo() {
		return this.fechaDesdeRespaldo;
	}

	public void setFechaDesdeRespaldo(Date fechaDesdeRespaldo) {
		this.fechaDesdeRespaldo = fechaDesdeRespaldo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_HASTA_RESPALDO", length = 7)
	public Date getFechaHastaRespaldo() {
		return this.fechaHastaRespaldo;
	}

	public void setFechaHastaRespaldo(Date fechaHastaRespaldo) {
		this.fechaHastaRespaldo = fechaHastaRespaldo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_DESDE_DISPONIBLE", length = 7)
	public Date getFechaDesdeDisponible() {
		return this.fechaDesdeDisponible;
	}

	public void setFechaDesdeDisponible(Date fechaDesdeDisponible) {
		this.fechaDesdeDisponible = fechaDesdeDisponible;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_HASTA_DISPONIBLE", length = 7)
	public Date getFechaHastaDisponible() {
		return this.fechaHastaDisponible;
	}

	public void setFechaHastaDisponible(Date fechaHastaDisponible) {
		this.fechaHastaDisponible = fechaHastaDisponible;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "S_PERIODO", length = 15)
	public String getIdPeriodoSeleccionado() {
		return idPeriodoSeleccionado;
	}

	public void setIdPeriodoSeleccionado(String idPeriodoSeleccionado) {
		this.idPeriodoSeleccionado = idPeriodoSeleccionado;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		} else {
			if (obj instanceof PeriodoDocRespaldo) {
				PeriodoDocRespaldo periodo = (PeriodoDocRespaldo) obj;
				if (periodo.getId() != null) {
					if (periodo.getId().equals(this.getId())) {
						return true;
					} else {
						return false;
					}
				} else {
					return false;
				}
			} else {
				return false;
			}
		}
	}
}
