package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 07-jul-2017 9:24:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * PeticionesMasiva generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_PETICIONES_MASIVA")
public class PeticionMasiva implements Serializable {

	private static final long serialVersionUID = -1995867434806437165L;
	private Long id;
	private Fichero fichero;
	private Materia materia;
	private String usuario;
	private String numDocu;
	private String procesado;
	private Long nodoAsignado;
	private Date version;
	private Set<CargaMasiva> cargaMasiva = new HashSet<CargaMasiva>(0);
	private Servicio servicioCreador;

	public PeticionMasiva() {
	}

	public PeticionMasiva(Fichero ficheros, 
							Materia materias, 
							String usuario, 
							String numDocu, 
							String procesado,
							Long nodoAsignado,
							Set<CargaMasiva> cargaMasiva,
							Servicio servicioCreador) {
		
		this.fichero = ficheros;
		this.materia = materias;
		this.usuario = usuario;
		this.numDocu = numDocu;
		this.procesado = procesado;
		this.nodoAsignado = nodoAsignado;
		this.cargaMasiva = cargaMasiva;
		this.servicioCreador = servicioCreador;
	}

	public PeticionMasiva(Fichero ficheros,
	                        Materia materias,
	                        String usuario,
	                        String numDocu,
	                        String procesado,
	                        Long nodoAsignado,
	                        Date version,
	                        Set<CargaMasiva> cargaMasiva,
	                        Servicio servicioCreador) {

		this.fichero = ficheros;
		this.materia = materias;
		this.usuario = usuario;
		this.numDocu = numDocu;
		this.procesado = procesado;
		this.nodoAsignado = nodoAsignado;
		this.version = version;
		this.cargaMasiva = cargaMasiva;
		this.servicioCreador = servicioCreador;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_PEMA_X_PEMA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_PEMA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FICH_X_FICH", nullable = false)
	public Fichero getFichero() {
		return this.fichero;
	}

	public void setFichero(Fichero ficheros) {
		this.fichero = ficheros;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATE_X_MATE", nullable = false)
	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materias) {
		this.materia = materias;
	}

	@Column(name = "C_USUARIO", length = 30)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "T_NUM_DOCU", nullable = false, length = 150)
	public String getNumDocu() {
		return this.numDocu;
	}

	public void setNumDocu(String numDocu) {
		this.numDocu = numDocu;
	}

	@Column(name = "L_PROCESADO", nullable = false, length = 1)
	public String getProcesado() {
		return this.procesado;
	}

	public void setProcesado(String procesado) {
		this.procesado = procesado;
	}

	@Column(name = "NODO_ASIGNADO", length = 3)
	public Long getNodoAsignado() {
		return nodoAsignado;
	}

	public void setNodoAsignado(Long nodoAsignado) {
		this.nodoAsignado = nodoAsignado;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peticionMasiva", cascade = CascadeType.ALL)
	public Set<CargaMasiva> getCargaMasiva() {
		return this.cargaMasiva;
	}

	public void setCargaMasiva(Set<CargaMasiva> cargaMasiva) {
		this.cargaMasiva = cargaMasiva;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SERV_X_SERV_E", nullable = false)
	public Servicio getServicioCreador() {
		return servicioCreador;
	}
	
	public void setServicioCreador(Servicio servicioCreador) {
		this.servicioCreador = servicioCreador;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PeticionMasiva))
			return false;
		PeticionMasiva castOther = (PeticionMasiva) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
}