package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 28-oct-2011 13:37:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;
import jakarta.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

/**
 * Region generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_REGIONES")
public class Region implements java.io.Serializable, Comparable<Region> {

	private static final long serialVersionUID = -5335725667377824396L;

	private Long id;
	private Date version;
	private Long codSiaper;
	private String descripcion;
	private String descripcionAlternativa;
	private Boolean activo;
	private String codUsuarioBloq;
	private String configFirma;
	private String configFirma2;
	private String usuarioConfigFirma;
	private String rubricaContrURI;
//	private Set<Comuna> comunas = new HashSet<Comuna>(0);
//	private Set<DatoRaiz> datoRaizes = new HashSet<DatoRaiz>(0);
//	private Set<Servicio> servicios = new HashSet<Servicio>(0);
//	private Set<CasoMasivo> casosMasivos = new HashSet<CasoMasivo>(0);

	private RegionSiaper regionSiaper = new RegionSiaper();	
	
	public Region() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_REGI_X_REGI")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_REGI", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "S_REGI", precision = 12, nullable=false, scale = 0)
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}
	
	@Column(name = "D_REGI", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@Column(name = "T_CONF_FIRMA", length = 50)
	public String getConfigFirma() {
		return configFirma;
	}

	public void setConfigFirma(String configFirma) {
		this.configFirma = configFirma;
	}

	@Column(name = "T_CONF_FIRMA_2")
	public String getConfigFirma2() {
		return configFirma2;
	}

	public void setConfigFirma2(String configFirma2) {
		this.configFirma2 = configFirma2;
	}

	@Column(name = "T_USUARIO_CONF_FIRMA")
	public String getUsuarioConfigFirma() {
		return usuarioConfigFirma;
	}

	public void setUsuarioConfigFirma(String usuarioConfigFirma) {
		this.usuarioConfigFirma = usuarioConfigFirma;
	}

	@Column(name = "T_RUBRICA_CONTR_URI")
	public String getRubricaContrURI() {
		return rubricaContrURI;
	}

	public void setRubricaContrURI(String rubricaContrURI) {
		this.rubricaContrURI = rubricaContrURI;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Comuna> getComunas() {
		return this.comunas;
	}

	public void setComunas(Set<Comuna> comunas) {
		this.comunas = comunas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<DatoRaiz> getDatoRaizes() {
		return this.datoRaizes;
	}

	public void setDatoRaizes(Set<DatoRaiz> datoRaizes) {
		this.datoRaizes = datoRaizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(Set<Servicio> servicios) {
		this.servicios = servicios;
	}
*/
	
	@Column(name = "D_REG_DES")
	public String getDescripcionAlternativa() {
		return this.descripcionAlternativa;
	}

	public void setDescripcionAlternativa(String descripcionAlternativa) {
		this.descripcionAlternativa = descripcionAlternativa;
	}
	
	
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Region))
			return false;
		Region castOther = (Region) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public int compareTo(Region reg) {
		return this.getDescripcion().compareTo(reg.getDescripcion());
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<CasoMasivo> getCasosMasivos() {
		return this.casosMasivos;
	}

	public void setCasosMasivos(Set<CasoMasivo> casosMasivos) {
		this.casosMasivos = casosMasivos;
	}
	*/
	@ManyToOne
	@JoinColumn(name="S_REGI", insertable=false, updatable=false)
	public RegionSiaper getRegionSiaper() {
		return regionSiaper;
	}

	public void setRegionSiaper(RegionSiaper regionSiaper) {
		this.regionSiaper = regionSiaper;
	}
}
