package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * Remuneracion generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_REMUNERACIONES", uniqueConstraints = @UniqueConstraint(columnNames = "S_REMU"))
public class Remuneracion implements java.io.Serializable {

	private static final long serialVersionUID = 7625258532712057591L;

	private Long id;
	private Date version;
	private Long codSiaper;
	private String descripcion;
	private String codUsuarioBloq;
	private Set<Dotacion> dotacionesRemuneracionHoras = new HashSet<Dotacion>(0);
	private Set<Dotacion> dotacionesRemuneracionGrado = new HashSet<Dotacion>(0);

	public Remuneracion() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_REMU_X_REMU")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_REMU", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "S_REMU", precision = 12, nullable=false, scale = 0)
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}
	
	@Column(name = "D_REMU", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "remuneracionHoras")
	public Set<Dotacion> getDotacionesRemuneracionHoras() {
		return this.dotacionesRemuneracionHoras;
	}

	public void setDotacionesRemuneracionHoras(Set<Dotacion> dotacionesForRemuXRemuH) {
		this.dotacionesRemuneracionHoras = dotacionesForRemuXRemuH;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "remuneracionGrado")
	public Set<Dotacion> getDotacionesRemuneracionGrado() {
		return this.dotacionesRemuneracionGrado;
	}

	public void setDotacionesRemuneracionGrado(Set<Dotacion> dotacionesForRemuXRemu) {
		this.dotacionesRemuneracionGrado = dotacionesForRemuXRemu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Remuneracion))
			return false;
		Remuneracion castOther = (Remuneracion) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Nombre: " + codSiaper + ", descripción: " + descripcion;
	}

}
