package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 13-oct-2011 16:37:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * Reporte generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_REPORTES", uniqueConstraints = @UniqueConstraint(columnNames = "C_REPO"))
public class Reporte implements java.io.Serializable, Entidad {

	private static final long serialVersionUID = -7922582709092929582L;

	private Long id;
	private Date version;
	private String codigo;
	private String nombre;
	private String path;
	private String tipoReporte;
	private Boolean periodoEmision;
	private Boolean excedeLimites;
	private Boolean calidadJuridica;
	private Boolean desagregacionAdmin;
	private Boolean desagregacionTerri;
	private String codUsuarioBloq;
	private Set<ReporteServicio> serviciosReporte = new HashSet<ReporteServicio>(0);
	private Set<TipoCalidadjReporte> tiposcalidadjReportes = new HashSet<TipoCalidadjReporte>(0);

	public Reporte() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_REPO_X_REPO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_REPO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "C_REPO", unique = true, nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "T_NOMBRE", nullable = false, length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "T_PATH", nullable = false, length = 500)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "V_TIPO_REPORTE", length = 1)
	public String getTipoReporte() {
		return this.tipoReporte;
	}

	public void setTipoReporte(String tipoReporte) {
		this.tipoReporte = tipoReporte;
	}

	@Column(name = "L_PERIODO_EMISION", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getPeriodoEmision() {
		return this.periodoEmision;
	}

	public void setPeriodoEmision(Boolean periodoEmision) {
		this.periodoEmision = periodoEmision;
	}

	@Column(name = "L_EXCEDE_LIMITES", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getExcedeLimites() {
		return this.excedeLimites;
	}

	public void setExcedeLimites(Boolean excedeLimites) {
		this.excedeLimites = excedeLimites;
	}

	@Column(name = "L_CALIDAD_JURIDICA", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getCalidadJuridica() {
		return this.calidadJuridica;
	}

	public void setCalidadJuridica(Boolean calidadJuridica) {
		this.calidadJuridica = calidadJuridica;
	}

	@Column(name = "L_DESAGREGACION_ADMIN", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getDesagregacionAdmin() {
		return this.desagregacionAdmin;
	}

	public void setDesagregacionAdmin(Boolean desagregacionAdmin) {
		this.desagregacionAdmin = desagregacionAdmin;
	}

	@Column(name = "L_DESAGREGACION_TERRI", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getDesagregacionTerri() {
		return this.desagregacionTerri;
	}

	public void setDesagregacionTerri(Boolean desagregacionTerri) {
		this.desagregacionTerri = desagregacionTerri;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reporte")
	public Set<TipoCalidadjReporte> getTiposcalidadjReportes() {
		return this.tiposcalidadjReportes;
	}

	public void setTiposcalidadjReportes(
			Set<TipoCalidadjReporte> tiposcalidadjReportes) {
		this.tiposcalidadjReportes = tiposcalidadjReportes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reporte")
	public Set<ReporteServicio> getServiciosReporte() {
		return this.serviciosReporte;
	}

	public void setServiciosReporte(Set<ReporteServicio> reporteServicios) {
		this.serviciosReporte = reporteServicios;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Reporte))
			return false;
		Reporte castOther = (Reporte) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	public String toString() {
		return "Código: " + codigo + ", nombre: " + nombre;
	}

}
