package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 06-mar-2012 11:28:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * ReqartCaminoTraGen generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_REQART_CAMINO_TRA_GEN")
public class ReqartCaminoTraGen implements java.io.Serializable, Comparable<ReqartCaminoTraGen> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7296044355933090235L;
	private Long id;
	private Date version;
	private CaminoTraGen caminoTraGen;
	private RequisitoArticulo requisitoArticulo;
	private Boolean alternativa;
	private long numOrden;
	private String codUsuarioBloq;

	public ReqartCaminoTraGen() {
	}

	public ReqartCaminoTraGen(CaminoTraGen caminoTraGen,
			RequisitoArticulo requisitoArticulo, Boolean alternativa,
			long numOrden) {
		this.caminoTraGen = caminoTraGen;
		this.requisitoArticulo = requisitoArticulo;
		this.alternativa = alternativa;
		this.numOrden = numOrden;
	}

	public ReqartCaminoTraGen(CaminoTraGen caminoTraGen,
			RequisitoArticulo requisitoArticulo, Boolean alternativa,
			long numOrden, String codUsuarioBloq) {
		this.caminoTraGen = caminoTraGen;
		this.requisitoArticulo = requisitoArticulo;
		this.alternativa = alternativa;
		this.numOrden = numOrden;
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_RCTG_X_RCTG")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_RCTG", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@ManyToOne
	@JoinColumn(name = "CTRG_X_CTRG", nullable = false)
	public CaminoTraGen getCaminoTraGen() {
		return this.caminoTraGen;
	}

	public void setCaminoTraGen(CaminoTraGen caminoTraGen) {
		this.caminoTraGen = caminoTraGen;
	}

	@ManyToOne
	@JoinColumn(name = "REAR_X_REAR", nullable = false)
	public RequisitoArticulo getRequisitoArticulo() {
		return this.requisitoArticulo;
	}

	public void setRequisitoArticulo(RequisitoArticulo requisitoArticulo) {
		this.requisitoArticulo = requisitoArticulo;
	}

	@Column(name = "L_ALTERNATIVA", length = 1, nullable = false)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getAlternativa() {
		return this.alternativa;
	}

	public void setAlternativa(Boolean alternativa) {
		this.alternativa = alternativa;
	}
	
	@Column(name = "N_ORDEN", nullable = false, precision = 10, scale = 0)
	public long getNumOrden() {
		return this.numOrden;
	}

	public void setNumOrden(long numOrden) {
		this.numOrden = numOrden;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	public int compareTo(ReqartCaminoTraGen rc) {
		return (int) (this.numOrden - rc.numOrden);
	}
	public String toString()
	{
		String res = "-";
		try {
			res = this.requisitoArticulo.getRequisito().getCuestionario();
		}catch(Exception e){
		}
		return "("+this.numOrden+")"+res+"="+this.alternativa;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReqartCaminoTraGen))
			return false;
		ReqartCaminoTraGen castOther = (ReqartCaminoTraGen) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

}
