package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * RequisitoArticulo generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_REQUISITOS_ARTICULO", uniqueConstraints = @UniqueConstraint(columnNames = { "REQU_X_REQU", "ARTI_X_ARTI" }))
public class RequisitoArticulo implements java.io.Serializable, Cloneable, Comparable {

	private static final long serialVersionUID = -95639872694814182L;

	private Long id;
	private Date version;
	private Articulo articulo;
	private Requisito requisito;
	private String codUsuarioBloq;

	public RequisitoArticulo() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_REAR_X_REAR")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_REAR", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ARTI_X_ARTI", nullable = false)
	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQU_X_REQU", nullable = false)
	public Requisito getRequisito() {
		return this.requisito;
	}

	public void setRequisito(Requisito requisito) {
		this.requisito = requisito;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	public RequisitoArticulo clone() {
		try {
			return (RequisitoArticulo) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RequisitoArticulo))
			return false;
		RequisitoArticulo castOther = (RequisitoArticulo) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	public int compareTo (Object o)
	{
		RequisitoArticulo ra = (RequisitoArticulo)o;
		if (ra != null) {
			if (ra.requisito != null && requisito != null) {
				if (ra.requisito.getId() != null && requisito.getId() != null) {
					return requisito.compareTo(ra.requisito);
				}
			}
		}
		return 0;
	}
	
	public String toString() {
		return "Artículo: (" + articulo + "), requisito: (" + requisito + ")";
	}

}
