package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * Requisito generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_REQUISITOS", uniqueConstraints = @UniqueConstraint(columnNames = "C_REQUISITO"))
public class Requisito implements java.io.Serializable, Comparable {

	private static final long serialVersionUID = -4849376491078857460L;

	private Long id;
	private Date version;
	private Warning warningAlternativaSi;
	private Warning warningAlternativaNo;
	private MedioVerificacion medioVerificacionAlternativaSi;
	private MedioVerificacion medioVerificacionAlternativaNo;
	private String codigo;
	private String texto;
	private String cuestionario;
	private String codUsuarioBloq;
	private Boolean revalidable;
	private Boolean certificable;
	private Set<RequisitoArticulo> requisitoArticulos = new HashSet<RequisitoArticulo>(0);

	public Requisito() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_REQU_X_REQU")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_REQU", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WARN_ALTERNAT_SI")
	public Warning getWarningAlternativaSi() {
		return this.warningAlternativaSi;
	}

	public void setWarningAlternativaSi(Warning warningByWarnAlternatSi) {
		this.warningAlternativaSi = warningByWarnAlternatSi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WARN_ALTERNAT_NO")
	public Warning getWarningAlternativaNo() {
		return this.warningAlternativaNo;
	}

	public void setWarningAlternativaNo(Warning warningByWarnAlternatNo) {
		this.warningAlternativaNo = warningByWarnAlternatNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEVE_ALTERNAT_SI")
	public MedioVerificacion getMedioVerificacionAlternativaSi() {
		return this.medioVerificacionAlternativaSi;
	}

	public void setMedioVerificacionAlternativaSi(MedioVerificacion medioVerificacionByMeveAlternatSi) {
		this.medioVerificacionAlternativaSi = medioVerificacionByMeveAlternatSi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEVE_ALTERNAT_NO")
	public MedioVerificacion getMedioVerificacionAlternativaNo() {
		return this.medioVerificacionAlternativaNo;
	}

	public void setMedioVerificacionAlternativaNo(MedioVerificacion medioVerificacionByMeveAlternatNo) {
		this.medioVerificacionAlternativaNo = medioVerificacionByMeveAlternatNo;
	}

	@Column(name = "C_REQUISITO", unique = true, nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codRequisito) {
		this.codigo = codRequisito;
	}

	@Column(name = "T_TEXTO", length = 4000)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "T_CUESTIONARIO", nullable = false, length = 500)
	public String getCuestionario() {
		return this.cuestionario;
	}

	public void setCuestionario(String cuestionario) {
		this.cuestionario = cuestionario;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requisito", cascade=CascadeType.ALL)
	public Set<RequisitoArticulo> getRequisitoArticulos() {
		return this.requisitoArticulos;
	}

	public void setRequisitoArticulos(Set<RequisitoArticulo> requisitoArticulos) {
		this.requisitoArticulos = requisitoArticulos;
	}

	@Column(name = "L_REVALIDABLE", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)	
	public Boolean getRevalidable() {
		return revalidable;
	}

	public void setRevalidable(Boolean revalidable) {
		this.revalidable = revalidable;
	}

	@Column(name = "L_CERTIFICABLE", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getCertificable() {
		return certificable;
	}

	public void setCertificable(Boolean certificable) {
		this.certificable = certificable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Requisito))
			return false;
		Requisito castOther = (Requisito) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public int compareTo(Object o)
	{
		Requisito r = (Requisito)o;
		long dif = 0;
		if (id != null && r.id != null) {
			 dif = restar( id,  r.id);
		}
		if (dif < 0)
			return -1;
		else if (dif > 0)
			return 1;
		else
			return 0;
	}
	private static final long restar(long x, long y)
	{
		return x - y;
	}
	
//	public String toString() {
//		return "Código: " + codigo + ", pregunta: " + cuestionario;
//	}

	//add siaper-ru
	public String toStringJson() {
	    StringBuilder sb = new StringBuilder();
	    sb.append("{\n");

	    sb.append("  \"id\": ").append(id).append(",\n");
	    sb.append("  \"version\": ").append(version != null ? "\"" + version + "\"" : null).append(",\n");

	    sb.append("  \"warningAlternativaSi\": ").append(warningAlternativaSi != null ? "\"" + warningAlternativaSi.getId() + "\"" : null).append(",\n");
	    sb.append("  \"warningAlternativaNo\": ").append(warningAlternativaNo != null ? "\"" + warningAlternativaNo.getId() + "\"" : null).append(",\n");

	    sb.append("  \"medioVerificacionAlternativaSi\": ").append(medioVerificacionAlternativaSi != null ? "\"" + medioVerificacionAlternativaSi.getId() + "\"" : null).append(",\n");
	    sb.append("  \"medioVerificacionAlternativaNo\": ").append(medioVerificacionAlternativaNo != null ? "\"" + medioVerificacionAlternativaNo.getId() + "\"" : null).append(",\n");

	    sb.append("  \"codigo\": ").append(codigo != null ? "\"" + codigo + "\"" : null).append(",\n");
	    sb.append("  \"texto\": ").append(texto != null ? "\"" + texto + "\"" : null).append(",\n");
	    sb.append("  \"cuestionario\": ").append(cuestionario != null ? "\"" + cuestionario + "\"" : null).append(",\n");
	    sb.append("  \"codUsuarioBloq\": ").append(codUsuarioBloq != null ? "\"" + codUsuarioBloq + "\"" : null).append(",\n");

	    sb.append("  \"revalidable\": ").append(revalidable).append(",\n");
	    sb.append("  \"certificable\": ").append(certificable).append(",\n");

	    sb.append("  \"requisitoArticulos\": ").append(requisitoArticulos != null ? requisitoArticulos.size() : 0).append("\n");

	    sb.append("}");

	    return sb.toString();
	}

	
}
