package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 02-nov-2011 16:29:53 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_SERVICIOS", uniqueConstraints = @UniqueConstraint(columnNames = "C_SERV"))
public class Servicio implements Serializable, Comparable<Servicio> {

	private static final long serialVersionUID = -3900985520424351536L;

	private Long id;
	private Date version;
	private Servicio servicio;
	private TipoServicio tipoServicio;
	private String codigo;
	private Long codSiaper;
	private String descripcion;
	private Boolean activo;
	private String codUsuarioBloq;
	private Boolean generaNum;
	private Integer secuencial;
	private Short anioSecuencial;
	private Set<Servicio> servicios = new HashSet<Servicio>(0);
//	private Set<PlantaServicio> plantas = new HashSet<PlantaServicio>(0);
//	private Set<Dotacion> dotaciones = new HashSet<Dotacion>(0);
//	private Set<MateriaServicio> materiasServicioOperado = new HashSet<MateriaServicio>(0);
//	private Set<Documento> documentosEmitidos = new HashSet<Documento>(0);
//	private Set<Documento> documentosRecibidos = new HashSet<Documento>(0);
//	private Set<NotificacionCaso> notificaciones = new HashSet<NotificacionCaso>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<ReporteServicio> reportesServicio = new HashSet<ReporteServicio>(0);
	private Set<TipoDocumentosServicio> tipoDocumentosServicio = new HashSet<TipoDocumentosServicio>(0);
//	private Set<Documento> documentos = new HashSet<Documento>(0);
//	private Set<MateriaServicio> materiasServicioOperante = new HashSet<MateriaServicio>(0);
//	private Set<FirmaDoc> firmasServicio = new HashSet<FirmaDoc>(0);
//	private Set<Formulario> formularios = new HashSet<Formulario>(0);
//	private Set<ListaServicio> listas = new HashSet<ListaServicio>(0);
	private Comuna comuna;
	private Region region;	
	private String tipo;
	private Servicio subsecretaria;
	private Boolean esSubsecretaria;
//	private Set<Creador> creadorServicios = new HashSet<Creador>(0);
//	private Set<Creador> creadorServiciosOtro = new HashSet<Creador>(0);
//	private Set<FirmanteAdjunto> firmanteAdjunto = new HashSet<FirmanteAdjunto>(0);
	private Boolean servicioSeleccionado = false;
				
	// Atributos para la generacion de previews (No se almacenan en BBDD)
	private String descripcionSinEfectoPreview;
	
	private Fichero ficheroImagenServicio;
	
	private Set<Documento> documentosContraloria = new HashSet<Documento>(0);
	
	private Set<Subrogacion> subroganciasContraloria = new HashSet<Subrogacion>(0);
	
	private Set<Documento> documentosCreados = new HashSet<Documento>(0);
	
	private Set<Documento> documentosEmitidosOri = new HashSet<Documento>(0);
	/*
	private Set<ActoMasivo> actosMasivosSerEmi = new HashSet<ActoMasivo>(0);
	
	private Set<ActoMasivo> actosMasivosDepEmi = new HashSet<ActoMasivo>(0);
	
	private Set<CasoMasivo> casosMasivosSerDest = new HashSet<CasoMasivo>(0);
	
	private Set<CasoMasivo> casosMasivosDepDest = new HashSet<CasoMasivo>(0);
*/
	
	public Servicio() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_SERV_X_SERV")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_SERV", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV")
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TISE_X_TISE", nullable = false)
	public TipoServicio getTipoServicio() {
		return this.tipoServicio;
	}

	public void setTipoServicio(TipoServicio tipoServicio) {
		this.tipoServicio = tipoServicio;
	}

	@Column(name = "C_SERV", unique = true, nullable = false, length = 12)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "S_SERV", precision = 12, nullable=true, scale = 0)
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}
	
	@Column(name = "D_SERV", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}


	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "L_ACTIVO", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "L_GENERA_NUM", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getGeneraNum() {
		return this.generaNum;
	}

	public void setGeneraNum(Boolean generaNum) {
		this.generaNum = generaNum;
	}

	@Column(name = "N_SECUENCIAL", precision = 5, scale = 0)
	public Integer getSecuencial() {
		return this.secuencial;
	}

	public void setSecuencial(Integer numSecuencial) {
		this.secuencial = numSecuencial;
	}

	@Column(name = "N_ANIO_SECUENCIA", precision = 4, scale = 0)
	public Short getAnioSecuencial() {
		return this.anioSecuencial;
	}

	public void setAnioSecuencial(Short numAnioSecuencia) {
		this.anioSecuencial = numAnioSecuencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(Set<Servicio> servicios) {
		this.servicios = servicios;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<PlantaServicio> getPlantas() {
		return this.plantas;
	}

	public void setPlantas(Set<PlantaServicio> plantaServicios) {
		this.plantas = plantaServicios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<Dotacion> getDotaciones() {
		return this.dotaciones;
	}

	public void setDotaciones(Set<Dotacion> dotaciones) {
		this.dotaciones = dotaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioOperado")
	public Set<MateriaServicio> getMateriasServicioOperado() {
		return this.materiasServicioOperado;
	}

	public void setMateriasServicioOperado(Set<MateriaServicio> materiaServiciosForServXServOperado) {
		this.materiasServicioOperado = materiaServiciosForServXServOperado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioEmisor")
	public Set<Documento> getDocumentosEmitidos() {
		return this.documentosEmitidos;
	}

	public void setDocumentosEmitidos(Set<Documento> documentosForServXServE) {
		this.documentosEmitidos = documentosForServXServE;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioRecepcion")
	public Set<Documento> getDocumentosRecibidos() {
		return this.documentosRecibidos;
	}

	public void setDocumentosRecibidos(Set<Documento> documentosForServXServA) {
		this.documentosRecibidos = documentosForServXServA;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<NotificacionCaso> getNotificaciones() {
		return this.notificaciones;
	}

	public void setNotificaciones(Set<NotificacionCaso> notificacionCasos) {
		this.notificaciones = notificacionCasos;
	}
*/
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<ReporteServicio> getReportesServicio() {
		return this.reportesServicio;
	}

	public void setReportesServicio(Set<ReporteServicio> reporteServicios) {
		this.reportesServicio = reporteServicios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<TipoDocumentosServicio> getTipoDocumentoServicio() {
		return this.tipoDocumentosServicio;
	}

	public void setTipoDocumentoServicio(Set<TipoDocumentosServicio> tipoDocumentosServicio) {
		this.tipoDocumentosServicio = tipoDocumentosServicio;
	}

/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentosForServXServD) {
		this.documentos = documentosForServXServD;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioOperante")
	public Set<MateriaServicio> getMateriasServicioOperante() {
		return this.materiasServicioOperante;
	}

	public void setMateriasServicioOperante(Set<MateriaServicio> materiaServiciosForServXServOperante) {
		this.materiasServicioOperante = materiaServiciosForServXServOperante;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<FirmaDoc> getFirmasServicio() {
		return this.firmasServicio;
	}

	public void setFirmasServicio(Set<FirmaDoc> firmaDoces) {
		this.firmasServicio = firmaDoces;
	}
	*/
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMU_X_COMU")
	public Comuna getComuna() {
		return comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGI_X_REGI")
	public Region getRegion() {
		return region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}
	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<ListaServicio> getListas() {
		return listas;
	}

	public void setListas(Set<ListaServicio> listas) {
		this.listas = listas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<Formulario> getFormularios() {
		return formularios;
	}

	public void setFormularios(Set<Formulario> formularios) {
		this.formularios = formularios;
	}
	*/
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV1_X_SERV1")
	public Servicio getSubsecretaria() {
		return this.subsecretaria;
	}

	public void setSubsecretaria(Servicio subsecretaria) {
		this.subsecretaria = subsecretaria;
	}
	
	@Column(name = "L_SUBSECRETARIA", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getEsSubsecretaria() {
		return this.esSubsecretaria;
	}

	public void setEsSubsecretaria(Boolean esSubsecretaria) {
		this.esSubsecretaria = esSubsecretaria;
	}

	@Transient
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Transient
	public String getDescripcionSinEfectoPreview() {
		return descripcionSinEfectoPreview;
	}

	public void setDescripcionSinEfectoPreview(String descripcionSinEfectoPreview) {
		this.descripcionSinEfectoPreview = descripcionSinEfectoPreview;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Servicio))
			return false;
		Servicio castOther = (Servicio) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Código: " + getCodigo() + ", descripción: " + getDescripcion() + ", tipo: (" + getTipoServicio() + ")";
	}
	
	public int compareTo(Servicio servicio) {
		return this.getDescripcion().compareTo(servicio.getDescripcion());
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "FICH_X_FICH")
	public Fichero getFicheroImagenServicio() {
		return this.ficheroImagenServicio;
	}

	public void setFicheroImagenServicio(Fichero ficheroImagenServicio) {
		this.ficheroImagenServicio = ficheroImagenServicio;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contraloriaAsignada")
	public Set<Documento> getDocumentosContraloria() {
		return this.documentosContraloria;
	}

	public void setDocumentosContraloria(Set<Documento> documentosContraloria) {
		this.documentosContraloria = documentosContraloria;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<Subrogacion> getSubroganciasContraloria() {
		return this.subroganciasContraloria;
	}

	public void setSubroganciasContraloria(Set<Subrogacion> subroganciasContraloria) {
		this.subroganciasContraloria = subroganciasContraloria;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioCreador")
	public Set<Documento> getDocumentosCreados() {
		return this.documentosCreados;
	}

	public void setDocumentosCreados(Set<Documento> documentosCreados) {
		this.documentosCreados = documentosCreados;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioEmisorOriginal")
	public Set<Documento> getDocumentosEmitidosOri() {
		return this.documentosEmitidosOri;
	}

	public void setDocumentosEmitidosOri(Set<Documento> documentosEmitidosOri) {
		this.documentosEmitidosOri = documentosEmitidosOri;
	}
	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioEmitidos")
	public Set<Creador> getCreadorServicios() {
		return creadorServicios;
	}

	public void setCreadorServicios(Set<Creador> creadorServicios) {
		this.creadorServicios = creadorServicios;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioEmitidosOtro")
	public Set<Creador> getCreadorServiciosOtro() {
		return creadorServiciosOtro;
	}

	public void setCreadorServiciosOtro(Set<Creador> creadorServiciosOtro) {
		this.creadorServiciosOtro = creadorServiciosOtro;
	}
*/
	@Transient
	public Boolean getServicioSeleccionado() {
		return servicioSeleccionado;
	}

	public void setServicioSeleccionado(Boolean servicioSeleccionado) {
		this.servicioSeleccionado = servicioSeleccionado;
	}
	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioFirmante")
	public Set<FirmanteAdjunto> getFirmanteAdjunto() {
		return firmanteAdjunto;
	}

	public void setFirmanteAdjunto(Set<FirmanteAdjunto> firmanteAdjunto) {
		this.firmanteAdjunto = firmanteAdjunto;
	}
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioEmisor")
	public Set<ActoMasivo> getActosMasivosSerEmi() {
		return this.actosMasivosSerEmi;
	}

	public void setActosMasivosSerEmi(Set<ActoMasivo> actosMasivosSerEmi) {
		this.actosMasivosSerEmi = actosMasivosSerEmi;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dependenciaEmisora")
	public Set<ActoMasivo> getActosMasivosDepEmi() {
		return this.actosMasivosDepEmi;
	}

	public void setActosMasivosDepEmi(Set<ActoMasivo> actosMasivosDepEmi) {
		this.actosMasivosDepEmi = actosMasivosDepEmi;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<CasoMasivo> getCasosMasivosSerDest() {
		return this.casosMasivosSerDest;
	}

	public void setCasosMasivosSerDest(Set<CasoMasivo> casosMasivosSerDest) {
		this.casosMasivosSerDest = casosMasivosSerDest;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<CasoMasivo> getCasosMasivosDepDest() {
		return this.casosMasivosDepDest;
	}

	public void setCasosMasivosDepDest(Set<CasoMasivo> casosMasivosDepDest) {
		this.casosMasivosDepDest = casosMasivosDepDest;
	}
	*/
}