package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * ServicioWeb generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_SERVICIOS_WEB")
public class ServicioWeb implements java.io.Serializable {

	private static final long serialVersionUID = -4981860712205515235L;

	private Long id;
	private Date version;
	private String identificador;
	private String url;
	private String tipoEntrada;
	private Boolean activo;
	private String urlPrueba;
	private String paramPrueba;
	private String resultadoPrueba;
	private Boolean asincrono;
	private Set<ErrorServicioWeb> erroresServicioWeb = new HashSet<ErrorServicioWeb>();

	public ServicioWeb() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_SEWE_X_SEWE")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_SEWE", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "T_IDENTIFICADOR", length = 100)
	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	@Column(name = "T_URL", length = 500)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "V_TIPO_ENTRADA", length = 1)
	public String getTipoEntrada() {
		return this.tipoEntrada;
	}

	public void setTipoEntrada(String tipoEntrada) {
		this.tipoEntrada = tipoEntrada;
	}

	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "T_URL_PRUEBA", length = 500)
	public String getUrlPrueba() {
		return this.urlPrueba;
	}

	public void setUrlPrueba(String urlPrueba) {
		this.urlPrueba = urlPrueba;
	}

	@Column(name = "T_PARAM_PRUEBA", length = 500)
	public String getParamPrueba() {
		return this.paramPrueba;
	}

	public void setParamPrueba(String paramPrueba) {
		this.paramPrueba = paramPrueba;
	}

	@Column(name = "T_RESULTADO_PRUEBA", length = 500)
	public String getResultadoPrueba() {
		return this.resultadoPrueba;
	}

	public void setResultadoPrueba(String resultadoPrueba) {
		this.resultadoPrueba = resultadoPrueba;
	}

	@Column(name = "L_ASINCRONO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getAsincrono() {
		return asincrono;
	}

	public void setAsincrono(Boolean asincrono) {
		this.asincrono = asincrono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioWeb")
	public Set<ErrorServicioWeb> getErroresServicioWeb() {
		return erroresServicioWeb;
	}

	public void setErroresServicioWeb(Set<ErrorServicioWeb> erroresServicioWeb) {
		this.erroresServicioWeb = erroresServicioWeb;
	}
	
	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServicioWeb))
			return false;
		ServicioWeb castOther = (ServicioWeb) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "ID: " + identificador + ", URL: " + url + ", tipo: " + tipoEntrada;
	}

}
