//TODO:faltaria una relacion
package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
* Subcargo generated by hbm2java
*/
@Entity
@Audited
@Table(name = "TRA_SUBCARGOS")
public class Subcargo implements java.io.Serializable {

	private static final long serialVersionUID = 4851614658829626581L;
	private Long id;
	private Date version;
	private Dotacion dotacion;
	private String descripcion;
	private Byte numHoras;
	private long numCupos;
	private String codUsuarioBloq;
	
	//private Set<CasoDocumento> casoDocumentos = new HashSet<CasoDocumento>(0);
	//private Set<CaminoTraEsp> caminosTraEsp = new HashSet<CaminoTraEsp>(0);
	
	public Subcargo() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_SUBC_X_SUBC")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_SUBC", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RPLS_X_RPLS", nullable = false)
	public Dotacion getDotacion() {
		return this.dotacion;
	}

	public void setDotacion(Dotacion dotacion) {
		this.dotacion = dotacion;
	}

	@Column(name = "D_SUBC", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "N_HORAS", precision = 2, scale = 0)
	public Byte getNumHoras() {
		return this.numHoras;
	}

	public void setNumHoras(Byte numHoras) {
		this.numHoras = numHoras;
	}

	@Column(name = "N_CUPOS", nullable = false, precision = 10, scale = 0)
	public long getNumCupos() {
		return this.numCupos;
	}

	public void setNumCupos(long numCupos) {
		this.numCupos = numCupos;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcargo")
	public Set<CasoDocumento> getCasoDocumentos() {
		return this.casoDocumentos;
	}

	public void setCasoDocumentos(Set<CasoDocumento> casoDocumentos) {
		this.casoDocumentos = casoDocumentos;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcargo")
	public Set<CaminoTraEsp> getCaminosTraEsp() {
		return caminosTraEsp;
	}

	public void setCaminosTraEsp(Set<CaminoTraEsp> caminosTraEsp) {
		this.caminosTraEsp = caminosTraEsp;
	}
*/
	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Subcargo))
			return false;
		Subcargo castOther = (Subcargo) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

}
