package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 02-nov-2011 16:29:53 by Hibernate Tools 3.4.0.CR1

import static jakarta.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;
import org.hibernate.envers.Audited;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_SUBROGACIONES")
public class Subrogacion implements java.io.Serializable {

	private static final long serialVersionUID = 1162367796282762393L;

	private Long id;
	private Date version;
	private Servicio servicio;
	private Usuario usuarioSubrogado;
	private Usuario usuarioSubrogante;
	private Date fechaInicio;
	private Date fechaFin;
	private Perfil perfil;
	private RuUsuario ruUsuarioSubrogado;  // FK to RU_USUARIOS for dual-write strategy
	private RuUsuario ruUsuarioSubrogante;  // FK to RU_USUARIOS for dual-write strategy
		
	public Subrogacion() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_SUBR_X_SUBR")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_SUBR", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV", nullable = false)
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}
	
	/**
	 * @return the usuarioSubrogado
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUA_X_USUA", nullable = false)
	public Usuario getUsuarioSubrogado() {
		return usuarioSubrogado;
	}

	/**
	 * @param usuarioSubrogado the usuarioSubrogado to set
	 */
	public void setUsuarioSubrogado(Usuario usuarioSubrogado) {
		this.usuarioSubrogado = usuarioSubrogado;
	}

	/**
	 * @return the usuarioSubrogante
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUA_X_USUA_S", nullable = false)
	public Usuario getUsuarioSubrogante() {
		return usuarioSubrogante;
	}

	/**
	 * @param usuarioSubrogante the usuarioSubrogante to set
	 */
	public void setUsuarioSubrogante(Usuario usuarioSubrogante) {
		this.usuarioSubrogante = usuarioSubrogante;
	}

	/**
	 * @return the fechaInicio
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_INICIO", length = 7)
	public Date getFechaInicio() {
		return fechaInicio;
	}

	/**
	 * @param fechaInicio the fechaInicio to set
	 */
	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	/**
	 * @return the fechaFin
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_FIN", length = 7)
	public Date getFechaFin() {
		return fechaFin;
	}

	/**
	 * @param fechaFin the fechaFin to set
	 */
	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}
	
	/**
	 * @return the perfil
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERF_X_PERF", nullable = false)
	public Perfil getPerfil() {
		return perfil;
	}

	/**
	 * @param usuarioSubrogante the usuarioSubrogante to set
	 */
	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUA_RU_X_USUA")
	public RuUsuario getRuUsuarioSubrogado() {
		return ruUsuarioSubrogado;
	}
	
	public void setRuUsuarioSubrogado(RuUsuario ruUsuarioSubrogado) {
		this.ruUsuarioSubrogado = ruUsuarioSubrogado;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUA_RU_X_USUA_S")
	public RuUsuario getRuUsuarioSubrogante() {
		return ruUsuarioSubrogante;
	}
	
	public void setRuUsuarioSubrogante(RuUsuario ruUsuarioSubrogante) {
		this.ruUsuarioSubrogante = ruUsuarioSubrogante;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Subrogacion))
			return false;
		Subrogacion castOther = (Subrogacion) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	public String toString() {
		return "Usuario Subrogante: " + usuarioSubrogado + ", Usuario Subrogado: " + usuarioSubrogante + " Fecha Inicio: " + fechaInicio.toString() + "Fecha Fin" + fechaFin.toString();
	}
}
