package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 29-feb-2012 10:45:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

import jakarta.persistence.GenerationType;

/**
 * Tiposmateiras generated by hbm2java
 */

@Entity
@Audited
@Table(name = "TRA_TIPOS_MATERIAS", uniqueConstraints = @UniqueConstraint(columnNames = "C_TIMA"))
public class TipoMateria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5627230348065711537L;
	
	
	private Long id;
	private Date version;
	private String codigo;
	private String descripcion;
	private String codUsuarioBloq;
	private Set<Materia> materias = new HashSet<Materia>(0);

	public TipoMateria() {
	}

	public TipoMateria(String codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public TipoMateria(String codigo, String descripcion,
			String codUsuarioBloq, Set<Materia> materias) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.codUsuarioBloq = codUsuarioBloq;
		this.materias = materias;
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_TIMA_X_TIMA")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_TIMA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}
	
	@Column(name = "C_TIMA", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}
	
	@Column(name = "D_TIMA", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "C_USUARIO_BLOQ", length = 30)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMateria")
	public Set<Materia> getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set<Materia> materias) {
		this.materias = materias;
	}
	
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoMateria))
			return false;
		TipoMateria castOther = (TipoMateria) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

}
