package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_TIPOS_DOCUMENTOS", uniqueConstraints = @UniqueConstraint(columnNames = "S_TIDO"))
public class TipoDocumento implements java.io.Serializable {

	private static final long serialVersionUID = 7405951372550937190L;

	private Long id;
	private Date version;
	private Long codSiaper;
	private String descripcion;
	private String codUsuarioBloq;
	private Boolean activo;
	private boolean firmaSoloContralor;
	private boolean exento;
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<TipoDocumentosServicio> tipoDocumentoServicio = new HashSet<TipoDocumentosServicio>(0);
	private Set<ActoMasivo> actosMasivos = new HashSet<ActoMasivo>(0);
	
	// Atributos para la generacion de previews (No se almacenan en BBDD)
	private String descripcionSinEfectoPreview;
	
	public TipoDocumento() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_TIDO_X_TIDO")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_TIDO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "S_TIDO", precision = 12, nullable=false, scale = 0)
	public Long getCodSiaper() {
		return codSiaper;
	}
	
	public void setCodSiaper(Long codSiaper) {
		this.codSiaper = codSiaper;
	}
	
	@Column(name = "D_TIDO", length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "L_ACTIVO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	
	@Column(name = "L_FIRMA_SOLO_CONTRALOR", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isFirmaSoloContralor() {
		return firmaSoloContralor;
	}

	public void setFirmaSoloContralor(boolean firmaSoloContralor) {
		this.firmaSoloContralor = firmaSoloContralor;
	}
	
	@Column(name = "L_EXENTO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public boolean isExento() {
		return exento;
	}

	public void setExento(boolean exento) {
		this.exento = exento;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDocumento")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDocumento")
	public Set<TipoDocumentosServicio> getTipoDocumentoServicio() {
		return this.tipoDocumentoServicio;
	}

	public void setTipoDocumentoServicio(Set<TipoDocumentosServicio> tipoDocumentosServicio) {
		this.tipoDocumentoServicio = tipoDocumentosServicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoDocumento))
			return false;
		TipoDocumento castOther = (TipoDocumento) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
	public String toString() {
		return "Nombre: " + codSiaper + ", descripción: " + descripcion;
	}
	
	@Transient
	public String getDescripcionPreview ()
	{
		if (descripcion != null && descripcion.trim().toUpperCase().startsWith(decreto))
			return decreto;
		else
			return "RESUELVO";
	}
	
	private static final String decreto = "DECRETO";
	
	@Transient
	public String getDescripcionPreview2 ()
	{
		String res = getDescripcionPreview();
		if ( !decreto.equals(res))
			return "RESOLUCIÓN";
		else 
			return res;
	}

	@Transient
	public String getDescripcionSinEfectoPreview() {
		return descripcionSinEfectoPreview;
	}

	public void setDescripcionSinEfectoPreview(String descripcionSinEfectoPreview) {
		this.descripcionSinEfectoPreview = descripcionSinEfectoPreview;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDocumento")
	public Set<ActoMasivo> getActosMasivos() {
		return this.actosMasivos;
	}

	public void setActosMasivos(Set<ActoMasivo> actosMasivos) {
		this.actosMasivos = actosMasivos;
	}
}
