package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-mar-2012 8:47:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * TiposcalidadjReporte generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_TIPCALDJ_X_REPORTE")
public class TipoCalidadjReporte implements java.io.Serializable {

	private Long id;
	private Date version;
	private TipoCalidadJuridica tipoCalidadJuridica;
	private Reporte reporte;
	private String codUsuarioBloq;

	public TipoCalidadjReporte() {
	}

	public TipoCalidadjReporte(TipoCalidadJuridica tipoCalidadJuridica,
			Reporte reporte) {
		this.tipoCalidadJuridica = tipoCalidadJuridica;
		this.reporte = reporte;
	}

	public TipoCalidadjReporte(TipoCalidadJuridica tipoCalidadJuridica,
			Reporte reporte, String codUsuarioBloq) {
		this.tipoCalidadJuridica = tipoCalidadJuridica;
		this.reporte = reporte;
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_TCJR_X_TCJR")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_TCJR", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TICJ_X_TICJ", nullable = false)
	public TipoCalidadJuridica getTipoCalidadJuridica() {
		return this.tipoCalidadJuridica;
	}

	public void setTipoCalidadJuridica(TipoCalidadJuridica tipoCalidadJuridica) {
		this.tipoCalidadJuridica = tipoCalidadJuridica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPO_X_REPO", nullable = false)
	public Reporte getReporte() {
		return this.reporte;
	}

	public void setReporte(Reporte reporte) {
		this.reporte = reporte;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 30)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

}
