package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-mar-2012 8:47:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * TipoCalidadJuridica generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_TIP_CAL_JURIDICA", uniqueConstraints = @UniqueConstraint(columnNames = "S_TICJ"))
public class TipoCalidadJuridica implements java.io.Serializable {

	private Long id;
	private Date version;
	private String nombre;
	private String descripcion;
	private Boolean valido;
	private String codUsuarioBloq;
	private Set<TipoCalidadjReporte> tiposcalidadjReportes = new HashSet<TipoCalidadjReporte>(
			0);

	public TipoCalidadJuridica() {
	}

	public TipoCalidadJuridica(String nombre, String descripcion, Boolean valido) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valido = valido;
	}

	public TipoCalidadJuridica(String nombre, String descripcion,
			Boolean valido, String codUsuarioBloq,
			Set<TipoCalidadjReporte> tiposcalidadjReportes) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valido = valido;
		this.codUsuarioBloq = codUsuarioBloq;
		this.tiposcalidadjReportes = tiposcalidadjReportes;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_TICJ_X_TICJ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_TICJ", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "S_TICJ", unique = true, nullable = false, length = 12)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "D_TICJ", nullable = false, length = 255)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "L_VALIDO", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getValido() {
		return this.valido;
	}

	public void setValido(Boolean valido) {
		this.valido = valido;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 30)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCalidadJuridica")
	public Set<TipoCalidadjReporte> getTiposcalidadjReportes() {
		return this.tiposcalidadjReportes;
	}

	public void setTiposcalidadjReportes(
			Set<TipoCalidadjReporte> tiposcalidadjReportes) {
		this.tiposcalidadjReportes = tiposcalidadjReportes;
	}

}
