//TODO: FADEConfiguration
package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 02-nov-2011 16:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;
//import org.jboss.seam.annotations.security.management.UserFirstName;
//import org.jboss.seam.annotations.security.management.UserLastName;
//import org.jboss.seam.annotations.security.management.UserPrincipal;
//import org.jboss.seam.annotations.security.management.UserRoles;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;
//import cl.contraloria.fade.core.FADEConfiguration;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_USUARIOS_EXTERNOS", uniqueConstraints = { @UniqueConstraint(columnNames = "T_RUN"), @UniqueConstraint(columnNames = "C_USUARIO") })
public class UsuarioExterno implements java.io.Serializable {

	private static final long serialVersionUID = 1162367796282762393L;

	private Long id;
	private Date version;
	private Servicio servicio;
	private String codigo;
	private String run;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String origen;
	private Boolean activo;
	private String codUsuarioBloq;
	private String email;
	
	private Set<UsuarioExternoPerfil> perfiles = new HashSet<UsuarioExternoPerfil>(0);


	// Transient
	private boolean selected;
	
	
	
	
	
	
	public UsuarioExterno() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_USUA_X_USUA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_USUA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV", nullable = false)
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

//	@UserPrincipal
	@Column(name = "C_USUARIO", unique = true, nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codUsuario) {
		this.codigo = codUsuario;
	}

	@Column(name = "T_RUN", unique = true, nullable = false, length = 10)
	public String getRun() {
		return this.run;
	}

	public void setRun(String run) {
		this.run = run;
	}

//	@UserFirstName
	@Column(name = "T_NOMBRE", length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "T_APELLIDO1", length = 150)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "T_APELLIDO2", length = 150)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "V_ORIGEN", length = 1)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "L_ACTIVO", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

//	@UserRoles
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioExternoPerfil> getPerfiles() {
		return this.perfiles;
	}

	public void setPerfiles(Set<UsuarioExternoPerfil> usuarioPerfiles) {
		this.perfiles = usuarioPerfiles;
	}
		
	@Column(name = "T_CORREO_ELECTRONICO", length = 150)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}


	@Transient
	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	

	@Transient
//	@UserLastName
	public String getApellidos() {
		if (this.apellido1 != null && !"".equals(this.apellido1)) {
			if (this.apellido2 != null && !"".equals(this.apellido2)) {
				return this.apellido1 + " " + this.apellido2;
			} else {
				return this.apellido1;
			}
		} else {
			if (this.apellido2 != null && !"".equals(this.apellido2)) {
				return this.apellido2;
			} else {
				return "";
			}
		}
	}
	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Usuario))
			return false;
		Usuario castOther = (Usuario) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	public String toString() {
		return "Código: " + codigo + ", Usuario: " + run + " - " + getApellidos() + ", " + nombre;
	}
	
	@Transient
	public String getNombreCompleto() {
		if (this.nombre != null && !"".equals(this.nombre)) {
			return this.nombre + " " + getApellidos();
		} else {
			return getApellidos();
		}
	}
	
		
	
	
	
}
