//TODO: borre fade
package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 02-nov-2011 16:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

//import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;
//import org.jboss.seam.annotations.security.management.UserFirstName;
//import org.jboss.seam.annotations.security.management.UserLastName;
//import org.jboss.seam.annotations.security.management.UserPrincipal;
//import org.jboss.seam.annotations.security.management.UserRoles;

import cl.contraloria.fade.core.FADEConfiguration;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_USUARIOS", uniqueConstraints = { @UniqueConstraint(columnNames = "T_RUN"), @UniqueConstraint(columnNames = "C_USUARIO") })
public class Usuario implements java.io.Serializable {

	private static final long serialVersionUID = 1162367796282762393L;

	private Long id;
	private Date version;
	private Servicio servicio;
	private String codigo;
	private String run;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String origen;
	private Boolean activo;
	private String codUsuarioBloq;
	private String email;
	private String configFirma;
	private String configFirmaPDF;
	private String usuarioConfigFirma;
	private Set<UsuarioPerfil> perfiles = new HashSet<UsuarioPerfil>(0);
//	private Set<FirmaDoc> firmas = new HashSet<FirmaDoc>(0);
//	private Set<Volcado> volcados = new HashSet<Volcado>(0);

	// Transient
	private boolean selected;
	private Division division;
	
	//private Set<Subrogacion> subrogados = new HashSet<Subrogacion>(0);
	private Set<Subrogacion> subrogantes = new HashSet<Subrogacion>(0);
	
	private boolean subrogaContralor;
	private boolean subrogaSubContralor;
	private boolean subrogaContralorRegional;
	
	private boolean diarioOficial;
	
	private boolean bandejaContralor;
	
	private boolean firmaHSMCGR;
	
	private boolean firmaHSMExterno;
	
	private boolean titular;
	
	private FADEConfiguration fadeConfig;
	
	private Set<FirmanteAdjunto> firmanteAdjunto = new HashSet<FirmanteAdjunto>(0);
	
	private Set<FirmanteCgr> usuarioFirmanteCgr = new HashSet<FirmanteCgr>(0);
	
	public Usuario() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_USUA_X_USUA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_USUA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_X_SERV", nullable = false)
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

//	@UserPrincipal
	@Column(name = "C_USUARIO", unique = true, nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codUsuario) {
		this.codigo = codUsuario;
	}

	@Column(name = "T_RUN", unique = true, nullable = false, length = 10)
	public String getRun() {
		return this.run;
	}

	public void setRun(String run) {
		this.run = run;
	}

//	@UserFirstName
	@Column(name = "T_NOMBRE", length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "T_APELLIDO1", length = 150)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "T_APELLIDO2", length = 150)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "V_ORIGEN", length = 1)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "L_ACTIVO", nullable = false, length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

//	@UserRoles
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioPerfil> getPerfiles() {
		return this.perfiles;
	}

	public void setPerfiles(Set<UsuarioPerfil> usuarioPerfiles) {
		this.perfiles = usuarioPerfiles;
	}


//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
//	public Set<FirmaDoc> getFirmas() {
//		return this.firmas;
//	}
//
//	public void setFirmas(Set<FirmaDoc> firmaDoces) {
//		this.firmas = firmaDoces;
//	}
	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
//	public Set<Volcado> getVolcados() {
//		return volcados;
//	}
//
//	public void setVolcados(Set<Volcado> volcados) {
//		this.volcados = volcados;
//	}

	@Column(name = "T_CORREO_ELECTRONICO", length = 150)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "T_CONF_FIRMA", length = 150)
	public String getConfigFirma() {
		return configFirma;
	}

	public void setConfigFirma(String configFirma) {
		this.configFirma = configFirma;
	}
	
	@Column(name = "T_USUARIO_CONF_FIRMA_PDF", length = 150)
	public String getConfigFirmaPDF() {
		return configFirmaPDF;
	}

	public void setConfigFirmaPDF(String configFirmaPDF) {
		this.configFirmaPDF = configFirmaPDF;
	}

	@Column(name = "T_USUARIO_CONF_FIRMA", length = 150)
	public String getUsuarioConfigFirma() {
		return usuarioConfigFirma;
	}

	public void setUsuarioConfigFirma(String usuarioConfigFirma) {
		this.usuarioConfigFirma = usuarioConfigFirma;
	}

	@Transient
	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	@Transient
	public Division getDivision() {
		return division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@Transient
//	@UserLastName
	public String getApellidos() {
		if (this.apellido1 != null && !"".equals(this.apellido1)) {
			if (this.apellido2 != null && !"".equals(this.apellido2)) {
				return this.apellido1 + " " + this.apellido2;
			} else {
				return this.apellido1;
			}
		} else {
			if (this.apellido2 != null && !"".equals(this.apellido2)) {
				return this.apellido2;
			} else {
				return "";
			}
		}
	}
	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Usuario))
			return false;
		Usuario castOther = (Usuario) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	public String toString() {
		return "Código: " + codigo + ", Usuario: " + run + " - " + getApellidos() + ", " + nombre;
	}
	
	@Transient
	public String getNombreCompleto() {
		if (this.nombre != null && !"".equals(this.nombre)) {
			return this.nombre + " " + getApellidos();
		} else {
			return getApellidos();
		}
	}
	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioSubrogado")
	public Set<Subrogacion> getSubrogados() {
		return this.subrogados;
	}

	public void setSubrogados(Set<Subrogacion> subrogados) {
		this.subrogados = subrogados;
	}
		*/
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioSubrogante")
	public Set<Subrogacion> getSubrogantes() {
		return this.subrogantes;
	}

	public void setSubrogantes(Set<Subrogacion> subrogantes) {
		this.subrogantes = subrogantes;
	}

	@Transient
	public boolean isSubrogaContralor() {
		return subrogaContralor;
	}

	public void setSubrogaContralor(boolean subrogaContralor) {
		this.subrogaContralor = subrogaContralor;
	}
	@Transient
	public boolean isSubrogaSubContralor() {
		return subrogaSubContralor;
	}

	public void setSubrogaSubContralor(boolean subrogaSubContralor) {
		this.subrogaSubContralor = subrogaSubContralor;
	}
	
	@Transient
	public boolean isSubrogaContralorRegional() {
		return subrogaContralorRegional;
	}

	public void setSubrogaContralorRegional(boolean subrogaContralorRegional) {
		this.subrogaContralorRegional = subrogaContralorRegional;
	}

	/**
	 * @return the diarioOficial
	 */
	@Transient
	public boolean isDiarioOficial() {
		return diarioOficial;
	}

	/**
	 * @param diarioOficial the diarioOficial to set
	 */
	public void setDiarioOficial(boolean diarioOficial) {
		this.diarioOficial = diarioOficial;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioFirmante")
	public Set<FirmanteAdjunto> getFirmanteAdjunto() {
		return firmanteAdjunto;
	}

	public void setFirmanteAdjunto(Set<FirmanteAdjunto> firmanteAdjunto) {
		this.firmanteAdjunto = firmanteAdjunto;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioFirmanteCgr")
	public Set<FirmanteCgr> getUsuarioFirmanteCgr() {
		return usuarioFirmanteCgr;
	}

	public void setUsuarioFirmanteCgr(Set<FirmanteCgr> usuarioFirmanteCgr) {
		this.usuarioFirmanteCgr = usuarioFirmanteCgr;
	}
	
	/**
	 * @return the bandejaContralor
	 */
	@Transient
	public boolean isBandejaContralor() {
		return bandejaContralor;
	}

	public void setBandejaContralor(boolean bandejaContralor) {
		this.bandejaContralor = bandejaContralor;
	}

	@Transient
	public boolean isFirmaHSMCGR() {
		return firmaHSMCGR;
	}

	public void setFirmaHSMCGR(boolean firmaHSMCGR) {
		this.firmaHSMCGR = firmaHSMCGR;
	}

	@Transient
	public boolean isFirmaHSMExterno() {
		return firmaHSMExterno;
	}

	public void setFirmaHSMExterno(boolean firmaHSMExterno) {
		this.firmaHSMExterno = firmaHSMExterno;
	}

	@Transient
	public FADEConfiguration getFadeConfig() {
		return fadeConfig;
	}

	public void setFadeConfig(FADEConfiguration fadeConfig) {
		this.fadeConfig = fadeConfig;
	}

	@Transient
	public boolean isTitular() {
		return titular;
	}

	public void setTitular(boolean titular) {
		this.titular = titular;
	}
	
}
