package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 01-sep-2011 13:49:13 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;
//import org.joda.time.DateTime;

import java.time.Instant;
import java.time.ZoneId;
import java.time.ZonedDateTime;

/**
 * Calidad generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_VOLCADOS")
public class Volcado implements Serializable, Entidad {

	private static final long serialVersionUID = 1032040433875968434L;
	
	private Long id;
	private Usuario usuario;
	private Documento documento;
	private String codigoEstado;
	private Date version;
	private String codUsuarioBloq;
	private Integer nVersion;
	
	private boolean seleccionado;
	private boolean beforeYesterday;

	public Volcado() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_VOLC_X_VOLC")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_VOLC", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "C_ESTADO", nullable = false, length = 10)
	public String getCodigoEstado() {
		return codigoEstado;
	}

	public void setCodigoEstado(String codigoEstado) {
		this.codigoEstado = codigoEstado;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}
	
	@Column(name = "N_VERSION", length = 9)
	public Integer getnVersion() {
		return nVersion;
	}

	public void setnVersion(Integer nVersion) {
		this.nVersion = nVersion;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUA_X_USUA", nullable = false)
	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCU_X_DOCU", nullable = false)
	public Documento getDocumento() {
		return documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}
	
	@Transient
	public boolean isSeleccionado() {
		return seleccionado;
	}

	public void setSeleccionado(boolean seleccionado) {
		this.seleccionado = seleccionado;
	}

	@Transient
	public boolean isBeforeYesterday() {
	    Instant versionInstant = getVersion().toInstant(); // suponiendo que getVersion() es Date
	    ZonedDateTime fVolcado = versionInstant.atZone(ZoneId.systemDefault());
	    ZonedDateTime fYesterday = ZonedDateTime.now().minusHours(24);
	    return fVolcado.isBefore(fYesterday);
	}
	/*
	public boolean isBeforeYesterday() {
		DateTime fVolcado = new DateTime(getVersion());
		DateTime fYesterday = (DateTime.now()).minusHours(24);
		beforeYesterday = fVolcado.isBefore(fYesterday);
		return beforeYesterday;
	}
*/
	public void setBeforeYesterday(boolean isBeforeYesterday) {
		this.beforeYesterday = isBeforeYesterday;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Volcado))
			return false;
		Volcado castOther = (Volcado) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
	
}
