package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 09-feb-2012 17:49:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

import org.hibernate.envers.Audited;

/**
 * Materia generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_WARNINGS_FIRMA")
public class WarningFirma implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 9146108989120925438L;
	
	private Long id;
	private Date version;	
	private Warning warning;
	private String descripcionWarning;	

	public WarningFirma() {
	}

	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_WAFI_X_WAFI")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_WAFI", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WARN_X_WARN", nullable = false)
	public Warning getWarning() {
		return this.warning;
	}

	public void setWarning(Warning warning) {
		this.warning = warning;
	}
		
	@Column(name = "D_WARNING", length = 250)
	public String getDescripcionWarning() {
		return descripcionWarning;
	}

	public void setDescripcionWarning(String descripcionWarning) {
		this.descripcionWarning = descripcionWarning;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WarningFirma))
			return false;
		WarningFirma castOther = (WarningFirma) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}
			
}
