package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 18-oct-2011 11:46:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * Warning generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_WARNINGS", uniqueConstraints = @UniqueConstraint(columnNames = "C_WARN"))
public class Warning implements java.io.Serializable {

	private static final long serialVersionUID = -4406591422239975847L;

	private Long id;
	private Date version;
	private String codigo;
	private String descripcion;
	private Boolean estudio;
	private String codUsuarioBloq;	
	private Set<Requisito> requisitosAlternativaNo = new HashSet<Requisito>(0);
	private Set<Requisito> requisitosAlternativaSi = new HashSet<Requisito>(0);
	private Set<WarningCaso> warningCasos = new HashSet<WarningCaso>(0);
	private int tipoWarning;
	private WarningFirma warningFirma;
	
	public static enum TIPO_WARNING {
		CAMINO_TRA(0), INCOMPATIBLE(1), CESE_SML(2), LEY_MEDICA(3), ESTUDIO_CARGO_INC(4);
		
		private int tipo;
		
		private TIPO_WARNING(int tipo) {
			this.tipo = tipo;
		}
		
		public String toString() {
			switch (tipo) {
			case 0:
				return "Camino Tra";
			case 1:
				return "Incompatible";
			case 2:
				return "Cese por el solo ministerio de la ley";
			case 3:
				return "Estudio por la ley médica";
			case 4:
				return "Estudio Cargo incompatible";	
			default:
				return "";
			}
		}
		
		public int getTipo() {
			return tipo;
		}
		
		public static TIPO_WARNING get (int c) {
			for (TIPO_WARNING r : values()) {
				if (r.tipo == c) return r;
			}
			return null;
		}		
	}
	
	public Warning() {
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_WARN_X_WARN")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_WARN", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "C_WARN", unique = true, nullable = false, length = 25)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "D_WARN", length = 2000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "L_ESTUDIO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getEstudio() {
		return this.estudio;
	}

	public void setEstudio(Boolean estudio) {
		this.estudio = estudio;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warningAlternativaNo")
	public Set<Requisito> getRequisitosAlternativaNo() {
		return this.requisitosAlternativaNo;
	}

	public void setRequisitosAlternativaNo(Set<Requisito> requisitosForWarnAlternatNo) {
		this.requisitosAlternativaNo = requisitosForWarnAlternatNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warningAlternativaSi")
	public Set<Requisito> getRequisitosAlternativaSi() {
		return this.requisitosAlternativaSi;
	}

	public void setRequisitosAlternativaSi(Set<Requisito> requisitosForWarnAlternatSi) {
		this.requisitosAlternativaSi = requisitosForWarnAlternatSi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warning")
	public Set<WarningCaso> getWarningCasos() {
		return this.warningCasos;
	}

	public void setWarningCasos(Set<WarningCaso> warningCasos) {
		this.warningCasos = warningCasos;
	}

	@Column(name = "V_TIPO_WARNING", nullable = false, length = 1)
	public int getTipoWarning() {
		return tipoWarning;
	}

	public void setTipoWarning(int tipoWarning) {
		this.tipoWarning = tipoWarning;
	}

	@OneToOne(mappedBy = "warning")
	public WarningFirma getWarningFirma() {
		return this.warningFirma;
	}

	public void setWarningFirma(WarningFirma warningFirma) {
		this.warningFirma = warningFirma;
	}
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Warning))
			return false;
		Warning castOther = (Warning) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	public String toString() {
		return "Código: " + codigo + ", descripción: " + descripcion + ", envia a estudio: " + (estudio != null && estudio ? "Si" : "No");
	}

}
