package cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model;

// Generated 03-oct-2011 16:27:55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;

import cl.cgr.siaper.ru.api.administracion_servicios_publicos.hist.model.converter.BooleanSiNoConverter;

/**
 * WarningCaso generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TRA_WARNINGS_CASOS")
public class WarningCaso implements java.io.Serializable {

	private static final long serialVersionUID = 7804009617292738880L;

	private Long id;
	private Date version;
	private CasoDocumento casoDocumento;
	private Warning warning;
	private String observaciones;
	private String atributo;
	private String codUsuarioBloq;
	private String codUsuarioAnalista;
	private Boolean analisisCorrecto;
	private Boolean estudiar;
	
	//transient attributes
	private boolean modificable;

	public WarningCaso() {
		this.estudiar = Boolean.FALSE;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "generator", sequenceName = "TRA_S_WACA_X_WACA")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@Column(name = "X_WACA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VERSION", length = 7)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CADO_X_CADO", nullable = false)
	public CasoDocumento getCasoDocumento() {
		return this.casoDocumento;
	}

	public void setCasoDocumento(CasoDocumento casoDocumento) {
		this.casoDocumento = casoDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WARN_X_WARN", nullable = false)
	public Warning getWarning() {
		return this.warning;
	}

	public void setWarning(Warning warning) {
		this.warning = warning;
	}

	@Column(name = "T_OBSERVACIONES", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "T_ATRIBUTO", length = 250)
	public String getAtributo() {
		return this.atributo;
	}

	public void setAtributo(String atributo) {
		this.atributo = atributo;
	}

	@Column(name = "C_USUARIO_BLOQ", length = 50)
	public String getCodUsuarioBloq() {
		return this.codUsuarioBloq;
	}

	public void setCodUsuarioBloq(String codUsuarioBloq) {
		this.codUsuarioBloq = codUsuarioBloq;
	}

	@Column(name = "C_USUARIO_ANALISTA", length = 50)
	public String getCodUsuarioAnalista() {
		return this.codUsuarioAnalista;
	}

	public void setCodUsuarioAnalista(String codUsuarioAnalista) {
		this.codUsuarioAnalista = codUsuarioAnalista;
	}

	@Column(name = "L_ANALISIS_CORRECTO", length = 1)
	@Convert(converter = BooleanSiNoConverter.class)
	public Boolean getAnalisisCorrecto() {
		return this.analisisCorrecto;
	}

	public void setAnalisisCorrecto(Boolean analisisCorrecto) {
		this.analisisCorrecto = analisisCorrecto;
	}

	@Column(name = "L_ESTUDIAR", length = 1)
	public Boolean getEstudiar() {
		return estudiar;
	}

	public void setEstudiar(Boolean estudiar) {
		this.estudiar = estudiar;
	}

	@Transient
	public boolean isModificable() {
		return modificable;
	}

	public void setModificable(boolean modificable) {
		this.modificable = modificable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WarningCaso))
			return false;
		WarningCaso castOther = (WarningCaso) other;
		return this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId());
	}

	public String toString() {
		return "Caso: (" + casoDocumento + "), warning: (" + warning + "), usuario analista: " + (codUsuarioAnalista != null ? codUsuarioAnalista : "") + ", resultado: " + (analisisCorrecto != null && analisisCorrecto ? "Si" : "No");
	}

}
